// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/frb.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<FrbNudgeEvent> dco_decode_StreamSink_frb_nudge_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  FrbBook dco_decode_box_autoadd_frb_book(dynamic raw);

  @protected
  FrbBookMetadata dco_decode_box_autoadd_frb_book_metadata(dynamic raw);

  @protected
  FrbCollection dco_decode_box_autoadd_frb_collection(dynamic raw);

  @protected
  FrbContact dco_decode_box_autoadd_frb_contact(dynamic raw);

  @protected
  FrbDirectoryConfig dco_decode_box_autoadd_frb_directory_config(dynamic raw);

  @protected
  FrbRegisterParams dco_decode_box_autoadd_frb_register_params(dynamic raw);

  @protected
  FrbRelayConfig dco_decode_box_autoadd_frb_relay_config(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FrbBook dco_decode_frb_book(dynamic raw);

  @protected
  FrbBookMetadata dco_decode_frb_book_metadata(dynamic raw);

  @protected
  FrbBookNote dco_decode_frb_book_note(dynamic raw);

  @protected
  FrbCatalogEntry dco_decode_frb_catalog_entry(dynamic raw);

  @protected
  FrbCollection dco_decode_frb_collection(dynamic raw);

  @protected
  FrbCollectionBook dco_decode_frb_collection_book(dynamic raw);

  @protected
  FrbContact dco_decode_frb_contact(dynamic raw);

  @protected
  FrbCoverCandidate dco_decode_frb_cover_candidate(dynamic raw);

  @protected
  FrbDirectoryConfig dco_decode_frb_directory_config(dynamic raw);

  @protected
  FrbDiscoveredPeer dco_decode_frb_discovered_peer(dynamic raw);

  @protected
  FrbGamificationConfig dco_decode_frb_gamification_config(dynamic raw);

  @protected
  FrbGamificationStatus dco_decode_frb_gamification_status(dynamic raw);

  @protected
  FrbHangmanChar dco_decode_frb_hangman_char(dynamic raw);

  @protected
  FrbHangmanLeaderboardEntry dco_decode_frb_hangman_leaderboard_entry(
    dynamic raw,
  );

  @protected
  FrbHangmanScore dco_decode_frb_hangman_score(dynamic raw);

  @protected
  FrbHangmanSetup dco_decode_frb_hangman_setup(dynamic raw);

  @protected
  FrbHubBorrowRequest dco_decode_frb_hub_borrow_request(dynamic raw);

  @protected
  FrbHubFollow dco_decode_frb_hub_follow(dynamic raw);

  @protected
  FrbHubProfile dco_decode_frb_hub_profile(dynamic raw);

  @protected
  FrbLeaderboardEntry dco_decode_frb_leaderboard_entry(dynamic raw);

  @protected
  FrbLeaderboardResponse dco_decode_frb_leaderboard_response(dynamic raw);

  @protected
  FrbLinkedDevice dco_decode_frb_linked_device(dynamic raw);

  @protected
  FrbLoan dco_decode_frb_loan(dynamic raw);

  @protected
  FrbLoanSettings dco_decode_frb_loan_settings(dynamic raw);

  @protected
  FrbMemoryCard dco_decode_frb_memory_card(dynamic raw);

  @protected
  FrbMemoryLeaderboardEntry dco_decode_frb_memory_leaderboard_entry(
    dynamic raw,
  );

  @protected
  FrbMemoryScore dco_decode_frb_memory_score(dynamic raw);

  @protected
  FrbNotification dco_decode_frb_notification(dynamic raw);

  @protected
  FrbNudgeEvent dco_decode_frb_nudge_event(dynamic raw);

  @protected
  FrbOperationLogEntry dco_decode_frb_operation_log_entry(dynamic raw);

  @protected
  FrbOperationLogStats dco_decode_frb_operation_log_stats(dynamic raw);

  @protected
  FrbPairingConfirmation dco_decode_frb_pairing_confirmation(dynamic raw);

  @protected
  FrbPairingOffer dco_decode_frb_pairing_offer(dynamic raw);

  @protected
  FrbPendingReviewOp dco_decode_frb_pending_review_op(dynamic raw);

  @protected
  FrbPuzzleBoard dco_decode_frb_puzzle_board(dynamic raw);

  @protected
  FrbPuzzleLeaderboardEntry dco_decode_frb_puzzle_leaderboard_entry(
    dynamic raw,
  );

  @protected
  FrbPuzzleScore dco_decode_frb_puzzle_score(dynamic raw);

  @protected
  FrbRegisterParams dco_decode_frb_register_params(dynamic raw);

  @protected
  FrbRelayConfig dco_decode_frb_relay_config(dynamic raw);

  @protected
  FrbStreakInfo dco_decode_frb_streak_info(dynamic raw);

  @protected
  FrbSyncResult dco_decode_frb_sync_result(dynamic raw);

  @protected
  FrbTag dco_decode_frb_tag(dynamic raw);

  @protected
  FrbTrackProgress dco_decode_frb_track_progress(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<FrbBook> dco_decode_list_frb_book(dynamic raw);

  @protected
  List<FrbBookNote> dco_decode_list_frb_book_note(dynamic raw);

  @protected
  List<FrbCatalogEntry> dco_decode_list_frb_catalog_entry(dynamic raw);

  @protected
  List<FrbCollection> dco_decode_list_frb_collection(dynamic raw);

  @protected
  List<FrbCollectionBook> dco_decode_list_frb_collection_book(dynamic raw);

  @protected
  List<FrbContact> dco_decode_list_frb_contact(dynamic raw);

  @protected
  List<FrbCoverCandidate> dco_decode_list_frb_cover_candidate(dynamic raw);

  @protected
  List<FrbDiscoveredPeer> dco_decode_list_frb_discovered_peer(dynamic raw);

  @protected
  List<FrbHangmanChar> dco_decode_list_frb_hangman_char(dynamic raw);

  @protected
  List<FrbHangmanLeaderboardEntry>
  dco_decode_list_frb_hangman_leaderboard_entry(dynamic raw);

  @protected
  List<FrbHangmanScore> dco_decode_list_frb_hangman_score(dynamic raw);

  @protected
  List<FrbHubBorrowRequest> dco_decode_list_frb_hub_borrow_request(dynamic raw);

  @protected
  List<FrbHubFollow> dco_decode_list_frb_hub_follow(dynamic raw);

  @protected
  List<FrbHubProfile> dco_decode_list_frb_hub_profile(dynamic raw);

  @protected
  List<FrbLeaderboardEntry> dco_decode_list_frb_leaderboard_entry(dynamic raw);

  @protected
  List<FrbLinkedDevice> dco_decode_list_frb_linked_device(dynamic raw);

  @protected
  List<FrbLoan> dco_decode_list_frb_loan(dynamic raw);

  @protected
  List<FrbMemoryCard> dco_decode_list_frb_memory_card(dynamic raw);

  @protected
  List<FrbMemoryLeaderboardEntry> dco_decode_list_frb_memory_leaderboard_entry(
    dynamic raw,
  );

  @protected
  List<FrbMemoryScore> dco_decode_list_frb_memory_score(dynamic raw);

  @protected
  List<FrbNotification> dco_decode_list_frb_notification(dynamic raw);

  @protected
  List<FrbOperationLogEntry> dco_decode_list_frb_operation_log_entry(
    dynamic raw,
  );

  @protected
  List<FrbPendingReviewOp> dco_decode_list_frb_pending_review_op(dynamic raw);

  @protected
  List<FrbPuzzleLeaderboardEntry> dco_decode_list_frb_puzzle_leaderboard_entry(
    dynamic raw,
  );

  @protected
  List<FrbPuzzleScore> dco_decode_list_frb_puzzle_score(dynamic raw);

  @protected
  List<FrbTag> dco_decode_list_frb_tag(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_i_32_loose(dynamic raw);

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  FrbBookMetadata? dco_decode_opt_box_autoadd_frb_book_metadata(dynamic raw);

  @protected
  FrbCollection? dco_decode_opt_box_autoadd_frb_collection(dynamic raw);

  @protected
  FrbDirectoryConfig? dco_decode_opt_box_autoadd_frb_directory_config(
    dynamic raw,
  );

  @protected
  FrbRelayConfig? dco_decode_opt_box_autoadd_frb_relay_config(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<FrbNudgeEvent> sse_decode_StreamSink_frb_nudge_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FrbBook sse_decode_box_autoadd_frb_book(SseDeserializer deserializer);

  @protected
  FrbBookMetadata sse_decode_box_autoadd_frb_book_metadata(
    SseDeserializer deserializer,
  );

  @protected
  FrbCollection sse_decode_box_autoadd_frb_collection(
    SseDeserializer deserializer,
  );

  @protected
  FrbContact sse_decode_box_autoadd_frb_contact(SseDeserializer deserializer);

  @protected
  FrbDirectoryConfig sse_decode_box_autoadd_frb_directory_config(
    SseDeserializer deserializer,
  );

  @protected
  FrbRegisterParams sse_decode_box_autoadd_frb_register_params(
    SseDeserializer deserializer,
  );

  @protected
  FrbRelayConfig sse_decode_box_autoadd_frb_relay_config(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FrbBook sse_decode_frb_book(SseDeserializer deserializer);

  @protected
  FrbBookMetadata sse_decode_frb_book_metadata(SseDeserializer deserializer);

  @protected
  FrbBookNote sse_decode_frb_book_note(SseDeserializer deserializer);

  @protected
  FrbCatalogEntry sse_decode_frb_catalog_entry(SseDeserializer deserializer);

  @protected
  FrbCollection sse_decode_frb_collection(SseDeserializer deserializer);

  @protected
  FrbCollectionBook sse_decode_frb_collection_book(
    SseDeserializer deserializer,
  );

  @protected
  FrbContact sse_decode_frb_contact(SseDeserializer deserializer);

  @protected
  FrbCoverCandidate sse_decode_frb_cover_candidate(
    SseDeserializer deserializer,
  );

  @protected
  FrbDirectoryConfig sse_decode_frb_directory_config(
    SseDeserializer deserializer,
  );

  @protected
  FrbDiscoveredPeer sse_decode_frb_discovered_peer(
    SseDeserializer deserializer,
  );

  @protected
  FrbGamificationConfig sse_decode_frb_gamification_config(
    SseDeserializer deserializer,
  );

  @protected
  FrbGamificationStatus sse_decode_frb_gamification_status(
    SseDeserializer deserializer,
  );

  @protected
  FrbHangmanChar sse_decode_frb_hangman_char(SseDeserializer deserializer);

  @protected
  FrbHangmanLeaderboardEntry sse_decode_frb_hangman_leaderboard_entry(
    SseDeserializer deserializer,
  );

  @protected
  FrbHangmanScore sse_decode_frb_hangman_score(SseDeserializer deserializer);

  @protected
  FrbHangmanSetup sse_decode_frb_hangman_setup(SseDeserializer deserializer);

  @protected
  FrbHubBorrowRequest sse_decode_frb_hub_borrow_request(
    SseDeserializer deserializer,
  );

  @protected
  FrbHubFollow sse_decode_frb_hub_follow(SseDeserializer deserializer);

  @protected
  FrbHubProfile sse_decode_frb_hub_profile(SseDeserializer deserializer);

  @protected
  FrbLeaderboardEntry sse_decode_frb_leaderboard_entry(
    SseDeserializer deserializer,
  );

  @protected
  FrbLeaderboardResponse sse_decode_frb_leaderboard_response(
    SseDeserializer deserializer,
  );

  @protected
  FrbLinkedDevice sse_decode_frb_linked_device(SseDeserializer deserializer);

  @protected
  FrbLoan sse_decode_frb_loan(SseDeserializer deserializer);

  @protected
  FrbLoanSettings sse_decode_frb_loan_settings(SseDeserializer deserializer);

  @protected
  FrbMemoryCard sse_decode_frb_memory_card(SseDeserializer deserializer);

  @protected
  FrbMemoryLeaderboardEntry sse_decode_frb_memory_leaderboard_entry(
    SseDeserializer deserializer,
  );

  @protected
  FrbMemoryScore sse_decode_frb_memory_score(SseDeserializer deserializer);

  @protected
  FrbNotification sse_decode_frb_notification(SseDeserializer deserializer);

  @protected
  FrbNudgeEvent sse_decode_frb_nudge_event(SseDeserializer deserializer);

  @protected
  FrbOperationLogEntry sse_decode_frb_operation_log_entry(
    SseDeserializer deserializer,
  );

  @protected
  FrbOperationLogStats sse_decode_frb_operation_log_stats(
    SseDeserializer deserializer,
  );

  @protected
  FrbPairingConfirmation sse_decode_frb_pairing_confirmation(
    SseDeserializer deserializer,
  );

  @protected
  FrbPairingOffer sse_decode_frb_pairing_offer(SseDeserializer deserializer);

  @protected
  FrbPendingReviewOp sse_decode_frb_pending_review_op(
    SseDeserializer deserializer,
  );

  @protected
  FrbPuzzleBoard sse_decode_frb_puzzle_board(SseDeserializer deserializer);

  @protected
  FrbPuzzleLeaderboardEntry sse_decode_frb_puzzle_leaderboard_entry(
    SseDeserializer deserializer,
  );

  @protected
  FrbPuzzleScore sse_decode_frb_puzzle_score(SseDeserializer deserializer);

  @protected
  FrbRegisterParams sse_decode_frb_register_params(
    SseDeserializer deserializer,
  );

  @protected
  FrbRelayConfig sse_decode_frb_relay_config(SseDeserializer deserializer);

  @protected
  FrbStreakInfo sse_decode_frb_streak_info(SseDeserializer deserializer);

  @protected
  FrbSyncResult sse_decode_frb_sync_result(SseDeserializer deserializer);

  @protected
  FrbTag sse_decode_frb_tag(SseDeserializer deserializer);

  @protected
  FrbTrackProgress sse_decode_frb_track_progress(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<FrbBook> sse_decode_list_frb_book(SseDeserializer deserializer);

  @protected
  List<FrbBookNote> sse_decode_list_frb_book_note(SseDeserializer deserializer);

  @protected
  List<FrbCatalogEntry> sse_decode_list_frb_catalog_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbCollection> sse_decode_list_frb_collection(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbCollectionBook> sse_decode_list_frb_collection_book(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbContact> sse_decode_list_frb_contact(SseDeserializer deserializer);

  @protected
  List<FrbCoverCandidate> sse_decode_list_frb_cover_candidate(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbDiscoveredPeer> sse_decode_list_frb_discovered_peer(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbHangmanChar> sse_decode_list_frb_hangman_char(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbHangmanLeaderboardEntry>
  sse_decode_list_frb_hangman_leaderboard_entry(SseDeserializer deserializer);

  @protected
  List<FrbHangmanScore> sse_decode_list_frb_hangman_score(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbHubBorrowRequest> sse_decode_list_frb_hub_borrow_request(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbHubFollow> sse_decode_list_frb_hub_follow(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbHubProfile> sse_decode_list_frb_hub_profile(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbLeaderboardEntry> sse_decode_list_frb_leaderboard_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbLinkedDevice> sse_decode_list_frb_linked_device(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbLoan> sse_decode_list_frb_loan(SseDeserializer deserializer);

  @protected
  List<FrbMemoryCard> sse_decode_list_frb_memory_card(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbMemoryLeaderboardEntry> sse_decode_list_frb_memory_leaderboard_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbMemoryScore> sse_decode_list_frb_memory_score(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbNotification> sse_decode_list_frb_notification(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbOperationLogEntry> sse_decode_list_frb_operation_log_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbPendingReviewOp> sse_decode_list_frb_pending_review_op(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbPuzzleLeaderboardEntry> sse_decode_list_frb_puzzle_leaderboard_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbPuzzleScore> sse_decode_list_frb_puzzle_score(
    SseDeserializer deserializer,
  );

  @protected
  List<FrbTag> sse_decode_list_frb_tag(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_i_32_loose(SseDeserializer deserializer);

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FrbBookMetadata? sse_decode_opt_box_autoadd_frb_book_metadata(
    SseDeserializer deserializer,
  );

  @protected
  FrbCollection? sse_decode_opt_box_autoadd_frb_collection(
    SseDeserializer deserializer,
  );

  @protected
  FrbDirectoryConfig? sse_decode_opt_box_autoadd_frb_directory_config(
    SseDeserializer deserializer,
  );

  @protected
  FrbRelayConfig? sse_decode_opt_box_autoadd_frb_relay_config(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_frb_nudge_event_Sse(
    RustStreamSink<FrbNudgeEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_frb_book(FrbBook self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_frb_book_metadata(
    FrbBookMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_collection(
    FrbCollection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_contact(
    FrbContact self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_directory_config(
    FrbDirectoryConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_register_params(
    FrbRegisterParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_frb_relay_config(
    FrbRelayConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_frb_book(FrbBook self, SseSerializer serializer);

  @protected
  void sse_encode_frb_book_metadata(
    FrbBookMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_book_note(FrbBookNote self, SseSerializer serializer);

  @protected
  void sse_encode_frb_catalog_entry(
    FrbCatalogEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_collection(FrbCollection self, SseSerializer serializer);

  @protected
  void sse_encode_frb_collection_book(
    FrbCollectionBook self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_contact(FrbContact self, SseSerializer serializer);

  @protected
  void sse_encode_frb_cover_candidate(
    FrbCoverCandidate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_directory_config(
    FrbDirectoryConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_discovered_peer(
    FrbDiscoveredPeer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_gamification_config(
    FrbGamificationConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_gamification_status(
    FrbGamificationStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_hangman_char(
    FrbHangmanChar self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_hangman_leaderboard_entry(
    FrbHangmanLeaderboardEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_hangman_score(
    FrbHangmanScore self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_hangman_setup(
    FrbHangmanSetup self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_hub_borrow_request(
    FrbHubBorrowRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_hub_follow(FrbHubFollow self, SseSerializer serializer);

  @protected
  void sse_encode_frb_hub_profile(FrbHubProfile self, SseSerializer serializer);

  @protected
  void sse_encode_frb_leaderboard_entry(
    FrbLeaderboardEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_leaderboard_response(
    FrbLeaderboardResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_linked_device(
    FrbLinkedDevice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_loan(FrbLoan self, SseSerializer serializer);

  @protected
  void sse_encode_frb_loan_settings(
    FrbLoanSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_memory_card(FrbMemoryCard self, SseSerializer serializer);

  @protected
  void sse_encode_frb_memory_leaderboard_entry(
    FrbMemoryLeaderboardEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_memory_score(
    FrbMemoryScore self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_notification(
    FrbNotification self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_nudge_event(FrbNudgeEvent self, SseSerializer serializer);

  @protected
  void sse_encode_frb_operation_log_entry(
    FrbOperationLogEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_operation_log_stats(
    FrbOperationLogStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_pairing_confirmation(
    FrbPairingConfirmation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_pairing_offer(
    FrbPairingOffer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_pending_review_op(
    FrbPendingReviewOp self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_puzzle_board(
    FrbPuzzleBoard self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_puzzle_leaderboard_entry(
    FrbPuzzleLeaderboardEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_puzzle_score(
    FrbPuzzleScore self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_register_params(
    FrbRegisterParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_relay_config(
    FrbRelayConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_streak_info(FrbStreakInfo self, SseSerializer serializer);

  @protected
  void sse_encode_frb_sync_result(FrbSyncResult self, SseSerializer serializer);

  @protected
  void sse_encode_frb_tag(FrbTag self, SseSerializer serializer);

  @protected
  void sse_encode_frb_track_progress(
    FrbTrackProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_frb_book(List<FrbBook> self, SseSerializer serializer);

  @protected
  void sse_encode_list_frb_book_note(
    List<FrbBookNote> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_catalog_entry(
    List<FrbCatalogEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_collection(
    List<FrbCollection> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_collection_book(
    List<FrbCollectionBook> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_contact(
    List<FrbContact> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_cover_candidate(
    List<FrbCoverCandidate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_discovered_peer(
    List<FrbDiscoveredPeer> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_hangman_char(
    List<FrbHangmanChar> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_hangman_leaderboard_entry(
    List<FrbHangmanLeaderboardEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_hangman_score(
    List<FrbHangmanScore> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_hub_borrow_request(
    List<FrbHubBorrowRequest> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_hub_follow(
    List<FrbHubFollow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_hub_profile(
    List<FrbHubProfile> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_leaderboard_entry(
    List<FrbLeaderboardEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_linked_device(
    List<FrbLinkedDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_loan(List<FrbLoan> self, SseSerializer serializer);

  @protected
  void sse_encode_list_frb_memory_card(
    List<FrbMemoryCard> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_memory_leaderboard_entry(
    List<FrbMemoryLeaderboardEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_memory_score(
    List<FrbMemoryScore> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_notification(
    List<FrbNotification> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_operation_log_entry(
    List<FrbOperationLogEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_pending_review_op(
    List<FrbPendingReviewOp> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_puzzle_leaderboard_entry(
    List<FrbPuzzleLeaderboardEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_puzzle_score(
    List<FrbPuzzleScore> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_frb_tag(List<FrbTag> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_i_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_frb_book_metadata(
    FrbBookMetadata? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_frb_collection(
    FrbCollection? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_frb_directory_config(
    FrbDirectoryConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_frb_relay_config(
    FrbRelayConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
