/// Shared map of language codes to their native display names.
/// Used by settings_screen.dart and external_search_screen.dart.
const Map<String, String> kLanguageNativeNames = {
  'fr': 'Français',
  'en': 'English',
  'es': 'Español',
  'de': 'Deutsch',
  'it': 'Italiano',
  'pt': 'Português',
  'nl': 'Nederlands',
  'ru': 'Русский',
  'ja': '日本語',
  'zh': '中文',
  'ar': 'العربية',
  'ko': '한국어',
  'pl': 'Polski',
  'sv': 'Svenska',
  'da': 'Dansk',
  'nb': 'Norsk',
  'fi': 'Suomi',
  'cs': 'Čeština',
  'el': 'Ελληνικά',
  'tr': 'Türkçe',
  'he': 'עברית',
  'la': 'Latina',
  'ro': 'Română',
  'hu': 'Magyar',
  'ca': 'Català',
  'uk': 'Українська',
};
