// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'frb.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `db`, `device_pairing_svc`, `device_sync_svc`, `entries_to_frb`, `hub_db`, `hub_directory_svc`, `install_panic_hook`, `load_google_books_api_key`, `runtime`, `track_to_frb`, `upsert_directory_catalog_cache`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Initialize the FFI backend with database at the given path
/// Must be called before any other FFI functions
Future<String> initBackend({required String dbPath}) =>
    RustLib.instance.api.crateApiFrbInitBackend(dbPath: dbPath);

/// Pass the hub URL from Flutter to the Rust process environment.
/// Must be called once after init_backend, before any hub_directory calls.
/// Rust reads HUB_URL via std::env::var — it cannot see Flutter's dotenv map.
Future<void> setHubUrlFfi({required String hubUrl}) =>
    RustLib.instance.api.crateApiFrbSetHubUrlFfi(hubUrl: hubUrl);

/// Check if the FFI backend is healthy
String healthCheck() => RustLib.instance.api.crateApiFrbHealthCheck();

/// Get the FFI backend version
String getVersion() => RustLib.instance.api.crateApiFrbGetVersion();

/// Simple greeting function to test the bridge
String greet({required String name}) =>
    RustLib.instance.api.crateApiFrbGreet(name: name);

/// Check if mDNS discovery service is currently active
/// This is a sync function that can be called to check status
bool isMdnsAvailable() => RustLib.instance.api.crateApiFrbIsMdnsAvailable();

/// Get the mDNS service type used for discovery
String getMdnsServiceType() =>
    RustLib.instance.api.crateApiFrbGetMdnsServiceType();

/// Get locally discovered peers via mDNS
/// This returns peers that have been found on the local network
Future<List<FrbDiscoveredPeer>> getLocalPeersFfi() =>
    RustLib.instance.api.crateApiFrbGetLocalPeersFfi();

/// Initialize mDNS service for discovery
/// Must be called to start announcing and discovering peers
Future<String> initMdnsFfi({
  required String libraryName,
  required int port,
  String? libraryId,
  String? ed25519PublicKey,
  String? x25519PublicKey,
}) => RustLib.instance.api.crateApiFrbInitMdnsFfi(
  libraryName: libraryName,
  port: port,
  libraryId: libraryId,
  ed25519PublicKey: ed25519PublicKey,
  x25519PublicKey: x25519PublicKey,
);

/// Stop mDNS service
Future<String> stopMdnsFfi() => RustLib.instance.api.crateApiFrbStopMdnsFfi();

/// Initialize the node's cryptographic identity.
/// Must be called after init_backend and after obtaining the library UUID.
/// Uses Argon2(library_uuid) to encrypt/decrypt the stored keypair.
Future<String> initIdentityFfi({required String libraryUuid}) =>
    RustLib.instance.api.crateApiFrbInitIdentityFfi(libraryUuid: libraryUuid);

/// Get the node's public keys as JSON: {"ed25519": "hex...", "x25519": "hex..."}
Future<String> getPublicKeysFfi() =>
    RustLib.instance.api.crateApiFrbGetPublicKeysFfi();

/// Generate a QR v2 payload as JSON string.
/// Includes library name, URL, UUID, and public keys.
Future<String> generateQrPayloadFfi({
  required String libraryName,
  required String url,
  required String libraryUuid,
}) => RustLib.instance.api.crateApiFrbGenerateQrPayloadFfi(
  libraryName: libraryName,
  url: url,
  libraryUuid: libraryUuid,
);

/// Parse a QR payload (supports both v1 and v2 formats).
/// Returns a normalized JSON string with all available fields.
Future<String> parseQrPayloadFfi({required String payload}) =>
    RustLib.instance.api.crateApiFrbParseQrPayloadFfi(payload: payload);

/// Generate an invite link with the library's connection info encoded in the URL fragment.
/// Format: https://bibliogenius.org/invite#BASE64URL(json)
/// The fragment (#) is never sent to the web server (B8 compliance).
/// Payload v3 adds optional relay info for WAN connectivity.
Future<String> generateInviteLinkFfi({
  required String libraryName,
  required String url,
  required String libraryUuid,
  String? relayUrl,
  String? mailboxId,
  String? relayWriteToken,
}) => RustLib.instance.api.crateApiFrbGenerateInviteLinkFfi(
  libraryName: libraryName,
  url: url,
  libraryUuid: libraryUuid,
  relayUrl: relayUrl,
  mailboxId: mailboxId,
  relayWriteToken: relayWriteToken,
);

/// Parse an invite link, extracting the JSON payload from the URL fragment.
Future<String> parseInviteLinkFfi({required String link}) =>
    RustLib.instance.api.crateApiFrbParseInviteLinkFfi(link: link);

/// Update only the library name in the database (library_config + libraries tables).
/// This is the FFI-direct path used by the flash editor on the home screen.
/// Only touches the `name` and `updated_at` fields - no other settings are overwritten.
Future<void> updateLibraryNameFfi({required String name}) =>
    RustLib.instance.api.crateApiFrbUpdateLibraryNameFfi(name: name);

/// Create a new book
Future<FrbBook> createBook({required FrbBook book}) =>
    RustLib.instance.api.crateApiFrbCreateBook(book: book);

/// Get all books with optional filters
Future<List<FrbBook>> getAllBooks({
  String? status,
  String? title,
  String? tag,
}) => RustLib.instance.api.crateApiFrbGetAllBooks(
  status: status,
  title: title,
  tag: tag,
);

/// Get a single book by ID
Future<FrbBook> getBookById({required int id}) =>
    RustLib.instance.api.crateApiFrbGetBookById(id: id);

/// Update an existing book
Future<FrbBook> updateBook({required int id, required FrbBook book}) =>
    RustLib.instance.api.crateApiFrbUpdateBook(id: id, book: book);

/// Delete a book
Future<void> deleteBook({required int id}) =>
    RustLib.instance.api.crateApiFrbDeleteBook(id: id);

/// Count total books
Future<PlatformInt64> countBooks() =>
    RustLib.instance.api.crateApiFrbCountBooks();

/// Enrich books that have an ISBN but no cover by checking external sources.
/// Runs in background, returns the count of covers found and persisted.
Future<int> enrichMissingCovers() =>
    RustLib.instance.api.crateApiFrbEnrichMissingCovers();

/// Search for a cover URL for a single ISBN from external sources.
Future<String?> searchCoverForBook({required String isbn}) =>
    RustLib.instance.api.crateApiFrbSearchCoverForBook(isbn: isbn);

/// Search for a cover URL by title with author verification.
/// Used as a fallback when ISBN-based search returns nothing.
/// Returns a cover only if the result author matches the given author.
Future<String?> searchCoverByTitle({
  required String title,
  String? author,
  bool? enableGoogle,
}) => RustLib.instance.api.crateApiFrbSearchCoverByTitle(
  title: title,
  author: author,
  enableGoogle: enableGoogle,
);

/// Search ALL enabled cover sources in parallel for a given ISBN.
/// Returns all found cover candidates for the picker carousel.
Future<List<FrbCoverCandidate>> searchAllCoversForBook({
  required String isbn,
}) => RustLib.instance.api.crateApiFrbSearchAllCoversForBook(isbn: isbn);

/// Search ALL enabled sources by title in parallel for the cover picker.
Future<List<FrbCoverCandidate>> searchAllCoversByTitle({
  required String title,
  String? author,
  bool? enableGoogle,
}) => RustLib.instance.api.crateApiFrbSearchAllCoversByTitle(
  title: title,
  author: author,
  enableGoogle: enableGoogle,
);

/// Look up book metadata by ISBN from external sources (BNF, Inventaire, OpenLibrary, etc.).
/// Used by the metadata refresh feature to let users preview and cherry-pick fields.
Future<FrbBookMetadata?> lookupBookMetadata({
  required String isbn,
  String? lang,
}) =>
    RustLib.instance.api.crateApiFrbLookupBookMetadata(isbn: isbn, lang: lang);

/// Get all tags with hierarchy info
Future<List<FrbTag>> getAllTags() =>
    RustLib.instance.api.crateApiFrbGetAllTags();

/// Create a new tag
Future<FrbTag> createTag({required String name, int? parentId}) =>
    RustLib.instance.api.crateApiFrbCreateTag(name: name, parentId: parentId);

/// Update a tag
Future<FrbTag> updateTag({
  required int id,
  required String name,
  int? parentId,
}) => RustLib.instance.api.crateApiFrbUpdateTag(
  id: id,
  name: name,
  parentId: parentId,
);

/// Delete a tag
Future<void> deleteTag({required int id}) =>
    RustLib.instance.api.crateApiFrbDeleteTag(id: id);

/// Reorder books by updating shelf positions
Future<void> reorderBooks({required List<int> bookIds}) =>
    RustLib.instance.api.crateApiFrbReorderBooks(bookIds: bookIds);

/// Get all contacts with optional filters
Future<List<FrbContact>> getAllContacts({
  int? libraryId,
  String? contactType,
}) => RustLib.instance.api.crateApiFrbGetAllContacts(
  libraryId: libraryId,
  contactType: contactType,
);

/// Get a single contact by ID
Future<FrbContact> getContactById({required int id}) =>
    RustLib.instance.api.crateApiFrbGetContactById(id: id);

/// Count total contacts
Future<PlatformInt64> countContacts() =>
    RustLib.instance.api.crateApiFrbCountContacts();

/// Create a new contact
Future<FrbContact> createContact({required FrbContact contact}) =>
    RustLib.instance.api.crateApiFrbCreateContact(contact: contact);

/// Update an existing contact
Future<FrbContact> updateContact({required FrbContact contact}) =>
    RustLib.instance.api.crateApiFrbUpdateContact(contact: contact);

/// Delete a contact by ID (soft delete)
Future<void> deleteContact({required int id}) =>
    RustLib.instance.api.crateApiFrbDeleteContact(id: id);

/// Get all loans with optional filters
Future<List<FrbLoan>> getAllLoans({
  int? libraryId,
  String? status,
  int? contactId,
}) => RustLib.instance.api.crateApiFrbGetAllLoans(
  libraryId: libraryId,
  status: status,
  contactId: contactId,
);

/// Count active loans
Future<PlatformInt64> countActiveLoans() =>
    RustLib.instance.api.crateApiFrbCountActiveLoans();

/// Create a new loan
Future<int> createLoan({
  required int copyId,
  required int contactId,
  required int libraryId,
  required String loanDate,
  required String dueDate,
  String? notes,
}) => RustLib.instance.api.crateApiFrbCreateLoan(
  copyId: copyId,
  contactId: contactId,
  libraryId: libraryId,
  loanDate: loanDate,
  dueDate: dueDate,
  notes: notes,
);

/// Count returned loans (for cleanup confirmation dialog)
Future<PlatformInt64> countReturnedLoans() =>
    RustLib.instance.api.crateApiFrbCountReturnedLoans();

/// Delete all returned loans, returns the number of deleted rows
Future<BigInt> deleteReturnedLoans() =>
    RustLib.instance.api.crateApiFrbDeleteReturnedLoans();

/// Count closed incoming P2P requests (not pending)
Future<PlatformInt64> countClosedIncomingRequests() =>
    RustLib.instance.api.crateApiFrbCountClosedIncomingRequests();

/// Delete all closed incoming P2P requests (not pending)
Future<BigInt> deleteClosedIncomingRequests() =>
    RustLib.instance.api.crateApiFrbDeleteClosedIncomingRequests();

/// Count closed outgoing P2P requests (not pending)
Future<PlatformInt64> countClosedOutgoingRequests() =>
    RustLib.instance.api.crateApiFrbCountClosedOutgoingRequests();

/// Delete all closed outgoing P2P requests (not pending)
Future<BigInt> deleteClosedOutgoingRequests() =>
    RustLib.instance.api.crateApiFrbDeleteClosedOutgoingRequests();

/// Return a loan
Future<String> returnLoan({required int id}) =>
    RustLib.instance.api.crateApiFrbReturnLoan(id: id);

/// Reset the entire application - deletes all data from all tables
/// This is irreversible and should be used with caution
Future<String> resetApp() => RustLib.instance.api.crateApiFrbResetApp();

/// Start the HTTP server on the specified port (FFI)
/// This is required for P2P functionality in standalone mode
/// If the specified port is occupied, tries the next 10 ports automatically
Future<int> startServer({required int port}) =>
    RustLib.instance.api.crateApiFrbStartServer(port: port);

/// Get available difficulty levels based on books with covers
Future<List<String>> memoryGameAvailableDifficulties() =>
    RustLib.instance.api.crateApiFrbMemoryGameAvailableDifficulties();

/// Set up a new memory game with the given difficulty
Future<List<FrbMemoryCard>> memoryGameSetup({required String difficulty}) =>
    RustLib.instance.api.crateApiFrbMemoryGameSetup(difficulty: difficulty);

/// Submit a completed game and get the score back
Future<FrbMemoryScore> memoryGameFinish({
  required String difficulty,
  required double elapsedSeconds,
  required int errors,
  required int pairsCount,
}) => RustLib.instance.api.crateApiFrbMemoryGameFinish(
  difficulty: difficulty,
  elapsedSeconds: elapsedSeconds,
  errors: errors,
  pairsCount: pairsCount,
);

/// Get top memory game scores
Future<List<FrbMemoryScore>> memoryGameTopScores() =>
    RustLib.instance.api.crateApiFrbMemoryGameTopScores();

/// Get leaderboard (peer scores + local user's best)
Future<List<FrbMemoryLeaderboardEntry>> memoryGameLeaderboard() =>
    RustLib.instance.api.crateApiFrbMemoryGameLeaderboard();

/// Refresh the network memory game leaderboard by syncing with all accepted peers.
/// Fetches each peer's /api/game/memory/public-best, upserts into peer_memory_scores,
/// then returns the merged leaderboard.
Future<List<FrbMemoryLeaderboardEntry>> memoryGameRefreshLeaderboard() =>
    RustLib.instance.api.crateApiFrbMemoryGameRefreshLeaderboard();

/// Get available puzzle difficulty levels based on books with covers
Future<List<String>> puzzleAvailableDifficulties() =>
    RustLib.instance.api.crateApiFrbPuzzleAvailableDifficulties();

/// Set up a new sliding puzzle with the given difficulty
Future<FrbPuzzleBoard> puzzleSetup({required String difficulty}) =>
    RustLib.instance.api.crateApiFrbPuzzleSetup(difficulty: difficulty);

/// Submit a completed sliding puzzle and get the score back
Future<FrbPuzzleScore> puzzleFinish({
  required String difficulty,
  required int gridSize,
  required double elapsedSeconds,
  required int moveCount,
  required int parMoves,
}) => RustLib.instance.api.crateApiFrbPuzzleFinish(
  difficulty: difficulty,
  gridSize: gridSize,
  elapsedSeconds: elapsedSeconds,
  moveCount: moveCount,
  parMoves: parMoves,
);

/// Get top sliding puzzle scores
Future<List<FrbPuzzleScore>> puzzleTopScores() =>
    RustLib.instance.api.crateApiFrbPuzzleTopScores();

/// Get puzzle leaderboard (peer scores + local user's best)
Future<List<FrbPuzzleLeaderboardEntry>> puzzleGameLeaderboard() =>
    RustLib.instance.api.crateApiFrbPuzzleGameLeaderboard();

/// Refresh the network puzzle leaderboard by syncing with all accepted peers.
/// Fetches each peer's /api/game/puzzle/public-best, upserts into peer_puzzle_scores,
/// then returns the merged leaderboard.
Future<List<FrbPuzzleLeaderboardEntry>> puzzleGameRefreshLeaderboard() =>
    RustLib.instance.api.crateApiFrbPuzzleGameRefreshLeaderboard();

/// Get full gamification status via FFI (replaces HTTP getUserStatus)
Future<FrbGamificationStatus> gamificationGetStatus() =>
    RustLib.instance.api.crateApiFrbGamificationGetStatus();

/// Get leaderboard via FFI (replaces HTTP getLeaderboard)
Future<FrbLeaderboardResponse> gamificationGetLeaderboard() =>
    RustLib.instance.api.crateApiFrbGamificationGetLeaderboard();

/// Refresh leaderboard (returns current state) via FFI.
/// Peer sync happens via the HTTP endpoint — this just returns current data.
Future<FrbLeaderboardResponse> gamificationRefreshLeaderboard() =>
    RustLib.instance.api.crateApiFrbGamificationRefreshLeaderboard();

/// Update gamification config via FFI
Future<void> gamificationUpdateConfig({
  int? readingGoalYearly,
  String? achievementsStyle,
}) => RustLib.instance.api.crateApiFrbGamificationUpdateConfig(
  readingGoalYearly: readingGoalYearly,
  achievementsStyle: achievementsStyle,
);

/// Check and unlock eligible achievements via FFI
Future<List<String>> gamificationCheckAchievements() =>
    RustLib.instance.api.crateApiFrbGamificationCheckAchievements();

/// Update daily streak via FFI
Future<FrbStreakInfo> gamificationUpdateStreak() =>
    RustLib.instance.api.crateApiFrbGamificationUpdateStreak();

/// List operation log entries with optional filters
Future<List<FrbOperationLogEntry>> operationLogList({
  String? entityType,
  String? operation,
  String? status,
  String? query,
  BigInt? page,
  BigInt? limit,
}) => RustLib.instance.api.crateApiFrbOperationLogList(
  entityType: entityType,
  operation: operation,
  status: status,
  query: query,
  page: page,
  limit: limit,
);

/// Get operation log stats
Future<FrbOperationLogStats> operationLogStats() =>
    RustLib.instance.api.crateApiFrbOperationLogStats();

/// Get distinct entity types for filter dropdowns
Future<List<String>> operationLogEntityTypes() =>
    RustLib.instance.api.crateApiFrbOperationLogEntityTypes();

/// Generate a 6-digit pairing offer for multi-device linking
Future<FrbPairingOffer> deviceGeneratePairingOffer({
  required String deviceName,
  required String libraryUuid,
  String? relayUrl,
  String? mailboxId,
  String? relayWriteToken,
}) => RustLib.instance.api.crateApiFrbDeviceGeneratePairingOffer(
  deviceName: deviceName,
  libraryUuid: libraryUuid,
  relayUrl: relayUrl,
  mailboxId: mailboxId,
  relayWriteToken: relayWriteToken,
);

/// Accept a pairing offer by entering the 6-digit code.
/// Returns the offerer's crypto keys and library info.
Future<FrbPairingConfirmation> deviceAcceptPairing({
  required String code,
  required String deviceName,
  required List<int> ed25519PublicKey,
  required List<int> x25519PublicKey,
  String? relayUrl,
  String? mailboxId,
  String? relayWriteToken,
}) => RustLib.instance.api.crateApiFrbDeviceAcceptPairing(
  code: code,
  deviceName: deviceName,
  ed25519PublicKey: ed25519PublicKey,
  x25519PublicKey: x25519PublicKey,
  relayUrl: relayUrl,
  mailboxId: mailboxId,
  relayWriteToken: relayWriteToken,
);

/// List all linked devices
Future<List<FrbLinkedDevice>> deviceListLinked() =>
    RustLib.instance.api.crateApiFrbDeviceListLinked();

/// Remove a linked device by ID
Future<void> deviceRemoveLinked({required int deviceId}) =>
    RustLib.instance.api.crateApiFrbDeviceRemoveLinked(deviceId: deviceId);

/// Trigger sync with a specific linked device.
/// This is a simplified version - full sync uses the HTTP trigger_sync endpoint
/// which handles E2EE transport. This FFI function delegates to it.
Future<FrbSyncResult> deviceTriggerSync({required int deviceId}) =>
    RustLib.instance.api.crateApiFrbDeviceTriggerSync(deviceId: deviceId);

/// List operations pending review (sync safety mode)
Future<List<FrbPendingReviewOp>> deviceSyncPendingReview() =>
    RustLib.instance.api.crateApiFrbDeviceSyncPendingReview();

/// Approve specific pending review operations
Future<int> deviceSyncApprove({required List<int> ids}) =>
    RustLib.instance.api.crateApiFrbDeviceSyncApprove(ids: ids);

/// Reject specific pending review operations
Future<int> deviceSyncReject({required List<int> ids}) =>
    RustLib.instance.api.crateApiFrbDeviceSyncReject(ids: ids);

/// Approve all pending review operations at once
Future<int> deviceSyncApproveAll() =>
    RustLib.instance.api.crateApiFrbDeviceSyncApproveAll();

/// Reject all pending review operations at once
Future<int> deviceSyncRejectAll() =>
    RustLib.instance.api.crateApiFrbDeviceSyncRejectAll();

/// Returns the local hub directory settings, or None if not yet registered.
Future<FrbDirectoryConfig?> hubDirectoryGetConfig() =>
    RustLib.instance.api.crateApiFrbHubDirectoryGetConfig();

/// Registers with the hub directory (first call) or updates the profile.
/// On first registration, the write_token is persisted automatically.
Future<FrbDirectoryConfig> hubDirectoryRegister({
  required FrbRegisterParams params,
}) => RustLib.instance.api.crateApiFrbHubDirectoryRegister(params: params);

/// Pushes the local ISBN list to the hub catalog cache (legacy, ISBN-only).
Future<void> hubDirectoryPushCatalog({required List<String> isbnList}) =>
    RustLib.instance.api.crateApiFrbHubDirectoryPushCatalog(isbnList: isbnList);

/// Reads all books with ISBNs from the local database, collects title and
/// first author, and pushes the enriched catalog to the hub.
/// Returns the number of entries pushed.
Future<int> hubDirectorySyncCatalog() =>
    RustLib.instance.api.crateApiFrbHubDirectorySyncCatalog();

/// Browses the hub public directory.
Future<List<FrbHubProfile>> hubDirectoryList({
  required PlatformInt64 limit,
  required PlatformInt64 offset,
  String? country,
  String? search,
}) => RustLib.instance.api.crateApiFrbHubDirectoryList(
  limit: limit,
  offset: offset,
  country: country,
  search: search,
);

/// Gets a specific library profile from the hub directory.
Future<FrbHubProfile> hubDirectoryGetProfile({required String nodeId}) =>
    RustLib.instance.api.crateApiFrbHubDirectoryGetProfile(nodeId: nodeId);

/// Gets the catalog of a library (public or approved follow).
/// Fetches from hub, upserts into local cache, and returns entries with first_seen_at.
/// If the hub fetch fails, returns the cached entries (offline-first).
Future<List<FrbCatalogEntry>> hubDirectoryGetCatalog({
  required String nodeId,
}) => RustLib.instance.api.crateApiFrbHubDirectoryGetCatalog(nodeId: nodeId);

/// Sends a follow request to a library.
Future<FrbHubFollow> hubDirectoryFollow({required String nodeId}) =>
    RustLib.instance.api.crateApiFrbHubDirectoryFollow(nodeId: nodeId);

/// Lists incoming follow requests pending approval.
Future<List<FrbHubFollow>> hubDirectoryPendingRequests() =>
    RustLib.instance.api.crateApiFrbHubDirectoryPendingRequests();

/// Resolves a pending follow request. resolution: "approve" | "reject" | "block"
/// When approving, encrypted_contact is an optional sealed blob of the owner's contact info.
Future<FrbHubFollow> hubDirectoryResolveFollow({
  required PlatformInt64 followId,
  required String resolution,
  String? encryptedContact,
}) => RustLib.instance.api.crateApiFrbHubDirectoryResolveFollow(
  followId: followId,
  resolution: resolution,
  encryptedContact: encryptedContact,
);

/// Lists libraries the local library is following (active follows).
Future<List<FrbHubFollow>> hubDirectoryListFollowing() =>
    RustLib.instance.api.crateApiFrbHubDirectoryListFollowing();

/// Lists libraries that follow the local library (active followers).
Future<List<FrbHubFollow>> hubDirectoryListFollowers() =>
    RustLib.instance.api.crateApiFrbHubDirectoryListFollowers();

/// Unfollows a library.
Future<void> hubDirectoryUnfollow({required String nodeId}) =>
    RustLib.instance.api.crateApiFrbHubDirectoryUnfollow(nodeId: nodeId);

/// Creates a hub-mediated borrow request for a book from a followed library.
Future<FrbHubBorrowRequest> hubDirectoryCreateBorrowRequest({
  required String lenderNodeId,
  required String isbn,
  required String bookTitle,
}) => RustLib.instance.api.crateApiFrbHubDirectoryCreateBorrowRequest(
  lenderNodeId: lenderNodeId,
  isbn: isbn,
  bookTitle: bookTitle,
);

/// Fetches incoming borrow requests (pending) for the local library as lender.
Future<List<FrbHubBorrowRequest>> hubDirectoryIncomingBorrowRequests() =>
    RustLib.instance.api.crateApiFrbHubDirectoryIncomingBorrowRequests();

/// Fetches outgoing borrow requests sent by the local library as requester.
Future<List<FrbHubBorrowRequest>> hubDirectoryOutgoingBorrowRequests() =>
    RustLib.instance.api.crateApiFrbHubDirectoryOutgoingBorrowRequests();

/// Resolves a borrow request. resolution: "accept" | "reject"
Future<FrbHubBorrowRequest> hubDirectoryResolveBorrowRequest({
  required PlatformInt64 requestId,
  required String resolution,
}) => RustLib.instance.api.crateApiFrbHubDirectoryResolveBorrowRequest(
  requestId: requestId,
  resolution: resolution,
);

/// Cancels a borrow request (requester only).
Future<void> hubDirectoryCancelBorrowRequest({
  required PlatformInt64 requestId,
}) => RustLib.instance.api.crateApiFrbHubDirectoryCancelBorrowRequest(
  requestId: requestId,
);

/// Encrypts plaintext for a recipient identified by their X25519 public key (hex-encoded).
/// Returns a base64-encoded sealed blob suitable for hub storage.
Future<String> sealBlob({
  required String recipientX25519Hex,
  required String plaintext,
}) => RustLib.instance.api.crateApiFrbSealBlob(
  recipientX25519Hex: recipientX25519Hex,
  plaintext: plaintext,
);

/// Decrypts a base64-encoded sealed blob using the local node identity's X25519 secret key.
/// Returns the plaintext string.
Future<String> openBlob({required String sealedBase64}) =>
    RustLib.instance.api.crateApiFrbOpenBlob(sealedBase64: sealedBase64);

/// Batch-updates encrypted contact blobs for all active followers.
/// contacts: list of (follow_id, encrypted_contact_base64) pairs.
Future<int> hubDirectorySyncContacts({
  required Int64List followIds,
  required List<String> encryptedContacts,
}) => RustLib.instance.api.crateApiFrbHubDirectorySyncContacts(
  followIds: followIds,
  encryptedContacts: encryptedContacts,
);

/// Returns the local X25519 public key as hex string, or None if no identity exists.
Future<String?> getLocalX25519PublicKey() =>
    RustLib.instance.api.crateApiFrbGetLocalX25519PublicKey();

/// Returns all collections with their book counts.
Future<List<FrbCollection>> getAllCollections() =>
    RustLib.instance.api.crateApiFrbGetAllCollections();

/// Returns a single collection by ID, or None if not found.
Future<FrbCollection?> getCollection({required String id}) =>
    RustLib.instance.api.crateApiFrbGetCollection(id: id);

/// Creates a new collection. Returns the created collection.
Future<FrbCollection> createCollection({
  required String name,
  String? description,
}) => RustLib.instance.api.crateApiFrbCreateCollection(
  name: name,
  description: description,
);

/// Deletes a collection by ID.
Future<void> deleteCollection({required String id}) =>
    RustLib.instance.api.crateApiFrbDeleteCollection(id: id);

/// Returns all books belonging to a collection.
Future<List<FrbCollectionBook>> getCollectionBooks({
  required String collectionId,
}) => RustLib.instance.api.crateApiFrbGetCollectionBooks(
  collectionId: collectionId,
);

/// Adds a book to a collection (idempotent).
Future<void> addBookToCollection({
  required String collectionId,
  required int bookId,
}) => RustLib.instance.api.crateApiFrbAddBookToCollection(
  collectionId: collectionId,
  bookId: bookId,
);

/// Removes a book from a collection.
Future<void> removeBookFromCollection({
  required String collectionId,
  required int bookId,
}) => RustLib.instance.api.crateApiFrbRemoveBookFromCollection(
  collectionId: collectionId,
  bookId: bookId,
);

/// Get library view statistics (peer and follower views).
/// Returns a JSON string with total_peer, total_follower, total, and daily breakdown.
Future<String> getLibraryViewStats() =>
    RustLib.instance.api.crateApiFrbGetLibraryViewStats();

/// Returns all collections a book belongs to.
Future<List<FrbCollection>> getBookCollections({required int bookId}) =>
    RustLib.instance.api.crateApiFrbGetBookCollections(bookId: bookId);

/// Replaces the set of collections a book belongs to.
Future<void> updateBookCollections({
  required int bookId,
  required List<String> collectionIds,
}) => RustLib.instance.api.crateApiFrbUpdateBookCollections(
  bookId: bookId,
  collectionIds: collectionIds,
);

/// List notifications, optionally filtered by category.
Future<List<FrbNotification>> notificationsList({
  String? category,
  required BigInt offset,
  required BigInt limit,
}) => RustLib.instance.api.crateApiFrbNotificationsList(
  category: category,
  offset: offset,
  limit: limit,
);

/// Get unread notification count (optionally by category).
Future<int> notificationsUnreadCount({String? category}) => RustLib.instance.api
    .crateApiFrbNotificationsUnreadCount(category: category);

/// Mark a single notification as read.
Future<bool> notificationsMarkRead({required int id}) =>
    RustLib.instance.api.crateApiFrbNotificationsMarkRead(id: id);

/// Mark all notifications as read.
Future<int> notificationsMarkAllRead() =>
    RustLib.instance.api.crateApiFrbNotificationsMarkAllRead();

/// Dismiss (hard delete) a single notification.
Future<bool> notificationsDismiss({required int id}) =>
    RustLib.instance.api.crateApiFrbNotificationsDismiss(id: id);

/// Dismiss (hard delete) all notifications. Returns count of deleted rows.
Future<int> notificationsDismissAll() =>
    RustLib.instance.api.crateApiFrbNotificationsDismissAll();

/// Run pruning (TTL + cap). Call on app startup.
Future<int> notificationsPrune() =>
    RustLib.instance.api.crateApiFrbNotificationsPrune();

/// Simplified book structure for FFI
@freezed
sealed class FrbBook with _$FrbBook {
  const factory FrbBook({
    int? id,
    required String title,
    String? author,
    String? isbn,
    String? summary,
    String? publisher,
    int? publicationYear,
    String? coverUrl,
    String? largeCoverUrl,
    String? readingStatus,
    int? shelfPosition,
    int? userRating,
    String? subjects,
    String? createdAt,
    String? updatedAt,
    String? finishedReadingAt,
    String? startedReadingAt,
    required bool owned,
    double? price,
    List<String>? digitalFormats,
  }) = _FrbBook;
}

/// Metadata fetched from external sources for a book refresh.
/// Each field is optional — only non-null fields have data from the source.
@freezed
sealed class FrbBookMetadata with _$FrbBookMetadata {
  const factory FrbBookMetadata({
    String? title,
    String? author,
    String? publisher,
    String? publicationYear,
    String? coverUrl,
    String? summary,
  }) = _FrbBookMetadata;
}

@freezed
sealed class FrbCatalogEntry with _$FrbCatalogEntry {
  const factory FrbCatalogEntry({
    required String isbn,
    required String title,
    String? author,
    String? coverUrl,
    String? firstSeenAt,
  }) = _FrbCatalogEntry;
}

/// Collection data exposed to Flutter.
class FrbCollection {
  final String id;
  final String name;
  final String? description;
  final String source;
  final PlatformInt64 totalBooks;
  final PlatformInt64 ownedBooks;
  final String createdAt;
  final String updatedAt;

  const FrbCollection({
    required this.id,
    required this.name,
    this.description,
    required this.source,
    required this.totalBooks,
    required this.ownedBooks,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      source.hashCode ^
      totalBooks.hashCode ^
      ownedBooks.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbCollection &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          source == other.source &&
          totalBooks == other.totalBooks &&
          ownedBooks == other.ownedBooks &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// A book entry within a collection, exposed to Flutter.
class FrbCollectionBook {
  final int bookId;
  final String title;
  final String? author;
  final String? coverUrl;
  final String? publisher;
  final int? publicationYear;
  final String addedAt;
  final bool isOwned;
  final List<String>? digitalFormats;

  const FrbCollectionBook({
    required this.bookId,
    required this.title,
    this.author,
    this.coverUrl,
    this.publisher,
    this.publicationYear,
    required this.addedAt,
    required this.isOwned,
    this.digitalFormats,
  });

  @override
  int get hashCode =>
      bookId.hashCode ^
      title.hashCode ^
      author.hashCode ^
      coverUrl.hashCode ^
      publisher.hashCode ^
      publicationYear.hashCode ^
      addedAt.hashCode ^
      isOwned.hashCode ^
      digitalFormats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbCollectionBook &&
          runtimeType == other.runtimeType &&
          bookId == other.bookId &&
          title == other.title &&
          author == other.author &&
          coverUrl == other.coverUrl &&
          publisher == other.publisher &&
          publicationYear == other.publicationYear &&
          addedAt == other.addedAt &&
          isOwned == other.isOwned &&
          digitalFormats == other.digitalFormats;
}

/// Simplified contact structure for FFI
@freezed
sealed class FrbContact with _$FrbContact {
  const factory FrbContact({
    int? id,
    required String contactType,
    required String name,
    String? firstName,
    String? email,
    String? phone,
    String? address,
    String? streetAddress,
    String? postalCode,
    String? city,
    String? country,
    double? latitude,
    double? longitude,
    String? notes,
    int? userId,
    int? libraryOwnerId,
    required bool isActive,
  }) = _FrbContact;
}

/// A cover candidate from an external source, for the multi-cover picker.
@freezed
sealed class FrbCoverCandidate with _$FrbCoverCandidate {
  const factory FrbCoverCandidate({
    required String url,
    required String source,
  }) = _FrbCoverCandidate;
}

@freezed
sealed class FrbDirectoryConfig with _$FrbDirectoryConfig {
  const factory FrbDirectoryConfig({
    required String nodeId,
    required bool isListed,
    required bool requiresApproval,
    required String acceptFrom,
    required bool allowBorrowing,
  }) = _FrbDirectoryConfig;
}

/// Discovered peer on local network (FFI-compatible)
@freezed
sealed class FrbDiscoveredPeer with _$FrbDiscoveredPeer {
  const factory FrbDiscoveredPeer({
    required String name,
    required String host,
    required int port,
    required List<String> addresses,
    String? libraryId,
    String? ed25519PublicKey,
    String? x25519PublicKey,
    required String discoveredAt,
  }) = _FrbDiscoveredPeer;
}

/// Gamification config (FFI-safe)
class FrbGamificationConfig {
  final String achievementsStyle;
  final int readingGoalYearly;
  final int readingGoalProgress;
  final int totalBooksRead;

  const FrbGamificationConfig({
    required this.achievementsStyle,
    required this.readingGoalYearly,
    required this.readingGoalProgress,
    required this.totalBooksRead,
  });

  @override
  int get hashCode =>
      achievementsStyle.hashCode ^
      readingGoalYearly.hashCode ^
      readingGoalProgress.hashCode ^
      totalBooksRead.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbGamificationConfig &&
          runtimeType == other.runtimeType &&
          achievementsStyle == other.achievementsStyle &&
          readingGoalYearly == other.readingGoalYearly &&
          readingGoalProgress == other.readingGoalProgress &&
          totalBooksRead == other.totalBooksRead;
}

/// Full gamification status (FFI-safe)
class FrbGamificationStatus {
  final FrbTrackProgress collector;
  final FrbTrackProgress reader;
  final FrbTrackProgress lender;
  final FrbTrackProgress cataloguer;
  final FrbStreakInfo streak;
  final List<String> recentAchievements;
  final FrbGamificationConfig config;
  final String level;
  final PlatformInt64 loansCount;
  final PlatformInt64 editsCount;
  final double nextLevelProgress;
  final String badgeUrl;

  const FrbGamificationStatus({
    required this.collector,
    required this.reader,
    required this.lender,
    required this.cataloguer,
    required this.streak,
    required this.recentAchievements,
    required this.config,
    required this.level,
    required this.loansCount,
    required this.editsCount,
    required this.nextLevelProgress,
    required this.badgeUrl,
  });

  @override
  int get hashCode =>
      collector.hashCode ^
      reader.hashCode ^
      lender.hashCode ^
      cataloguer.hashCode ^
      streak.hashCode ^
      recentAchievements.hashCode ^
      config.hashCode ^
      level.hashCode ^
      loansCount.hashCode ^
      editsCount.hashCode ^
      nextLevelProgress.hashCode ^
      badgeUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbGamificationStatus &&
          runtimeType == other.runtimeType &&
          collector == other.collector &&
          reader == other.reader &&
          lender == other.lender &&
          cataloguer == other.cataloguer &&
          streak == other.streak &&
          recentAchievements == other.recentAchievements &&
          config == other.config &&
          level == other.level &&
          loansCount == other.loansCount &&
          editsCount == other.editsCount &&
          nextLevelProgress == other.nextLevelProgress &&
          badgeUrl == other.badgeUrl;
}

@freezed
sealed class FrbHubBorrowRequest with _$FrbHubBorrowRequest {
  const factory FrbHubBorrowRequest({
    required PlatformInt64 id,
    required String requesterNodeId,
    required String lenderNodeId,
    required String isbn,
    required String bookTitle,
    required String status,
    required String createdAt,
    String? resolvedAt,
    String? requesterDisplayName,
    String? lenderDisplayName,
  }) = _FrbHubBorrowRequest;
}

@freezed
sealed class FrbHubFollow with _$FrbHubFollow {
  const factory FrbHubFollow({
    required PlatformInt64 id,
    required String followerNodeId,
    required String followedNodeId,
    required String status,
    required String createdAt,
    String? resolvedAt,
    String? followerDisplayName,
    String? encryptedContact,
    String? followerX25519PublicKey,
  }) = _FrbHubFollow;
}

@freezed
sealed class FrbHubProfile with _$FrbHubProfile {
  const factory FrbHubProfile({
    required String nodeId,
    required String displayName,
    String? description,
    required int bookCount,
    String? locationCountry,
    required bool requiresApproval,
    bool? allowBorrowing,
    String? lastSeenAt,
    String? x25519PublicKey,
    String? website,
  }) = _FrbHubProfile;
}

/// Leaderboard entry (FFI-safe)
class FrbLeaderboardEntry {
  final String libraryName;
  final int level;
  final PlatformInt64 current;
  final bool isSelf;
  final int? peerId;

  const FrbLeaderboardEntry({
    required this.libraryName,
    required this.level,
    required this.current,
    required this.isSelf,
    this.peerId,
  });

  @override
  int get hashCode =>
      libraryName.hashCode ^
      level.hashCode ^
      current.hashCode ^
      isSelf.hashCode ^
      peerId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbLeaderboardEntry &&
          runtimeType == other.runtimeType &&
          libraryName == other.libraryName &&
          level == other.level &&
          current == other.current &&
          isSelf == other.isSelf &&
          peerId == other.peerId;
}

/// Full leaderboard response (FFI-safe)
class FrbLeaderboardResponse {
  final List<FrbLeaderboardEntry> collector;
  final List<FrbLeaderboardEntry> reader;
  final List<FrbLeaderboardEntry> lender;
  final List<FrbLeaderboardEntry> cataloguer;
  final String? lastRefreshed;

  const FrbLeaderboardResponse({
    required this.collector,
    required this.reader,
    required this.lender,
    required this.cataloguer,
    this.lastRefreshed,
  });

  @override
  int get hashCode =>
      collector.hashCode ^
      reader.hashCode ^
      lender.hashCode ^
      cataloguer.hashCode ^
      lastRefreshed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbLeaderboardResponse &&
          runtimeType == other.runtimeType &&
          collector == other.collector &&
          reader == other.reader &&
          lender == other.lender &&
          cataloguer == other.cataloguer &&
          lastRefreshed == other.lastRefreshed;
}

/// FFI struct for linked device info
class FrbLinkedDevice {
  final int id;
  final String name;
  final Uint8List ed25519PublicKey;
  final Uint8List x25519PublicKey;
  final String? relayUrl;
  final String? mailboxId;
  final String? lastSynced;
  final String? createdAt;

  const FrbLinkedDevice({
    required this.id,
    required this.name,
    required this.ed25519PublicKey,
    required this.x25519PublicKey,
    this.relayUrl,
    this.mailboxId,
    this.lastSynced,
    this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      ed25519PublicKey.hashCode ^
      x25519PublicKey.hashCode ^
      relayUrl.hashCode ^
      mailboxId.hashCode ^
      lastSynced.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbLinkedDevice &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          ed25519PublicKey == other.ed25519PublicKey &&
          x25519PublicKey == other.x25519PublicKey &&
          relayUrl == other.relayUrl &&
          mailboxId == other.mailboxId &&
          lastSynced == other.lastSynced &&
          createdAt == other.createdAt;
}

/// Simplified loan structure for FFI
@freezed
sealed class FrbLoan with _$FrbLoan {
  const factory FrbLoan({
    required int id,
    required int copyId,
    required int contactId,
    required int libraryId,
    required String loanDate,
    required String dueDate,
    String? returnDate,
    required String status,
    String? notes,
    required String contactName,
    required String bookTitle,
    int? bookId,
    String? coverUrl,
    String? isbn,
  }) = _FrbLoan;
}

/// A card in the memory game (FFI-safe)
class FrbMemoryCard {
  final int bookId;
  final String title;
  final String coverUrl;

  const FrbMemoryCard({
    required this.bookId,
    required this.title,
    required this.coverUrl,
  });

  @override
  int get hashCode => bookId.hashCode ^ title.hashCode ^ coverUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbMemoryCard &&
          runtimeType == other.runtimeType &&
          bookId == other.bookId &&
          title == other.title &&
          coverUrl == other.coverUrl;
}

/// A leaderboard entry (FFI-safe)
class FrbMemoryLeaderboardEntry {
  final int peerId;
  final String libraryName;
  final double bestScore;
  final String difficulty;
  final String playedAt;

  /// True if this entry is the local user (not a peer)
  final bool isSelf;

  const FrbMemoryLeaderboardEntry({
    required this.peerId,
    required this.libraryName,
    required this.bestScore,
    required this.difficulty,
    required this.playedAt,
    required this.isSelf,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      libraryName.hashCode ^
      bestScore.hashCode ^
      difficulty.hashCode ^
      playedAt.hashCode ^
      isSelf.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbMemoryLeaderboardEntry &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          libraryName == other.libraryName &&
          bestScore == other.bestScore &&
          difficulty == other.difficulty &&
          playedAt == other.playedAt &&
          isSelf == other.isSelf;
}

/// A saved memory game score (FFI-safe)
class FrbMemoryScore {
  final int? id;
  final String difficulty;
  final int pairsCount;
  final double elapsedSeconds;
  final int errors;
  final double normalizedScore;
  final String playedAt;

  /// Achievements unlocked after this game (empty if none)
  final List<String> newAchievements;

  const FrbMemoryScore({
    this.id,
    required this.difficulty,
    required this.pairsCount,
    required this.elapsedSeconds,
    required this.errors,
    required this.normalizedScore,
    required this.playedAt,
    required this.newAchievements,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      difficulty.hashCode ^
      pairsCount.hashCode ^
      elapsedSeconds.hashCode ^
      errors.hashCode ^
      normalizedScore.hashCode ^
      playedAt.hashCode ^
      newAchievements.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbMemoryScore &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          difficulty == other.difficulty &&
          pairsCount == other.pairsCount &&
          elapsedSeconds == other.elapsedSeconds &&
          errors == other.errors &&
          normalizedScore == other.normalizedScore &&
          playedAt == other.playedAt &&
          newAchievements == other.newAchievements;
}

class FrbNotification {
  final int id;
  final String eventType;
  final String category;
  final String title;
  final String? body;
  final String? refType;
  final String? refId;
  final String? readAt;
  final String createdAt;

  const FrbNotification({
    required this.id,
    required this.eventType,
    required this.category,
    required this.title,
    this.body,
    this.refType,
    this.refId,
    this.readAt,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      eventType.hashCode ^
      category.hashCode ^
      title.hashCode ^
      body.hashCode ^
      refType.hashCode ^
      refId.hashCode ^
      readAt.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbNotification &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          eventType == other.eventType &&
          category == other.category &&
          title == other.title &&
          body == other.body &&
          refType == other.refType &&
          refId == other.refId &&
          readAt == other.readAt &&
          createdAt == other.createdAt;
}

@freezed
sealed class FrbOperationLogEntry with _$FrbOperationLogEntry {
  const factory FrbOperationLogEntry({
    required int id,
    required String entityType,
    required int entityId,
    required String operation,
    String? payload,
    required String status,
    String? errorMessage,
    required bool pinned,
    required String createdAt,
  }) = _FrbOperationLogEntry;
}

@freezed
sealed class FrbOperationLogStats with _$FrbOperationLogStats {
  const factory FrbOperationLogStats({
    required BigInt total,
    required BigInt today,
    required BigInt pending,
    required BigInt failed,
  }) = _FrbOperationLogStats;
}

/// FFI struct for pairing confirmation
class FrbPairingConfirmation {
  final int deviceId;
  final String libraryUuid;
  final Uint8List offererEd25519;
  final Uint8List offererX25519;
  final String? offererRelayUrl;
  final String? offererMailboxId;

  const FrbPairingConfirmation({
    required this.deviceId,
    required this.libraryUuid,
    required this.offererEd25519,
    required this.offererX25519,
    this.offererRelayUrl,
    this.offererMailboxId,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      libraryUuid.hashCode ^
      offererEd25519.hashCode ^
      offererX25519.hashCode ^
      offererRelayUrl.hashCode ^
      offererMailboxId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbPairingConfirmation &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          libraryUuid == other.libraryUuid &&
          offererEd25519 == other.offererEd25519 &&
          offererX25519 == other.offererX25519 &&
          offererRelayUrl == other.offererRelayUrl &&
          offererMailboxId == other.offererMailboxId;
}

/// FFI struct for pairing offer response
class FrbPairingOffer {
  final String code;
  final BigInt expiresIn;

  const FrbPairingOffer({required this.code, required this.expiresIn});

  @override
  int get hashCode => code.hashCode ^ expiresIn.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbPairingOffer &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          expiresIn == other.expiresIn;
}

/// FFI struct for pending review operation
class FrbPendingReviewOp {
  final int id;
  final String entityType;
  final int entityId;
  final String operation;
  final String? payload;
  final String source;
  final String createdAt;

  const FrbPendingReviewOp({
    required this.id,
    required this.entityType,
    required this.entityId,
    required this.operation,
    this.payload,
    required this.source,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      entityType.hashCode ^
      entityId.hashCode ^
      operation.hashCode ^
      payload.hashCode ^
      source.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbPendingReviewOp &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          entityType == other.entityType &&
          entityId == other.entityId &&
          operation == other.operation &&
          payload == other.payload &&
          source == other.source &&
          createdAt == other.createdAt;
}

/// A generated puzzle board (FFI-safe)
class FrbPuzzleBoard {
  final int bookId;
  final String title;
  final String coverUrl;
  final int gridSize;
  final Uint8List tiles;
  final int emptyIndex;
  final int parMoves;

  const FrbPuzzleBoard({
    required this.bookId,
    required this.title,
    required this.coverUrl,
    required this.gridSize,
    required this.tiles,
    required this.emptyIndex,
    required this.parMoves,
  });

  @override
  int get hashCode =>
      bookId.hashCode ^
      title.hashCode ^
      coverUrl.hashCode ^
      gridSize.hashCode ^
      tiles.hashCode ^
      emptyIndex.hashCode ^
      parMoves.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbPuzzleBoard &&
          runtimeType == other.runtimeType &&
          bookId == other.bookId &&
          title == other.title &&
          coverUrl == other.coverUrl &&
          gridSize == other.gridSize &&
          tiles == other.tiles &&
          emptyIndex == other.emptyIndex &&
          parMoves == other.parMoves;
}

/// A leaderboard entry for the sliding puzzle (FFI-safe)
class FrbPuzzleLeaderboardEntry {
  final int peerId;
  final String libraryName;
  final double bestScore;
  final String difficulty;
  final String playedAt;
  final bool isSelf;

  const FrbPuzzleLeaderboardEntry({
    required this.peerId,
    required this.libraryName,
    required this.bestScore,
    required this.difficulty,
    required this.playedAt,
    required this.isSelf,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      libraryName.hashCode ^
      bestScore.hashCode ^
      difficulty.hashCode ^
      playedAt.hashCode ^
      isSelf.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbPuzzleLeaderboardEntry &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          libraryName == other.libraryName &&
          bestScore == other.bestScore &&
          difficulty == other.difficulty &&
          playedAt == other.playedAt &&
          isSelf == other.isSelf;
}

/// A saved sliding puzzle score (FFI-safe)
class FrbPuzzleScore {
  final int? id;
  final String difficulty;
  final int gridSize;
  final double elapsedSeconds;
  final int moveCount;
  final int parMoves;
  final double normalizedScore;
  final String playedAt;

  /// Achievements unlocked after this game (empty if none)
  final List<String> newAchievements;

  const FrbPuzzleScore({
    this.id,
    required this.difficulty,
    required this.gridSize,
    required this.elapsedSeconds,
    required this.moveCount,
    required this.parMoves,
    required this.normalizedScore,
    required this.playedAt,
    required this.newAchievements,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      difficulty.hashCode ^
      gridSize.hashCode ^
      elapsedSeconds.hashCode ^
      moveCount.hashCode ^
      parMoves.hashCode ^
      normalizedScore.hashCode ^
      playedAt.hashCode ^
      newAchievements.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbPuzzleScore &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          difficulty == other.difficulty &&
          gridSize == other.gridSize &&
          elapsedSeconds == other.elapsedSeconds &&
          moveCount == other.moveCount &&
          parMoves == other.parMoves &&
          normalizedScore == other.normalizedScore &&
          playedAt == other.playedAt &&
          newAchievements == other.newAchievements;
}

@freezed
sealed class FrbRegisterParams with _$FrbRegisterParams {
  const factory FrbRegisterParams({
    required String nodeId,
    required String displayName,
    required int bookCount,
    required bool isListed,
    required bool requiresApproval,
    required String acceptFrom,
    String? description,
    String? locationCountry,
    required bool allowBorrowing,
    String? x25519PublicKey,
    String? website,
  }) = _FrbRegisterParams;
}

/// Streak info (FFI-safe)
class FrbStreakInfo {
  final int current;
  final int longest;

  const FrbStreakInfo({required this.current, required this.longest});

  @override
  int get hashCode => current.hashCode ^ longest.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbStreakInfo &&
          runtimeType == other.runtimeType &&
          current == other.current &&
          longest == other.longest;
}

/// FFI struct for sync result
class FrbSyncResult {
  final int sentCount;
  final int receivedCount;
  final int pendingReviewCount;

  const FrbSyncResult({
    required this.sentCount,
    required this.receivedCount,
    required this.pendingReviewCount,
  });

  @override
  int get hashCode =>
      sentCount.hashCode ^ receivedCount.hashCode ^ pendingReviewCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbSyncResult &&
          runtimeType == other.runtimeType &&
          sentCount == other.sentCount &&
          receivedCount == other.receivedCount &&
          pendingReviewCount == other.pendingReviewCount;
}

/// Simplified tag structure for FFI
@freezed
sealed class FrbTag with _$FrbTag {
  const factory FrbTag({
    required int id,
    required String name,
    int? parentId,
    required PlatformInt64 count,
  }) = _FrbTag;
}

/// Track progress (FFI-safe)
class FrbTrackProgress {
  final int level;
  final double progress;
  final PlatformInt64 current;
  final int nextThreshold;

  const FrbTrackProgress({
    required this.level,
    required this.progress,
    required this.current,
    required this.nextThreshold,
  });

  @override
  int get hashCode =>
      level.hashCode ^
      progress.hashCode ^
      current.hashCode ^
      nextThreshold.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbTrackProgress &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          progress == other.progress &&
          current == other.current &&
          nextThreshold == other.nextThreshold;
}
