// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'frb.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `account_device_entry`, `account_library_uuid`, `account_status_json`, `apply_fallback_preferences_to_modules`, `covers_dir`, `db`, `ensure_account_session`, `entries_to_frb`, `fill_state`, `from_info`, `from_manifest`, `from_summary`, `global_app_state`, `hub_db`, `hub_directory_svc`, `hub_directory_sync_catalog_inner`, `install_panic_hook`, `load_google_books_api_key`, `loan_due_reminder_text`, `loan_due_today_text`, `merge_api_keys`, `modules_to_fallback_preferences`, `nudge_source_label`, `rename_subject_in_books`, `runtime`, `track_to_frb`, `try_from_summary`, `undo_outcome_str`, `upsert_directory_catalog_cache`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AccountSession`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Initialize the FFI backend with database at the given path
/// Must be called before any other FFI functions
Future<String> initBackend({required String dbPath}) =>
    RustLib.instance.api.crateApiFrbInitBackend(dbPath: dbPath);

/// Pass the hub URL from Flutter to the Rust process environment.
/// Must be called once after init_backend, before any hub_directory calls.
/// Rust reads HUB_URL via std::env::var - it cannot see Flutter's dotenv map.
///
/// The .env value is only a default: if a relay has been configured (persisted
/// in `my_relay_config`), its URL takes precedence so the hub directory and
/// relay always point to the same hub.
Future<void> setHubUrlFfi({required String hubUrl}) =>
    RustLib.instance.api.crateApiFrbSetHubUrlFfi(hubUrl: hubUrl);

/// Check if the FFI backend is healthy
String healthCheck() => RustLib.instance.api.crateApiFrbHealthCheck();

/// Get the FFI backend version
String getVersion() => RustLib.instance.api.crateApiFrbGetVersion();

/// Return the last `lines` lines of the Rust tracing log file.
/// Empty string if the file does not exist, tracing is disabled (release
/// build), or `init_backend` has not run yet.
String getRustLogTail({required int lines}) =>
    RustLib.instance.api.crateApiFrbGetRustLogTail(lines: lines);

/// Simple greeting function to test the bridge
String greet({required String name}) =>
    RustLib.instance.api.crateApiFrbGreet(name: name);

/// Check if mDNS discovery service is currently active
/// This is a sync function that can be called to check status
bool isMdnsAvailable() => RustLib.instance.api.crateApiFrbIsMdnsAvailable();

/// Get the mDNS service type used for discovery
String getMdnsServiceType() =>
    RustLib.instance.api.crateApiFrbGetMdnsServiceType();

/// Get locally discovered peers via mDNS
/// This returns peers that have been found on the local network
Future<List<FrbDiscoveredPeer>> getLocalPeersFfi() =>
    RustLib.instance.api.crateApiFrbGetLocalPeersFfi();

/// Initialize mDNS service for discovery
/// Must be called to start announcing and discovering peers
Future<String> initMdnsFfi({
  required String libraryName,
  required int port,
  String? libraryId,
  String? ed25519PublicKey,
  String? x25519PublicKey,
}) => RustLib.instance.api.crateApiFrbInitMdnsFfi(
  libraryName: libraryName,
  port: port,
  libraryId: libraryId,
  ed25519PublicKey: ed25519PublicKey,
  x25519PublicKey: x25519PublicKey,
);

/// Stop mDNS service
Future<String> stopMdnsFfi() => RustLib.instance.api.crateApiFrbStopMdnsFfi();

/// Initialize the node's cryptographic identity.
/// Must be called after init_backend and after obtaining the library UUID.
/// Uses Argon2(library_uuid) to encrypt/decrypt the stored keypair.
///
/// Errors propagate through `IdentityError::Display`, which prefixes the
/// `DecryptionFailed` variant with `E_IDENTITY_DECRYPT_FAILED` so the Flutter
/// layer can pattern-match the FFI exception and surface a recovery dialog
/// instead of silently regenerating the identity (which would break peers).
Future<String> initIdentityFfi({required String libraryUuid}) =>
    RustLib.instance.api.crateApiFrbInitIdentityFfi(libraryUuid: libraryUuid);

/// User-confirmed identity regeneration: wipes `crypto_keys` and runs init.
///
/// Called by the Flutter recovery dialog when the user explicitly chooses
/// "Régénérer (perdre les peers)". Every paired peer (iPhone, Android, etc.)
/// will have to re-pair after this — that's the expected cost.
Future<String> confirmRegenerateIdentityFfi({required String libraryUuid}) =>
    RustLib.instance.api.crateApiFrbConfirmRegenerateIdentityFfi(
      libraryUuid: libraryUuid,
    );

/// Get the node's public keys as JSON: {"ed25519": "hex...", "x25519": "hex..."}
Future<String> getPublicKeysFfi() =>
    RustLib.instance.api.crateApiFrbGetPublicKeysFfi();

/// Generate a QR v2 payload as JSON string.
/// Includes library name, URL, UUID, and public keys.
Future<String> generateQrPayloadFfi({
  required String libraryName,
  required String url,
  required String libraryUuid,
}) => RustLib.instance.api.crateApiFrbGenerateQrPayloadFfi(
  libraryName: libraryName,
  url: url,
  libraryUuid: libraryUuid,
);

/// Parse a QR payload (supports both v1 and v2 formats).
/// Returns a normalized JSON string with all available fields.
Future<String> parseQrPayloadFfi({required String payload}) =>
    RustLib.instance.api.crateApiFrbParseQrPayloadFfi(payload: payload);

/// Generate an invite link with the library's connection info encoded in the URL fragment.
/// Format: https://bibliogenius.org/invite#BASE64URL(json)
/// The fragment (#) is never sent to the web server (B8 compliance).
/// Payload v3 adds optional relay info for WAN connectivity.
Future<String> generateInviteLinkFfi({
  required String libraryName,
  required String url,
  required String libraryUuid,
  String? relayUrl,
  String? mailboxId,
  String? relayWriteToken,
}) => RustLib.instance.api.crateApiFrbGenerateInviteLinkFfi(
  libraryName: libraryName,
  url: url,
  libraryUuid: libraryUuid,
  relayUrl: relayUrl,
  mailboxId: mailboxId,
  relayWriteToken: relayWriteToken,
);

/// Parse an invite link, extracting the JSON payload from the URL fragment.
Future<String> parseInviteLinkFfi({required String link}) =>
    RustLib.instance.api.crateApiFrbParseInviteLinkFfi(link: link);

/// Account session status for the UI. Cheap: reads the plaintext metadata columns and
/// never decrypts the trousseau or hits the network.
Future<String> accountStatusFfi() =>
    RustLib.instance.api.crateApiFrbAccountStatusFfi();

/// Join an EXISTING account on this device with its passphrase (Path A). Unlocks the
/// trousseau, enrolls this device into the signed registry, and persists the session.
Future<String> accountEnrollPassphraseFfi({
  required String email,
  required String passphrase,
  required String deviceName,
}) => RustLib.instance.api.crateApiFrbAccountEnrollPassphraseFfi(
  email: email,
  passphrase: passphrase,
  deviceName: deviceName,
);

/// NEW device, step 1: generate this device's lane key and return the `bg-pair` QR payload
/// (its lane key + ADR-039 public keys) for an authorized device to scan. The payload
/// carries NO secret; the X25519 public key in it is what the authorized device will seal
/// the trousseau to (ADR-045 authenticated channel).
Future<String> accountGetDevicePairingQrFfi({required String deviceName}) =>
    RustLib.instance.api.crateApiFrbAccountGetDevicePairingQrFfi(
      deviceName: deviceName,
    );

/// AUTHORIZED device: scan a NEW device's `bg-pair` QR, seal the trousseau to it, and add it
/// to the signed registry. Returns the `bg-sealed` payload (sealed blob + account email) to
/// show back as a QR.
///
/// SECURITY (ADR-045 / ADR-042 §14 H2): the X25519 key the trousseau is sealed to comes
/// ONLY from the scanned payload (`req.x25519_pk`) — never a hub field. Do not refactor this
/// to source the key from anywhere else.
Future<String> accountAuthorizeDeviceFfi({required String pairingQrPayload}) =>
    RustLib.instance.api.crateApiFrbAccountAuthorizeDeviceFfi(
      pairingQrPayload: pairingQrPayload,
    );

/// NEW device, step 2: scan the `bg-sealed` QR returned by the authorized device, open the
/// trousseau with this device's X25519 identity, authenticate, and persist the session. The
/// authorizing device already registered this device, so no registry write happens here.
Future<String> accountEnrollFromSealedFfi({required String sealedQrPayload}) =>
    RustLib.instance.api.crateApiFrbAccountEnrollFromSealedFfi(
      sealedQrPayload: sealedQrPayload,
    );

/// Fetch and adopt the account's signed device registry, returning the authorized devices
/// as JSON (`{device_id, name, is_self}`). This is the H3 step `sync_once` runs first; it
/// is exposed on its own so the UI can list/refresh devices before data sync ships.
Future<String> accountRefreshDevicesFfi() =>
    RustLib.instance.api.crateApiFrbAccountRefreshDevicesFfi();

/// Sign out of the account on this device: drop the in-RAM session and delete the encrypted
/// `account_session` row. Does not revoke the device server-side (that is a registry edit
/// from another device). Idempotent.
Future<String> accountLogoutFfi() =>
    RustLib.instance.api.crateApiFrbAccountLogoutFfi();

/// Score a candidate passphrase locally for the signup strength meter. No network, no DB,
/// no logging (SECURITY_GUIDELINES F7: the check is 100% local). Returns JSON
/// `{score 0-4, length, acceptable, warning, suggestions}`; the UI gates the signup button
/// on `acceptable` (zxcvbn 4/4 AND length >= 12).
Future<String> accountCheckPassphraseFfi({required String passphrase}) =>
    RustLib.instance.api.crateApiFrbAccountCheckPassphraseFfi(
      passphrase: passphrase,
    );

/// Create a NEW account on this (first) device with a passphrase (Path A). Enforces the
/// strength floor, generates and double-wraps the trousseau, publishes the first signed
/// registry, persists the session, and returns the one-time BIP39 recovery phrase inside the
/// status JSON (`recovery_phrase`) for the UI to display ONCE. The phrase is never persisted
/// or logged; losing both passphrase and kit means permanent account loss (ADR-042 §8).
Future<String> accountSignupFfi({
  required String email,
  required String passphrase,
  required String deviceName,
}) => RustLib.instance.api.crateApiFrbAccountSignupFfi(
  email: email,
  passphrase: passphrase,
  deviceName: deviceName,
);

/// Update only the library name in the database (library_config + libraries tables).
/// This is the FFI-direct path used by the flash editor on the home screen.
/// Only touches the `name` and `updated_at` fields - no other settings are overwritten.
Future<void> updateLibraryNameFfi({required String name}) =>
    RustLib.instance.api.crateApiFrbUpdateLibraryNameFfi(name: name);

/// Create a new book
Future<FrbBook> createBook({required FrbBook book}) =>
    RustLib.instance.api.crateApiFrbCreateBook(book: book);

/// Get all books with optional filters
Future<List<FrbBook>> getAllBooks({
  String? status,
  String? title,
  String? tag,
}) => RustLib.instance.api.crateApiFrbGetAllBooks(
  status: status,
  title: title,
  tag: tag,
);

/// Get a single book by ID
Future<FrbBook> getBookById({required int id}) =>
    RustLib.instance.api.crateApiFrbGetBookById(id: id);

/// Update an existing book
Future<FrbBook> updateBook({required int id, required FrbBook book}) =>
    RustLib.instance.api.crateApiFrbUpdateBook(id: id, book: book);

/// Delete a book
Future<void> deleteBook({required int id}) =>
    RustLib.instance.api.crateApiFrbDeleteBook(id: id);

/// Count total books
Future<PlatformInt64> countBooks() =>
    RustLib.instance.api.crateApiFrbCountBooks();

/// Enrich books that have an ISBN but no cover by checking external sources.
/// Runs in background, returns the count of covers found and persisted.
Future<int> enrichMissingCovers() =>
    RustLib.instance.api.crateApiFrbEnrichMissingCovers();

/// Search for a cover URL for a single ISBN from external sources.
Future<String?> searchCoverForBook({required String isbn}) =>
    RustLib.instance.api.crateApiFrbSearchCoverForBook(isbn: isbn);

/// Search for a cover URL by title with author verification.
/// Used as a fallback when ISBN-based search returns nothing.
/// Returns a cover only if the result author matches the given author.
Future<String?> searchCoverByTitle({
  required String title,
  String? author,
  bool? enableGoogle,
}) => RustLib.instance.api.crateApiFrbSearchCoverByTitle(
  title: title,
  author: author,
  enableGoogle: enableGoogle,
);

/// Search ALL enabled cover sources in parallel for a given ISBN.
/// Returns all found cover candidates for the picker carousel.
Future<List<FrbCoverCandidate>> searchAllCoversForBook({
  required String isbn,
}) => RustLib.instance.api.crateApiFrbSearchAllCoversForBook(isbn: isbn);

/// Search ALL enabled sources by title in parallel for the cover picker.
Future<List<FrbCoverCandidate>> searchAllCoversByTitle({
  required String title,
  String? author,
  bool? enableGoogle,
}) => RustLib.instance.api.crateApiFrbSearchAllCoversByTitle(
  title: title,
  author: author,
  enableGoogle: enableGoogle,
);

/// Look up book metadata by ISBN from external sources (BNF, Inventaire, OpenLibrary, etc.).
/// Used by the metadata refresh feature to let users preview and cherry-pick fields.
Future<FrbBookMetadata?> lookupBookMetadata({
  required String isbn,
  String? lang,
}) =>
    RustLib.instance.api.crateApiFrbLookupBookMetadata(isbn: isbn, lang: lang);

/// Completeness statistic for the dashboard "Complétude" card.
Future<FrbCompletenessStats> metadataFillStats() =>
    RustLib.instance.api.crateApiFrbMetadataFillStats();

/// Start (or resume) the bulk fill. Returns the batch id. `languages` is the
/// user's reading-language config (comma-joined) for summary coherence.
/// `lot_limit` caps how many books this invocation processes before pausing the
/// run as resumable (the "small batches" nudge); `None` runs to completion.
Future<String> metadataFillStart({String? languages, int? lotLimit}) => RustLib
    .instance
    .api
    .crateApiFrbMetadataFillStart(languages: languages, lotLimit: lotLimit);

/// Current/last run progress (None if a run has never been started).
Future<FrbFillProgress?> metadataFillProgress() =>
    RustLib.instance.api.crateApiFrbMetadataFillProgress();

/// Request cancellation of the active run.
Future<void> metadataFillCancel() =>
    RustLib.instance.api.crateApiFrbMetadataFillCancel();

/// Recently completed books with the still-active fields the fill added.
Future<List<FrbFilledBook>> metadataFillRecent({required int limit}) =>
    RustLib.instance.api.crateApiFrbMetadataFillRecent(limit: limit);

/// Owned, incomplete books without an ISBN (not processable; manual fix list).
Future<List<FrbIncompleteBook>> metadataFillBooksWithoutIsbn() =>
    RustLib.instance.api.crateApiFrbMetadataFillBooksWithoutIsbn();

/// All owned, incomplete books with their missing fields (closest-to-complete
/// first), for the manual completion overview.
Future<List<FrbIncompleteBookDetail>> metadataFillIncomplete({int? limit}) =>
    RustLib.instance.api.crateApiFrbMetadataFillIncomplete(limit: limit);

/// Undo a single filled field. Returns `reverted` | `superseded` | `not_found`.
Future<String> metadataFillUndoField({required PlatformInt64 journalId}) =>
    RustLib.instance.api.crateApiFrbMetadataFillUndoField(journalId: journalId);

/// Undo all fields the fill added to one book in a batch. Returns reverted count.
Future<int> metadataFillUndoBook({
  required String batchId,
  required int bookId,
}) => RustLib.instance.api.crateApiFrbMetadataFillUndoBook(
  batchId: batchId,
  bookId: bookId,
);

/// Undo every field a whole run added. Returns reverted count.
Future<int> metadataFillUndoRun({required String batchId}) =>
    RustLib.instance.api.crateApiFrbMetadataFillUndoRun(batchId: batchId);

/// Get all tags with hierarchy info
Future<List<FrbTag>> getAllTags() =>
    RustLib.instance.api.crateApiFrbGetAllTags();

/// Create a new tag
Future<FrbTag> createTag({required String name, int? parentId}) =>
    RustLib.instance.api.crateApiFrbCreateTag(name: name, parentId: parentId);

/// Update a tag
Future<FrbTag> updateTag({
  required int id,
  required String name,
  int? parentId,
}) => RustLib.instance.api.crateApiFrbUpdateTag(
  id: id,
  name: name,
  parentId: parentId,
);

/// Public FFI entry point: rename a subject in all books.
Future<void> renameSubject({
  required String oldName,
  required String newName,
}) => RustLib.instance.api.crateApiFrbRenameSubject(
  oldName: oldName,
  newName: newName,
);

/// Delete a tag
Future<void> deleteTag({required int id}) =>
    RustLib.instance.api.crateApiFrbDeleteTag(id: id);

/// Reorder books by updating shelf positions
Future<void> reorderBooks({required List<int> bookIds}) =>
    RustLib.instance.api.crateApiFrbReorderBooks(bookIds: bookIds);

/// Get all contacts with optional filters
Future<List<FrbContact>> getAllContacts({
  int? libraryId,
  String? contactType,
}) => RustLib.instance.api.crateApiFrbGetAllContacts(
  libraryId: libraryId,
  contactType: contactType,
);

/// Get a single contact by ID
Future<FrbContact> getContactById({required int id}) =>
    RustLib.instance.api.crateApiFrbGetContactById(id: id);

/// Count total contacts
Future<PlatformInt64> countContacts() =>
    RustLib.instance.api.crateApiFrbCountContacts();

/// Create a new contact
Future<FrbContact> createContact({required FrbContact contact}) =>
    RustLib.instance.api.crateApiFrbCreateContact(contact: contact);

/// Update an existing contact
Future<FrbContact> updateContact({required FrbContact contact}) =>
    RustLib.instance.api.crateApiFrbUpdateContact(contact: contact);

/// Delete a contact by ID (soft delete)
Future<void> deleteContact({required int id}) =>
    RustLib.instance.api.crateApiFrbDeleteContact(id: id);

/// Get all loans with optional filters
Future<List<FrbLoan>> getAllLoans({
  int? libraryId,
  String? status,
  int? contactId,
}) => RustLib.instance.api.crateApiFrbGetAllLoans(
  libraryId: libraryId,
  status: status,
  contactId: contactId,
);

/// Count active loans
Future<PlatformInt64> countActiveLoans() =>
    RustLib.instance.api.crateApiFrbCountActiveLoans();

/// Create a new loan
Future<int> createLoan({
  required int copyId,
  required int contactId,
  required int libraryId,
  required String loanDate,
  required String dueDate,
  String? notes,
}) => RustLib.instance.api.crateApiFrbCreateLoan(
  copyId: copyId,
  contactId: contactId,
  libraryId: libraryId,
  loanDate: loanDate,
  dueDate: dueDate,
  notes: notes,
);

/// Count returned loans (for cleanup confirmation dialog)
Future<PlatformInt64> countReturnedLoans() =>
    RustLib.instance.api.crateApiFrbCountReturnedLoans();

/// Delete all returned loans, returns the number of deleted rows
Future<BigInt> deleteReturnedLoans() =>
    RustLib.instance.api.crateApiFrbDeleteReturnedLoans();

/// Count closed incoming P2P requests (not pending)
Future<PlatformInt64> countClosedIncomingRequests() =>
    RustLib.instance.api.crateApiFrbCountClosedIncomingRequests();

/// Delete all closed incoming P2P requests (not pending)
Future<BigInt> deleteClosedIncomingRequests() =>
    RustLib.instance.api.crateApiFrbDeleteClosedIncomingRequests();

/// Count closed outgoing P2P requests (not pending)
Future<PlatformInt64> countClosedOutgoingRequests() =>
    RustLib.instance.api.crateApiFrbCountClosedOutgoingRequests();

/// Delete all closed outgoing P2P requests (not pending)
Future<BigInt> deleteClosedOutgoingRequests() =>
    RustLib.instance.api.crateApiFrbDeleteClosedOutgoingRequests();

/// Return a loan
Future<String> returnLoan({required int id}) =>
    RustLib.instance.api.crateApiFrbReturnLoan(id: id);

/// Get the current loan settings
Future<FrbLoanSettings> getLoanSettings() =>
    RustLib.instance.api.crateApiFrbGetLoanSettings();

/// Update the global loan settings
Future<FrbLoanSettings> updateLoanSettings({
  required int defaultLoanDurationDays,
  required bool perBookDurationEnabled,
  required int reminderDaysBeforeDue,
}) => RustLib.instance.api.crateApiFrbUpdateLoanSettings(
  defaultLoanDurationDays: defaultLoanDurationDays,
  perBookDurationEnabled: perBookDurationEnabled,
  reminderDaysBeforeDue: reminderDaysBeforeDue,
);

/// Check active loans for upcoming due dates and emit reminder notifications.
///
/// Emits:
/// - `LoanDueReminder` when `0 < days_until_due <= reminder_days_before_due`
/// - `LoanDueToday` when `days_until_due <= 0` (due today or overdue)
///
/// Deduplication is enforced: no duplicate notification per loan per type.
/// Returns the number of new notifications created.
Future<int> checkLoanReminders({required String language}) =>
    RustLib.instance.api.crateApiFrbCheckLoanReminders(language: language);

/// Get the effective loan duration for a specific book (in days).
/// Returns the per-book override if enabled and set, otherwise the global default.
Future<int> getEffectiveLoanDuration({required int bookId}) =>
    RustLib.instance.api.crateApiFrbGetEffectiveLoanDuration(bookId: bookId);

/// Get the per-book loan duration override (None = uses global default)
Future<int?> getBookLoanDuration({required int bookId}) =>
    RustLib.instance.api.crateApiFrbGetBookLoanDuration(bookId: bookId);

/// Set the per-book loan duration override (pass None to clear and use global default)
Future<void> setBookLoanDuration({required int bookId, int? days}) => RustLib
    .instance
    .api
    .crateApiFrbSetBookLoanDuration(bookId: bookId, days: days);

/// Reset the entire application - deletes all data from all tables
/// This is irreversible and should be used with caution
Future<String> resetApp() => RustLib.instance.api.crateApiFrbResetApp();

/// Start the HTTP server on the specified port (FFI)
/// This is required for P2P functionality in standalone mode
/// If the specified port is occupied, tries the next 10 ports automatically
Future<int> startServer({required int port}) =>
    RustLib.instance.api.crateApiFrbStartServer(port: port);

/// Subscribe to the relay nudge event stream.
///
/// Each emitted event indicates that `poll_once()` finished processing at
/// least one message and persisted it to the local DB. Flutter consumers
/// should refresh the relevant providers (notifications, loan requests,
/// peer libraries) on receipt.
///
/// The function returns immediately after spawning a forwarding task. The
/// task lives until the Dart side drops the StreamSink.
/// Subscribe to the catalog-change event stream.
///
/// Each emitted event indicates that a peer added or deleted a book and
/// their catalog is now different from what the local device has cached.
/// Flutter consumers (typically `PeerBookListScreen`) should trigger a
/// re-sync when they receive an event matching the displayed peer.
///
/// The stream lives until the Dart side drops the `StreamSink`. Multiple
/// concurrent subscribers each receive their own independent copy of every
/// event (broadcast semantics). A slow subscriber lags without blocking
/// the emitter.
/// Attempt a delta sync against a peer via E2EE (ADR-029).
///
/// Returns `true` when a delta window was successfully fetched and applied
/// to `peer_books` - the caller should SKIP the legacy
/// `relay_library_request("manifest")` loop and simply re-read the local
/// cache. Returns `false` on any non-applied outcome
/// (`ResetRequired`, `FallbackRequired`, `E2eeUnavailable`, transport
/// error) - the caller should run the legacy full-catalog flow as before.
///
/// Designed to be called from the Flutter `subscribe_catalog_changes`
/// handler before triggering a full sync, so the delta path replaces the
/// full pull whenever it succeeds.
Future<bool> tryPeerCatalogDelta({required int peerId}) =>
    RustLib.instance.api.crateApiFrbTryPeerCatalogDelta(peerId: peerId);

/// Same as [`try_peer_catalog_delta`] but returns a descriptive string so
/// Flutter can surface the exact outcome without depending on the FFI log
/// file (invisible on iOS). Format:
/// - `applied:<ops>:<cursor>:<has_more>`: delta applied.
/// - `fallback_required`: peer did not respond.
/// - `e2ee_unavailable`: no E2EE capability.
/// - `reset_required`: cursor pruned upstream, responder did not populate
///   `current_cursor` (older codebase).
/// - `reset_required:<N>`: cursor pruned upstream, responder reports its
///   current `operation_log` max id as `N`. The caller SHOULD persist `N`
///   via [`set_peer_delta_cursor`] only after a successful legacy full
///   sync, to break the reset loop.
/// - `no_state`: AppState not initialised.
/// - `error:<message>`: transport or DB error.
Future<String> tryPeerCatalogDeltaDetailed({required int peerId}) =>
    RustLib.instance.api.crateApiFrbTryPeerCatalogDeltaDetailed(peerId: peerId);

/// Persist `peers.last_delta_cursor` for the given peer.
///
/// Flutter calls this after a successful legacy full-catalog sync that was
/// triggered by a `reset_required:<N>` outcome, passing the responder's
/// reported `current_cursor`. This breaks the reset loop by letting the
/// next sync resume as a delta.
///
/// Returns `Ok(())` on success, or a descriptive error string on DB
/// failure / unknown peer id. Safe to call with a cursor of 0 (no-op for
/// peers that have never had any operations).
Future<void> setPeerDeltaCursor({
  required int peerId,
  required PlatformInt64 cursor,
}) => RustLib.instance.api.crateApiFrbSetPeerDeltaCursor(
  peerId: peerId,
  cursor: cursor,
);

/// Persist a refreshed `peers.library_uuid` for the given peer (ADR-030).
///
/// The E2EE-signed manifest from a peer carries its current `library_uuid`.
/// When that value diverges from the locally persisted one, the local row
/// is stale (historical drift from an older pairing code path). This helper
/// adopts the manifest value so all downstream lookups (hub directory
/// fallback, event UUID matching on later mounts) see the current identity.
///
/// Trust model: only call this with a `new_uuid` read from an ENVELOPE
/// that successfully verified against `peers.public_key` (ed25519). The
/// signature check on that path is what binds the uuid to the peer identity.
/// Skipping it would let any relay forwarder inject an arbitrary uuid.
/// `peer_book` rows are intentionally left untouched: they key on
/// `peer_id`, not `library_uuid`, and the enclosing manifest sync pass is
/// already about to refresh them via upsert (a premature purge would flash
/// an empty library in the UI before the pages arrive).
///
/// Idempotent: writing the same uuid twice is a no-op; writing a null or
/// empty string is rejected to avoid clearing a healthy value by accident.
///
/// Returns `Ok(true)` when the stored uuid changed (Flutter may log it),
/// `Ok(false)` when the value was already current.
Future<bool> updatePeerLibraryUuid({
  required int peerId,
  required String newUuid,
}) => RustLib.instance.api.crateApiFrbUpdatePeerLibraryUuid(
  peerId: peerId,
  newUuid: newUuid,
);

Stream<FrbCatalogChangedEvent> subscribeCatalogChanges() =>
    RustLib.instance.api.crateApiFrbSubscribeCatalogChanges();

/// Subscribe to the profile-change event stream (ADR-025).
///
/// Each emitted event indicates that a peer's profile (today: avatar)
/// changed. Flutter should pull the new values via
/// `try_peer_avatar_pull(peer_id)`. The subscription is intended to be
/// registered once at app level (`AvatarSyncService`) so avatars stay
/// fresh across every screen without per-screen wiring.
///
/// The stream lives until the Dart side drops the `StreamSink`.
Stream<FrbProfileChangedEvent> subscribeProfileChanges() =>
    RustLib.instance.api.crateApiFrbSubscribeProfileChanges();

/// Pull a peer's avatar (and `library_name`) over E2EE (ADR-025).
///
/// Returns `true` when at least one field changed and was persisted to the
/// local `peers` row. Returns `false` when the peer is up to date, the
/// peer did not respond, or E2EE is unavailable. Errors are converted to
/// `false` and logged (the caller's UI should degrade gracefully to the
/// cached avatar).
///
/// Designed to be called from the Flutter `subscribe_profile_changes`
/// handler (`AvatarSyncService`) whenever a peer emits a `profile_changed`
/// nudge. Also safe to call opportunistically on first-seen of a relay-only
/// peer.
Future<bool> tryPeerAvatarPull({required int peerId}) =>
    RustLib.instance.api.crateApiFrbTryPeerAvatarPull(peerId: peerId);

Stream<FrbNudgeEvent> subscribeRelayNudges() =>
    RustLib.instance.api.crateApiFrbSubscribeRelayNudges();

/// Stream of leaderboard-change events from peers (ADR-023).
///
/// Each emitted event indicates that a peer pushed updated scores via
/// `public_stats_push` and the local cache has been updated. Flutter
/// consumers (game leaderboard screens) should reload network scores.
///
/// The stream lives until the Dart side drops the `StreamSink`. Multiple
/// concurrent subscribers each receive their own independent copy of every
/// event (broadcast semantics). A slow subscriber lags without blocking
/// the emitter.
Stream<FrbLeaderboardChangedEvent> subscribeLeaderboardChanges() =>
    RustLib.instance.api.crateApiFrbSubscribeLeaderboardChanges();

/// Get available difficulty levels based on books with covers
Future<List<String>> memoryGameAvailableDifficulties() =>
    RustLib.instance.api.crateApiFrbMemoryGameAvailableDifficulties();

/// Set up a new memory game with the given difficulty
Future<List<FrbMemoryCard>> memoryGameSetup({required String difficulty}) =>
    RustLib.instance.api.crateApiFrbMemoryGameSetup(difficulty: difficulty);

/// Submit a completed game and get the score back
Future<FrbMemoryScore> memoryGameFinish({
  required String difficulty,
  required double elapsedSeconds,
  required int errors,
  required int pairsCount,
}) => RustLib.instance.api.crateApiFrbMemoryGameFinish(
  difficulty: difficulty,
  elapsedSeconds: elapsedSeconds,
  errors: errors,
  pairsCount: pairsCount,
);

/// Get top memory game scores
Future<List<FrbMemoryScore>> memoryGameTopScores() =>
    RustLib.instance.api.crateApiFrbMemoryGameTopScores();

/// Get leaderboard (peer scores + local user's best)
Future<List<FrbMemoryLeaderboardEntry>> memoryGameLeaderboard() =>
    RustLib.instance.api.crateApiFrbMemoryGameLeaderboard();

/// Return a debug summary of all peers and their relay credential state.
///
/// Used to diagnose leaderboard relay issues (ADR-022). Returns one line per peer
/// with name, connection_status, key_exchange_done, and whether relay credentials
/// are present. Call from Flutter and log with debugPrint.
Future<String> peersRelayDebugInfo() =>
    RustLib.instance.api.crateApiFrbPeersRelayDebugInfo();

/// Reset all local memory game scores.
Future<void> memoryGameResetScores() =>
    RustLib.instance.api.crateApiFrbMemoryGameResetScores();

/// Reset all local sliding puzzle scores.
Future<void> puzzleGameResetScores() =>
    RustLib.instance.api.crateApiFrbPuzzleGameResetScores();

/// Reset all local hangman scores.
Future<void> hangmanResetScores() =>
    RustLib.instance.api.crateApiFrbHangmanResetScores();

/// Refresh ALL leaderboard caches (memory, puzzle, hangman, gamification) in one pass.
///
/// A single relay round-trip per peer populates all game caches. When `skip_direct`
/// is true, Phase 1 direct HTTP is skipped (use on cellular where LAN peers are
/// unreachable). Called by Flutter at startup (pre-warm) and by per-game refresh.
Future<void> refreshAllLeaderboards({required bool skipDirect}) => RustLib
    .instance
    .api
    .crateApiFrbRefreshAllLeaderboards(skipDirect: skipDirect);

/// Refresh the network memory game leaderboard by syncing with all accepted peers.
/// Uses the unified sync that populates all game caches in one relay pass.
Future<List<FrbMemoryLeaderboardEntry>> memoryGameRefreshLeaderboard() =>
    RustLib.instance.api.crateApiFrbMemoryGameRefreshLeaderboard();

/// Get available puzzle difficulty levels based on books with covers
Future<List<String>> puzzleAvailableDifficulties() =>
    RustLib.instance.api.crateApiFrbPuzzleAvailableDifficulties();

/// Set up a new sliding puzzle with the given difficulty
Future<FrbPuzzleBoard> puzzleSetup({required String difficulty}) =>
    RustLib.instance.api.crateApiFrbPuzzleSetup(difficulty: difficulty);

/// Submit a completed sliding puzzle and get the score back
Future<FrbPuzzleScore> puzzleFinish({
  required String difficulty,
  required int gridSize,
  required double elapsedSeconds,
  required int moveCount,
  required int parMoves,
}) => RustLib.instance.api.crateApiFrbPuzzleFinish(
  difficulty: difficulty,
  gridSize: gridSize,
  elapsedSeconds: elapsedSeconds,
  moveCount: moveCount,
  parMoves: parMoves,
);

/// Get top sliding puzzle scores
Future<List<FrbPuzzleScore>> puzzleTopScores() =>
    RustLib.instance.api.crateApiFrbPuzzleTopScores();

/// Get puzzle leaderboard (peer scores + local user's best)
Future<List<FrbPuzzleLeaderboardEntry>> puzzleGameLeaderboard() =>
    RustLib.instance.api.crateApiFrbPuzzleGameLeaderboard();

/// Refresh the network puzzle leaderboard by syncing with all accepted peers.
/// Fetches each peer's /api/game/puzzle/public-best, upserts into peer_puzzle_scores,
/// then returns the merged leaderboard.
Future<List<FrbPuzzleLeaderboardEntry>> puzzleGameRefreshLeaderboard() =>
    RustLib.instance.api.crateApiFrbPuzzleGameRefreshLeaderboard();

/// Get available hangman difficulty levels based on valid titles count
Future<List<String>> hangmanAvailableDifficulties() =>
    RustLib.instance.api.crateApiFrbHangmanAvailableDifficulties();

/// Set up a new hangman game with the given difficulty.
/// `exclude_book_ids` -- book IDs already played in the current session (avoids same series).
Future<FrbHangmanSetup> hangmanSetup({
  required String difficulty,
  required List<int> excludeBookIds,
}) => RustLib.instance.api.crateApiFrbHangmanSetup(
  difficulty: difficulty,
  excludeBookIds: excludeBookIds,
);

/// Submit a completed hangman game and get the score back
Future<FrbHangmanScore> hangmanFinish({
  required int bookId,
  required String difficulty,
  required double elapsedSeconds,
  required int errors,
  required int hintsUsed,
  required bool won,
}) => RustLib.instance.api.crateApiFrbHangmanFinish(
  bookId: bookId,
  difficulty: difficulty,
  elapsedSeconds: elapsedSeconds,
  errors: errors,
  hintsUsed: hintsUsed,
  won: won,
);

/// Get top hangman scores
Future<List<FrbHangmanScore>> hangmanTopScores() =>
    RustLib.instance.api.crateApiFrbHangmanTopScores();

/// Get hangman leaderboard (peer scores + local user's best)
Future<List<FrbHangmanLeaderboardEntry>> hangmanLeaderboard() =>
    RustLib.instance.api.crateApiFrbHangmanLeaderboard();

/// Refresh the hangman leaderboard by syncing with all accepted peers
Future<List<FrbHangmanLeaderboardEntry>> hangmanRefreshLeaderboard() =>
    RustLib.instance.api.crateApiFrbHangmanRefreshLeaderboard();

/// Get full gamification status via FFI (replaces HTTP getUserStatus)
Future<FrbGamificationStatus> gamificationGetStatus() =>
    RustLib.instance.api.crateApiFrbGamificationGetStatus();

/// Get leaderboard via FFI (replaces HTTP getLeaderboard)
Future<FrbLeaderboardResponse> gamificationGetLeaderboard() =>
    RustLib.instance.api.crateApiFrbGamificationGetLeaderboard();

/// Refresh leaderboard (returns current state) via FFI.
/// Peer sync happens via the HTTP endpoint - this just returns current data.
Future<FrbLeaderboardResponse> gamificationRefreshLeaderboard() =>
    RustLib.instance.api.crateApiFrbGamificationRefreshLeaderboard();

/// Update gamification config via FFI
Future<void> gamificationUpdateConfig({
  int? readingGoalYearly,
  String? achievementsStyle,
}) => RustLib.instance.api.crateApiFrbGamificationUpdateConfig(
  readingGoalYearly: readingGoalYearly,
  achievementsStyle: achievementsStyle,
);

/// Check and unlock eligible achievements via FFI
Future<List<String>> gamificationCheckAchievements() =>
    RustLib.instance.api.crateApiFrbGamificationCheckAchievements();

/// Update daily streak via FFI
Future<FrbStreakInfo> gamificationUpdateStreak() =>
    RustLib.instance.api.crateApiFrbGamificationUpdateStreak();

/// Read the installation profile's search settings (toggles + API keys).
///
/// Used by the Flutter settings screen to display the persisted state of
/// the "Search Sources" section. Returns an error if the profile row is
/// missing; callers should fall back to defaults in that case.
Future<FrbSearchSettings> installationProfileGetSearchSettings() =>
    RustLib.instance.api.crateApiFrbInstallationProfileGetSearchSettings();

/// Persist the installation profile's search settings (source toggles + API
/// keys) directly to the database.
///
/// This is the FFI-mode counterpart of `PUT /api/profile`: native clients call
/// it so the persisted state survives an app restart even when the embedded
/// HTTP server is not running. Previously the FFI write path depended on that
/// server and silently no-op'd when it was down, so toggles reverted on reload.
/// Read the value back via [`installation_profile_get_search_settings`].
///
/// Security: `api_keys` holds secrets; they are merged and stored but never
/// logged. The profile row (id 1) is the single source of truth, shared with
/// the HTTP write path, so both stay consistent.
Future<void> installationProfileSetSearchSettings({
  required Map<String, bool> fallbackPreferences,
  required Map<String, String> apiKeys,
}) => RustLib.instance.api.crateApiFrbInstallationProfileSetSearchSettings(
  fallbackPreferences: fallbackPreferences,
  apiKeys: apiKeys,
);

/// List operation log entries with optional filters
Future<List<FrbOperationLogEntry>> operationLogList({
  String? entityType,
  String? operation,
  String? status,
  String? query,
  BigInt? page,
  BigInt? limit,
}) => RustLib.instance.api.crateApiFrbOperationLogList(
  entityType: entityType,
  operation: operation,
  status: status,
  query: query,
  page: page,
  limit: limit,
);

/// Get operation log stats
Future<FrbOperationLogStats> operationLogStats() =>
    RustLib.instance.api.crateApiFrbOperationLogStats();

/// Get distinct entity types for filter dropdowns
Future<List<String>> operationLogEntityTypes() =>
    RustLib.instance.api.crateApiFrbOperationLogEntityTypes();

/// Returns the local hub directory settings, or None if not yet registered.
Future<FrbDirectoryConfig?> hubDirectoryGetConfig() =>
    RustLib.instance.api.crateApiFrbHubDirectoryGetConfig();

/// Returns the local relay configuration (relay_url, mailbox_uuid, write_token).
/// Returns None if relay is not configured yet.
/// Note: read_token is intentionally excluded (S2: never leaves the device).
Future<FrbRelayConfig?> getRelayConfigFfi() =>
    RustLib.instance.api.crateApiFrbGetRelayConfigFfi();

/// Exports the hub directory write_token for Keychain backup.
/// Used by Flutter to persist the token in platform-secure storage
/// so it survives app reinstalls (critical on iOS).
/// Returns None if not yet registered.
Future<String?> hubDirectoryExportWriteToken() =>
    RustLib.instance.api.crateApiFrbHubDirectoryExportWriteToken();

/// Imports a write_token recovered from Keychain after app reinstall.
/// Restores hub authentication without requiring a new registration.
Future<void> hubDirectoryImportWriteToken({
  required String nodeId,
  required String writeToken,
}) => RustLib.instance.api.crateApiFrbHubDirectoryImportWriteToken(
  nodeId: nodeId,
  writeToken: writeToken,
);

/// Purges the local hub_directory_config row, forcing a fresh registration
/// on the next ensureRegistered() call. Used for 401 recovery when the
/// stored write_token is no longer valid on the hub.
Future<void> hubDirectoryPurgeConfig() =>
    RustLib.instance.api.crateApiFrbHubDirectoryPurgeConfig();

/// Returns the locally stored recovery code for display in settings.
/// Returns None if not yet registered or if registration predates recovery codes.
Future<String?> hubDirectoryGetRecoveryCode() =>
    RustLib.instance.api.crateApiFrbHubDirectoryGetRecoveryCode();

/// Recovers a hub profile using a one-time recovery code.
/// On success: stores the new write_token + recovery_code locally and returns the config.
Future<FrbDirectoryConfig> hubDirectoryRecover({
  required String nodeId,
  required String recoveryCode,
}) => RustLib.instance.api.crateApiFrbHubDirectoryRecover(
  nodeId: nodeId,
  recoveryCode: recoveryCode,
);

/// Registers with the hub directory (first call) or updates the profile.
/// On first registration, the write_token is persisted automatically.
Future<FrbDirectoryConfig> hubDirectoryRegister({
  required FrbRegisterParams params,
}) => RustLib.instance.api.crateApiFrbHubDirectoryRegister(params: params);

/// Pushes the local ISBN list to the hub catalog cache (legacy, ISBN-only).
Future<void> hubDirectoryPushCatalog({required List<String> isbnList}) =>
    RustLib.instance.api.crateApiFrbHubDirectoryPushCatalog(isbnList: isbnList);

/// Reads all owned books from the local database, collects title, author,
/// and cover data, and pushes the enriched catalog to the hub.
/// Every entry carries its local `book_id` so the hub-side cover GC
/// (ADR-033) can diff the catalog against the `covers/{node}/{id}.jpg`
/// files on disk. Books without ISBN are still included; the entry is
/// keyed by `book_id` alone in that case.
/// Local cover images are resized and uploaded as thumbnails (best-effort).
/// Returns the number of entries pushed.
Future<int> hubDirectorySyncCatalog() =>
    RustLib.instance.api.crateApiFrbHubDirectorySyncCatalog();

/// Browses the hub public directory.
///
/// ADR-035 Phase 2: `city_id` filters by GeoNames id (combinable with
/// `country` and `search`). Pass `None` to return all listed libraries.
Future<List<FrbHubProfile>> hubDirectoryList({
  required PlatformInt64 limit,
  required PlatformInt64 offset,
  String? country,
  String? search,
  PlatformInt64? cityId,
}) => RustLib.instance.api.crateApiFrbHubDirectoryList(
  limit: limit,
  offset: offset,
  country: country,
  search: search,
  cityId: cityId,
);

/// Gets a specific library profile from the hub directory.
Future<FrbHubProfile> hubDirectoryGetProfile({required String nodeId}) =>
    RustLib.instance.api.crateApiFrbHubDirectoryGetProfile(nodeId: nodeId);

/// Gets the catalog of a library (public or approved follow).
/// Fetches from hub, upserts into local cache, and returns entries with added_at.
/// If the hub fetch fails, returns the cached entries (offline-first).
Future<List<FrbCatalogEntry>> hubDirectoryGetCatalog({
  required String nodeId,
}) => RustLib.instance.api.crateApiFrbHubDirectoryGetCatalog(nodeId: nodeId);

/// Sends a follow request to a library.
Future<FrbHubFollow> hubDirectoryFollow({required String nodeId}) =>
    RustLib.instance.api.crateApiFrbHubDirectoryFollow(nodeId: nodeId);

/// Lists incoming follow requests pending approval.
Future<List<FrbHubFollow>> hubDirectoryPendingRequests() =>
    RustLib.instance.api.crateApiFrbHubDirectoryPendingRequests();

/// Resolves a pending follow request. resolution: "approve" | "reject" | "block"
/// When approving, encrypted_contact is an optional sealed blob of the owner's contact info.
Future<FrbHubFollow> hubDirectoryResolveFollow({
  required PlatformInt64 followId,
  required String resolution,
  String? encryptedContact,
}) => RustLib.instance.api.crateApiFrbHubDirectoryResolveFollow(
  followId: followId,
  resolution: resolution,
  encryptedContact: encryptedContact,
);

/// Lists libraries the local library is following (active follows).
Future<List<FrbHubFollow>> hubDirectoryListFollowing() =>
    RustLib.instance.api.crateApiFrbHubDirectoryListFollowing();

/// Lists libraries that follow the local library (active followers).
Future<List<FrbHubFollow>> hubDirectoryListFollowers() =>
    RustLib.instance.api.crateApiFrbHubDirectoryListFollowers();

/// Unfollows a library.
Future<void> hubDirectoryUnfollow({required String nodeId}) =>
    RustLib.instance.api.crateApiFrbHubDirectoryUnfollow(nodeId: nodeId);

/// Creates a hub-mediated borrow request for a book from a followed library.
Future<FrbHubBorrowRequest> hubDirectoryCreateBorrowRequest({
  required String lenderNodeId,
  required String isbn,
  required String bookTitle,
}) => RustLib.instance.api.crateApiFrbHubDirectoryCreateBorrowRequest(
  lenderNodeId: lenderNodeId,
  isbn: isbn,
  bookTitle: bookTitle,
);

/// Fetches incoming borrow requests (pending) for the local library as lender.
Future<List<FrbHubBorrowRequest>> hubDirectoryIncomingBorrowRequests() =>
    RustLib.instance.api.crateApiFrbHubDirectoryIncomingBorrowRequests();

/// Fetches outgoing borrow requests sent by the local library as requester.
Future<List<FrbHubBorrowRequest>> hubDirectoryOutgoingBorrowRequests() =>
    RustLib.instance.api.crateApiFrbHubDirectoryOutgoingBorrowRequests();

/// Resolves a borrow request. resolution: "accept" | "reject"
Future<FrbHubBorrowRequest> hubDirectoryResolveBorrowRequest({
  required PlatformInt64 requestId,
  required String resolution,
}) => RustLib.instance.api.crateApiFrbHubDirectoryResolveBorrowRequest(
  requestId: requestId,
  resolution: resolution,
);

/// Cancels a borrow request (requester only).
Future<void> hubDirectoryCancelBorrowRequest({
  required PlatformInt64 requestId,
}) => RustLib.instance.api.crateApiFrbHubDirectoryCancelBorrowRequest(
  requestId: requestId,
);

/// Encrypts plaintext for a recipient identified by their X25519 public key (hex-encoded).
/// Returns a base64-encoded sealed blob suitable for hub storage.
Future<String> sealBlob({
  required String recipientX25519Hex,
  required String plaintext,
}) => RustLib.instance.api.crateApiFrbSealBlob(
  recipientX25519Hex: recipientX25519Hex,
  plaintext: plaintext,
);

/// Decrypts a base64-encoded sealed blob using the local node identity's X25519 secret key.
/// Returns the plaintext string.
Future<String> openBlob({required String sealedBase64}) =>
    RustLib.instance.api.crateApiFrbOpenBlob(sealedBase64: sealedBase64);

/// Batch-updates encrypted contact blobs for all active followers.
/// contacts: list of (follow_id, encrypted_contact_base64) pairs.
Future<int> hubDirectorySyncContacts({
  required Int64List followIds,
  required List<String> encryptedContacts,
}) => RustLib.instance.api.crateApiFrbHubDirectorySyncContacts(
  followIds: followIds,
  encryptedContacts: encryptedContacts,
);

/// Returns the local X25519 public key as hex string, or None if no identity exists.
Future<String?> getLocalX25519PublicKey() =>
    RustLib.instance.api.crateApiFrbGetLocalX25519PublicKey();

/// Returns all collections with their book counts.
Future<List<FrbCollection>> getAllCollections() =>
    RustLib.instance.api.crateApiFrbGetAllCollections();

/// Returns a single collection by ID, or None if not found.
Future<FrbCollection?> getCollection({required String id}) =>
    RustLib.instance.api.crateApiFrbGetCollection(id: id);

/// Creates a new collection. Returns the created collection.
Future<FrbCollection> createCollection({
  required String name,
  String? description,
}) => RustLib.instance.api.crateApiFrbCreateCollection(
  name: name,
  description: description,
);

/// Deletes a collection by ID. Books are left orphaned (current behaviour).
Future<void> deleteCollection({required String id}) =>
    RustLib.instance.api.crateApiFrbDeleteCollection(id: id);

/// Returns how many books would be deleted / kept if the collection were
/// removed along with its books.
Future<FrbCollectionDeletionPreview> getCollectionDeletionPreview({
  required String id,
}) => RustLib.instance.api.crateApiFrbGetCollectionDeletionPreview(id: id);

/// Deletes a collection along with its eligible books (no loaned/borrowed
/// copy, not in another collection, on no shelf). Returns the IDs of books
/// that were actually removed.
Future<Int32List> deleteCollectionWithBooks({required String id}) =>
    RustLib.instance.api.crateApiFrbDeleteCollectionWithBooks(id: id);

/// Returns all books belonging to a collection.
Future<List<FrbCollectionBook>> getCollectionBooks({
  required String collectionId,
}) => RustLib.instance.api.crateApiFrbGetCollectionBooks(
  collectionId: collectionId,
);

/// Adds a book to a collection (idempotent).
Future<void> addBookToCollection({
  required String collectionId,
  required int bookId,
}) => RustLib.instance.api.crateApiFrbAddBookToCollection(
  collectionId: collectionId,
  bookId: bookId,
);

/// Removes a book from a collection.
Future<void> removeBookFromCollection({
  required String collectionId,
  required int bookId,
}) => RustLib.instance.api.crateApiFrbRemoveBookFromCollection(
  collectionId: collectionId,
  bookId: bookId,
);

/// Get library view statistics (peer and follower views).
/// Returns a JSON string with total_peer, total_follower, total, and daily breakdown.
Future<String> getLibraryViewStats() =>
    RustLib.instance.api.crateApiFrbGetLibraryViewStats();

/// Returns all collections a book belongs to.
Future<List<FrbCollection>> getBookCollections({required int bookId}) =>
    RustLib.instance.api.crateApiFrbGetBookCollections(bookId: bookId);

/// Replaces the set of collections a book belongs to.
Future<void> updateBookCollections({
  required int bookId,
  required List<String> collectionIds,
}) => RustLib.instance.api.crateApiFrbUpdateBookCollections(
  bookId: bookId,
  collectionIds: collectionIds,
);

/// List notifications, optionally filtered by category.
Future<List<FrbNotification>> notificationsList({
  String? category,
  required BigInt offset,
  required BigInt limit,
}) => RustLib.instance.api.crateApiFrbNotificationsList(
  category: category,
  offset: offset,
  limit: limit,
);

/// Get unread notification count (optionally by category).
Future<int> notificationsUnreadCount({String? category}) => RustLib.instance.api
    .crateApiFrbNotificationsUnreadCount(category: category);

/// Mark a single notification as read.
Future<bool> notificationsMarkRead({required int id}) =>
    RustLib.instance.api.crateApiFrbNotificationsMarkRead(id: id);

/// Mark all notifications as read.
Future<int> notificationsMarkAllRead() =>
    RustLib.instance.api.crateApiFrbNotificationsMarkAllRead();

/// Dismiss (hard delete) a single notification.
Future<bool> notificationsDismiss({required int id}) =>
    RustLib.instance.api.crateApiFrbNotificationsDismiss(id: id);

/// Dismiss (hard delete) all notifications. Returns count of deleted rows.
Future<int> notificationsDismissAll() =>
    RustLib.instance.api.crateApiFrbNotificationsDismissAll();

/// Run pruning (TTL + cap). Call on app startup.
Future<int> notificationsPrune() =>
    RustLib.instance.api.crateApiFrbNotificationsPrune();

/// Emit a one-time welcome notification after setup. Uses emit_unique
/// so it fires at most once per install (idempotent on re-call).
Future<void> emitWelcomeNotification() =>
    RustLib.instance.api.crateApiFrbEmitWelcomeNotification();

/// Get all notes for a book, ordered by creation date (newest first).
Future<List<FrbBookNote>> getBookNotes({required int bookId}) =>
    RustLib.instance.api.crateApiFrbGetBookNotes(bookId: bookId);

/// Create a new note for a book.
Future<FrbBookNote> createBookNote({
  required int bookId,
  required String content,
  int? page,
}) => RustLib.instance.api.crateApiFrbCreateBookNote(
  bookId: bookId,
  content: content,
  page: page,
);

/// Update an existing note.
Future<FrbBookNote> updateBookNote({
  required int id,
  required String content,
  int? page,
}) => RustLib.instance.api.crateApiFrbUpdateBookNote(
  id: id,
  content: content,
  page: page,
);

/// Delete a note by ID.
Future<void> deleteBookNote({required int id}) =>
    RustLib.instance.api.crateApiFrbDeleteBookNote(id: id);

/// Write a `.bgbackup` archive at `output_path` (ADR-037).
///
/// `unlock_kind` accepts `"recovery_code"` or `"passphrase"`. Any other
/// value yields an error before any heavy work runs.
///
/// `secret_bytes` carries the resolved passphrase or recovery code as raw
/// UTF-8 bytes. Crossing the FFI as `Uint8List` (rather than `String`)
/// lets the Flutter caller clear the buffer in place via
/// `fillRange(0, len, 0)` after the call returns; Dart `String` is
/// immutable and cannot be wiped reliably.
///
/// The Rust side wraps `secret_bytes` in `Zeroizing` so it is also
/// scrubbed on every return path (including panics) before write_backup
/// makes its own internal copy.
///
/// `include_identity = true` packs the Ed25519 + X25519 secret bytes in
/// `identity.bin` (Option C clone mode). The identity must already be
/// initialized via `init_identity_ffi`; otherwise the call returns an
/// error before any file is touched on disk.
///
/// `cover_dir` is the on-disk directory where local cover images live;
/// hub-hosted URLs are detected by their `http(s)://` prefix and skipped.
Future<FrbBackupSummary> writeBackupFfi({
  required String outputPath,
  required List<int> secretBytes,
  required String unlockKind,
  required String libraryUuid,
  required bool includeIdentity,
  required String prefsJson,
  required String coverDir,
}) => RustLib.instance.api.crateApiFrbWriteBackupFfi(
  outputPath: outputPath,
  secretBytes: secretBytes,
  unlockKind: unlockKind,
  libraryUuid: libraryUuid,
  includeIdentity: includeIdentity,
  prefsJson: prefsJson,
  coverDir: coverDir,
);

/// Parse `manifest.json` from a `.bgbackup` file without unlocking. Used by
/// the wizard preview step.
Future<FrbBackupManifestPreview> readManifestFfi({
  required String archivePath,
}) => RustLib.instance.api.crateApiFrbReadManifestFfi(archivePath: archivePath);

/// Restore a `.bgbackup` archive into the live DB.
///
/// `mode` accepts `"replace"` or `"merge"`. `restore_identity` is honoured
/// only in Replace mode AND when the archive carries `identity.bin`; ignored
/// otherwise.
///
/// **The Flutter caller MUST force-restart the app after this returns.** The
/// FFI's global SeaORM connection still holds open file descriptors on the
/// inode that was just renamed to the rollback sibling; reusing it is unsafe.
/// `db_path` and `cover_dir` are passed explicitly so the caller (which knows
/// its sandbox layout via `getApplicationSupportDirectory`) is the single
/// source of truth.
/// `local_library_uuid`: pass the device's current `library_uuid` so the
/// Replace path can detect a same-device restore and keep `crypto_keys`
/// intact (ADR-037 §5). `None` falls back to the cross-device behaviour
/// (wipe identity unless full clone-mode).
Future<FrbRestoreSummary> restoreBackupFfi({
  required String archivePath,
  required List<int> secretBytes,
  required String mode,
  required bool restoreIdentity,
  String? localLibraryUuid,
  required String dbPath,
  required String coverDir,
}) => RustLib.instance.api.crateApiFrbRestoreBackupFfi(
  archivePath: archivePath,
  secretBytes: secretBytes,
  mode: mode,
  restoreIdentity: restoreIdentity,
  localLibraryUuid: localLibraryUuid,
  dbPath: dbPath,
  coverDir: coverDir,
);

/// List rollback files available in the directory of `db_path`. Empty list
/// means no "Restore previous version" card should be shown.
Future<List<FrbRollbackInfo>> listAvailableRollbacksFfi({
  required String dbPath,
}) => RustLib.instance.api.crateApiFrbListAvailableRollbacksFfi(dbPath: dbPath);

/// Swap a rollback file back into the live DB. Same restart constraint as
/// `restore_backup_ffi`.
Future<void> restoreFromRollbackFfi({
  required String rollbackPath,
  required String dbPath,
}) => RustLib.instance.api.crateApiFrbRestoreFromRollbackFfi(
  rollbackPath: rollbackPath,
  dbPath: dbPath,
);

/// Watermark used by the Flutter `BackupSchedulerService` to skip a 24h tick
/// when no catalog change happened. Returns the highest `updated_at` across
/// `books`, `copies`, `loans`, `library_config`, or `None` for a fresh DB
/// (ADR-037 §6).
Future<String?> latestUserDataChangeAtFfi() =>
    RustLib.instance.api.crateApiFrbLatestUserDataChangeAtFfi();

/// Subset of the manifest surfaced to the wizard's preview screen. Mirrors
/// `ManifestSummary` field-by-field but flattened for FFI portability.
/// Counts cross the FFI as `i64`.
@freezed
sealed class FrbBackupManifestPreview with _$FrbBackupManifestPreview {
  const factory FrbBackupManifestPreview({
    required String formatVersion,
    required PlatformInt64 schemaVersion,
    required PlatformInt64 currentSchemaVersion,
    required String exportedAt,
    required String libraryUuid,
    required bool identityIncluded,
    required String unlockKind,
    required String appVersion,
    required PlatformInt64 booksCount,
    required PlatformInt64 copiesCount,
    required PlatformInt64 loansCount,
    required PlatformInt64 contactsCount,
    required PlatformInt64 authorsCount,
    required PlatformInt64 tagsCount,
    required PlatformInt64 collectionsCount,
    required PlatformInt64 peersCount,
    required PlatformInt64 salesCount,
    required PlatformInt64 coversCount,
    required String dbSha256,
  }) = _FrbBackupManifestPreview;
}

/// Summary of a successfully written `.bgbackup` archive, returned to the
/// Flutter caller. Counts and sizes are surfaced as `i64` for FFI
/// portability (Dart `int` is signed 64-bit on native).
@freezed
sealed class FrbBackupSummary with _$FrbBackupSummary {
  const factory FrbBackupSummary({
    required String archivePath,
    required PlatformInt64 archiveSizeBytes,
    required bool identityIncluded,
    required String exportedAt,
    required String libraryUuid,
    required PlatformInt64 schemaVersion,
    required String formatVersion,
    required PlatformInt64 booksCount,
    required PlatformInt64 copiesCount,
    required PlatformInt64 loansCount,
    required PlatformInt64 contactsCount,
    required PlatformInt64 authorsCount,
    required PlatformInt64 tagsCount,
    required PlatformInt64 collectionsCount,
    required PlatformInt64 peersCount,
    required PlatformInt64 salesCount,
    required PlatformInt64 coversCount,
    required String manifestJson,
  }) = _FrbBackupSummary;
}

/// Simplified book structure for FFI
@freezed
sealed class FrbBook with _$FrbBook {
  const factory FrbBook({
    int? id,
    required String title,
    String? author,
    String? isbn,
    String? summary,
    String? publisher,
    int? publicationYear,
    String? coverUrl,
    String? largeCoverUrl,
    String? readingStatus,
    int? shelfPosition,
    int? userRating,
    String? subjects,
    String? createdAt,
    String? updatedAt,
    String? finishedReadingAt,
    String? startedReadingAt,
    required bool owned,
    double? price,
    List<String>? digitalFormats,
    required bool private,
    int? pageCount,
    String? addedAt,
    String? hubCoverUploadFailedAt,
    String? uuid,
  }) = _FrbBook;
}

/// Metadata fetched from external sources for a book refresh.
/// Each field is optional - only non-null fields have data from the source.
@freezed
sealed class FrbBookMetadata with _$FrbBookMetadata {
  const factory FrbBookMetadata({
    String? title,
    String? author,
    String? publisher,
    String? publicationYear,
    String? coverUrl,
    String? summary,
    int? pageCount,
  }) = _FrbBookMetadata;
}

/// FFI-safe book note representation.
class FrbBookNote {
  final int id;
  final int bookId;
  final String content;
  final int? page;
  final String createdAt;
  final String updatedAt;

  const FrbBookNote({
    required this.id,
    required this.bookId,
    required this.content,
    this.page,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      bookId.hashCode ^
      content.hashCode ^
      page.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbBookNote &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          bookId == other.bookId &&
          content == other.content &&
          page == other.page &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// FFI-safe view of a peer catalog-change event.
///
/// Emitted when a peer sends a `catalog_changed` relay message, indicating
/// that they added or deleted a book. Flutter screens showing that peer's
/// library should trigger a re-sync on receipt.
///
/// Match by `peer_id` (local SQLite row ID) or `peer_library_uuid` (remote
/// UUID from the message payload). Both are provided so callers can use
/// whichever is available in their context.
@freezed
sealed class FrbCatalogChangedEvent with _$FrbCatalogChangedEvent {
  const factory FrbCatalogChangedEvent({
    required String peerLibraryUuid,
    required int peerId,
    required bool deltaApplied,
  }) = _FrbCatalogChangedEvent;
}

@freezed
sealed class FrbCatalogEntry with _$FrbCatalogEntry {
  const factory FrbCatalogEntry({
    required String isbn,
    required String title,
    String? author,
    String? coverUrl,
    String? addedAt,
  }) = _FrbCatalogEntry;
}

/// Collection data exposed to Flutter.
class FrbCollection {
  final String id;
  final String name;
  final String? description;
  final String source;
  final PlatformInt64 totalBooks;
  final PlatformInt64 ownedBooks;
  final String createdAt;
  final String updatedAt;

  const FrbCollection({
    required this.id,
    required this.name,
    this.description,
    required this.source,
    required this.totalBooks,
    required this.ownedBooks,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      source.hashCode ^
      totalBooks.hashCode ^
      ownedBooks.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbCollection &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          source == other.source &&
          totalBooks == other.totalBooks &&
          ownedBooks == other.ownedBooks &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// A book entry within a collection, exposed to Flutter.
class FrbCollectionBook {
  final int bookId;
  final String title;
  final String? author;
  final String? coverUrl;
  final String? publisher;
  final int? publicationYear;
  final String addedAt;
  final bool isOwned;
  final List<String>? digitalFormats;

  const FrbCollectionBook({
    required this.bookId,
    required this.title,
    this.author,
    this.coverUrl,
    this.publisher,
    this.publicationYear,
    required this.addedAt,
    required this.isOwned,
    this.digitalFormats,
  });

  @override
  int get hashCode =>
      bookId.hashCode ^
      title.hashCode ^
      author.hashCode ^
      coverUrl.hashCode ^
      publisher.hashCode ^
      publicationYear.hashCode ^
      addedAt.hashCode ^
      isOwned.hashCode ^
      digitalFormats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbCollectionBook &&
          runtimeType == other.runtimeType &&
          bookId == other.bookId &&
          title == other.title &&
          author == other.author &&
          coverUrl == other.coverUrl &&
          publisher == other.publisher &&
          publicationYear == other.publicationYear &&
          addedAt == other.addedAt &&
          isOwned == other.isOwned &&
          digitalFormats == other.digitalFormats;
}

/// Preview data for the "delete collection with its books" flow.
///
/// * `total_books` - books currently in the collection
/// * `to_delete` - books that would be deleted
/// * `to_keep` - books kept (loaned, borrowed, multi-collection, shelved)
class FrbCollectionDeletionPreview {
  final PlatformInt64 totalBooks;
  final PlatformInt64 toDelete;
  final PlatformInt64 toKeep;

  const FrbCollectionDeletionPreview({
    required this.totalBooks,
    required this.toDelete,
    required this.toKeep,
  });

  @override
  int get hashCode => totalBooks.hashCode ^ toDelete.hashCode ^ toKeep.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbCollectionDeletionPreview &&
          runtimeType == other.runtimeType &&
          totalBooks == other.totalBooks &&
          toDelete == other.toDelete &&
          toKeep == other.toKeep;
}

/// Library completeness snapshot over owned books.
@freezed
sealed class FrbCompletenessStats with _$FrbCompletenessStats {
  const factory FrbCompletenessStats({
    required PlatformInt64 ownedTotal,
    required PlatformInt64 complete,
    required PlatformInt64 incomplete,
    required PlatformInt64 noIsbn,
    required PlatformInt64 emptyFields,
  }) = _FrbCompletenessStats;
}

/// Simplified contact structure for FFI
@freezed
sealed class FrbContact with _$FrbContact {
  const factory FrbContact({
    int? id,
    required String contactType,
    required String name,
    String? firstName,
    String? email,
    String? phone,
    String? address,
    String? streetAddress,
    String? postalCode,
    String? city,
    String? country,
    double? latitude,
    double? longitude,
    String? notes,
    int? userId,
    int? libraryOwnerId,
    required bool isActive,
    String? uuid,
  }) = _FrbContact;
}

/// A cover candidate from an external source, for the multi-cover picker.
@freezed
sealed class FrbCoverCandidate with _$FrbCoverCandidate {
  const factory FrbCoverCandidate({
    required String url,
    required String source,
  }) = _FrbCoverCandidate;
}

@freezed
sealed class FrbDirectoryConfig with _$FrbDirectoryConfig {
  const factory FrbDirectoryConfig({
    required String nodeId,
    required bool isListed,
    required bool requiresApproval,
    required String acceptFrom,
    required bool allowBorrowing,
  }) = _FrbDirectoryConfig;
}

/// Discovered peer on local network (FFI-compatible)
@freezed
sealed class FrbDiscoveredPeer with _$FrbDiscoveredPeer {
  const factory FrbDiscoveredPeer({
    required String name,
    required String host,
    required int port,
    required List<String> addresses,
    String? libraryId,
    String? ed25519PublicKey,
    String? x25519PublicKey,
    required String discoveredAt,
  }) = _FrbDiscoveredPeer;
}

/// Live/last progress of a bulk fill run.
@freezed
sealed class FrbFillProgress with _$FrbFillProgress {
  const factory FrbFillProgress({
    required String batchId,
    required String status,
    required PlatformInt64 total,
    required PlatformInt64 done,
    required PlatformInt64 filled,
    required PlatformInt64 skipped,
    required PlatformInt64 errored,
    String? currentTitle,
  }) = _FrbFillProgress;
}

/// A recently-completed book with the fields the fill added to it.
@freezed
sealed class FrbFilledBook with _$FrbFilledBook {
  const factory FrbFilledBook({
    required int bookId,
    required String title,
    String? coverUrl,
    required List<FrbFilledField> fields,
  }) = _FrbFilledBook;
}

/// One field added to a book by the bulk fill, for the undo list.
@freezed
sealed class FrbFilledField with _$FrbFilledField {
  const factory FrbFilledField({
    required PlatformInt64 journalId,
    required String batchId,
    required String field,
    required String value,
  }) = _FrbFilledField;
}

/// Gamification config (FFI-safe)
class FrbGamificationConfig {
  final String achievementsStyle;
  final int readingGoalYearly;
  final int readingGoalProgress;
  final int totalBooksRead;

  const FrbGamificationConfig({
    required this.achievementsStyle,
    required this.readingGoalYearly,
    required this.readingGoalProgress,
    required this.totalBooksRead,
  });

  @override
  int get hashCode =>
      achievementsStyle.hashCode ^
      readingGoalYearly.hashCode ^
      readingGoalProgress.hashCode ^
      totalBooksRead.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbGamificationConfig &&
          runtimeType == other.runtimeType &&
          achievementsStyle == other.achievementsStyle &&
          readingGoalYearly == other.readingGoalYearly &&
          readingGoalProgress == other.readingGoalProgress &&
          totalBooksRead == other.totalBooksRead;
}

/// Full gamification status (FFI-safe)
class FrbGamificationStatus {
  final FrbTrackProgress collector;
  final FrbTrackProgress reader;
  final FrbTrackProgress lender;
  final FrbTrackProgress cataloguer;
  final FrbStreakInfo streak;
  final List<String> recentAchievements;
  final FrbGamificationConfig config;
  final String level;
  final PlatformInt64 loansCount;
  final PlatformInt64 editsCount;
  final double nextLevelProgress;
  final String badgeUrl;

  const FrbGamificationStatus({
    required this.collector,
    required this.reader,
    required this.lender,
    required this.cataloguer,
    required this.streak,
    required this.recentAchievements,
    required this.config,
    required this.level,
    required this.loansCount,
    required this.editsCount,
    required this.nextLevelProgress,
    required this.badgeUrl,
  });

  @override
  int get hashCode =>
      collector.hashCode ^
      reader.hashCode ^
      lender.hashCode ^
      cataloguer.hashCode ^
      streak.hashCode ^
      recentAchievements.hashCode ^
      config.hashCode ^
      level.hashCode ^
      loansCount.hashCode ^
      editsCount.hashCode ^
      nextLevelProgress.hashCode ^
      badgeUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbGamificationStatus &&
          runtimeType == other.runtimeType &&
          collector == other.collector &&
          reader == other.reader &&
          lender == other.lender &&
          cataloguer == other.cataloguer &&
          streak == other.streak &&
          recentAchievements == other.recentAchievements &&
          config == other.config &&
          level == other.level &&
          loansCount == other.loansCount &&
          editsCount == other.editsCount &&
          nextLevelProgress == other.nextLevelProgress &&
          badgeUrl == other.badgeUrl;
}

/// A character in the hangman display (FFI-safe)
class FrbHangmanChar {
  final String character;
  final String baseChar;
  final bool revealed;
  final bool isGuessable;

  const FrbHangmanChar({
    required this.character,
    required this.baseChar,
    required this.revealed,
    required this.isGuessable,
  });

  @override
  int get hashCode =>
      character.hashCode ^
      baseChar.hashCode ^
      revealed.hashCode ^
      isGuessable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbHangmanChar &&
          runtimeType == other.runtimeType &&
          character == other.character &&
          baseChar == other.baseChar &&
          revealed == other.revealed &&
          isGuessable == other.isGuessable;
}

/// A hangman leaderboard entry (FFI-safe)
class FrbHangmanLeaderboardEntry {
  final int peerId;
  final String libraryName;
  final double bestScore;
  final String difficulty;
  final String playedAt;
  final bool isSelf;

  const FrbHangmanLeaderboardEntry({
    required this.peerId,
    required this.libraryName,
    required this.bestScore,
    required this.difficulty,
    required this.playedAt,
    required this.isSelf,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      libraryName.hashCode ^
      bestScore.hashCode ^
      difficulty.hashCode ^
      playedAt.hashCode ^
      isSelf.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbHangmanLeaderboardEntry &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          libraryName == other.libraryName &&
          bestScore == other.bestScore &&
          difficulty == other.difficulty &&
          playedAt == other.playedAt &&
          isSelf == other.isSelf;
}

/// A saved hangman score (FFI-safe)
class FrbHangmanScore {
  final int? id;
  final String difficulty;
  final double elapsedSeconds;
  final int errors;
  final int hintsUsed;
  final bool won;
  final double normalizedScore;
  final String playedAt;

  /// Achievements unlocked after this game (empty if none)
  final List<String> newAchievements;

  const FrbHangmanScore({
    this.id,
    required this.difficulty,
    required this.elapsedSeconds,
    required this.errors,
    required this.hintsUsed,
    required this.won,
    required this.normalizedScore,
    required this.playedAt,
    required this.newAchievements,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      difficulty.hashCode ^
      elapsedSeconds.hashCode ^
      errors.hashCode ^
      hintsUsed.hashCode ^
      won.hashCode ^
      normalizedScore.hashCode ^
      playedAt.hashCode ^
      newAchievements.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbHangmanScore &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          difficulty == other.difficulty &&
          elapsedSeconds == other.elapsedSeconds &&
          errors == other.errors &&
          hintsUsed == other.hintsUsed &&
          won == other.won &&
          normalizedScore == other.normalizedScore &&
          playedAt == other.playedAt &&
          newAchievements == other.newAchievements;
}

/// Game setup returned to Flutter (FFI-safe)
class FrbHangmanSetup {
  final int bookId;
  final String title;
  final List<FrbHangmanChar> display;
  final String author;
  final String? coverUrl;
  final int maxErrors;
  final int hintsAvailable;
  final String difficulty;

  const FrbHangmanSetup({
    required this.bookId,
    required this.title,
    required this.display,
    required this.author,
    this.coverUrl,
    required this.maxErrors,
    required this.hintsAvailable,
    required this.difficulty,
  });

  @override
  int get hashCode =>
      bookId.hashCode ^
      title.hashCode ^
      display.hashCode ^
      author.hashCode ^
      coverUrl.hashCode ^
      maxErrors.hashCode ^
      hintsAvailable.hashCode ^
      difficulty.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbHangmanSetup &&
          runtimeType == other.runtimeType &&
          bookId == other.bookId &&
          title == other.title &&
          display == other.display &&
          author == other.author &&
          coverUrl == other.coverUrl &&
          maxErrors == other.maxErrors &&
          hintsAvailable == other.hintsAvailable &&
          difficulty == other.difficulty;
}

@freezed
sealed class FrbHubBorrowRequest with _$FrbHubBorrowRequest {
  const factory FrbHubBorrowRequest({
    required PlatformInt64 id,
    required String requesterNodeId,
    required String lenderNodeId,
    required String isbn,
    required String bookTitle,
    required String status,
    required String createdAt,
    String? resolvedAt,
    String? requesterDisplayName,
    String? lenderDisplayName,
  }) = _FrbHubBorrowRequest;
}

@freezed
sealed class FrbHubFollow with _$FrbHubFollow {
  const factory FrbHubFollow({
    required PlatformInt64 id,
    required String followerNodeId,
    required String followedNodeId,
    required String status,
    required String createdAt,
    String? resolvedAt,
    String? followerDisplayName,
    String? encryptedContact,
    String? followerX25519PublicKey,
  }) = _FrbHubFollow;
}

@freezed
sealed class FrbHubProfile with _$FrbHubProfile {
  const factory FrbHubProfile({
    required String nodeId,
    required String displayName,
    String? description,
    required int bookCount,
    String? locationCountry,
    PlatformInt64? locationCityId,
    required bool requiresApproval,
    bool? allowBorrowing,
    String? lastSeenAt,
    String? x25519PublicKey,
    String? website,
    String? deviceModel,
    String? deviceFingerprint,
    String? appVersion,
    String? avatarConfig,
  }) = _FrbHubProfile;
}

/// A book that could not be processed (no ISBN), for the manual-fix list.
@freezed
sealed class FrbIncompleteBook with _$FrbIncompleteBook {
  const factory FrbIncompleteBook({
    required int id,
    required String title,
    String? isbn,
  }) = _FrbIncompleteBook;
}

/// An incomplete owned book with the exact fields still empty, for the manual
/// "books to complete" overview.
@freezed
sealed class FrbIncompleteBookDetail with _$FrbIncompleteBookDetail {
  const factory FrbIncompleteBookDetail({
    required int id,
    required String title,
    String? isbn,
    String? coverUrl,
    required List<String> missing,
  }) = _FrbIncompleteBookDetail;
}

/// FFI-safe view of a leaderboard-change event.
///
/// Emitted when a peer sends a `public_stats_push` relay message, indicating
/// that they beat their personal best in a game or gained a gamification level.
/// Flutter providers showing network leaderboards should trigger a re-load
/// on receipt.
@freezed
sealed class FrbLeaderboardChangedEvent with _$FrbLeaderboardChangedEvent {
  const factory FrbLeaderboardChangedEvent({required int peerId}) =
      _FrbLeaderboardChangedEvent;
}

/// Leaderboard entry (FFI-safe)
class FrbLeaderboardEntry {
  final String libraryName;
  final int level;
  final PlatformInt64 current;
  final bool isSelf;
  final int? peerId;

  const FrbLeaderboardEntry({
    required this.libraryName,
    required this.level,
    required this.current,
    required this.isSelf,
    this.peerId,
  });

  @override
  int get hashCode =>
      libraryName.hashCode ^
      level.hashCode ^
      current.hashCode ^
      isSelf.hashCode ^
      peerId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbLeaderboardEntry &&
          runtimeType == other.runtimeType &&
          libraryName == other.libraryName &&
          level == other.level &&
          current == other.current &&
          isSelf == other.isSelf &&
          peerId == other.peerId;
}

/// Full leaderboard response (FFI-safe)
class FrbLeaderboardResponse {
  final List<FrbLeaderboardEntry> collector;
  final List<FrbLeaderboardEntry> reader;
  final List<FrbLeaderboardEntry> lender;
  final List<FrbLeaderboardEntry> cataloguer;
  final String? lastRefreshed;

  const FrbLeaderboardResponse({
    required this.collector,
    required this.reader,
    required this.lender,
    required this.cataloguer,
    this.lastRefreshed,
  });

  @override
  int get hashCode =>
      collector.hashCode ^
      reader.hashCode ^
      lender.hashCode ^
      cataloguer.hashCode ^
      lastRefreshed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbLeaderboardResponse &&
          runtimeType == other.runtimeType &&
          collector == other.collector &&
          reader == other.reader &&
          lender == other.lender &&
          cataloguer == other.cataloguer &&
          lastRefreshed == other.lastRefreshed;
}

/// Simplified loan structure for FFI
@freezed
sealed class FrbLoan with _$FrbLoan {
  const factory FrbLoan({
    required int id,
    required int copyId,
    required int contactId,
    required int libraryId,
    required String loanDate,
    required String dueDate,
    String? returnDate,
    required String status,
    String? notes,
    required String contactName,
    required String bookTitle,
    int? bookId,
    String? coverUrl,
    String? isbn,
    String? uuid,
  }) = _FrbLoan;
}

/// Loan settings for FFI
@freezed
sealed class FrbLoanSettings with _$FrbLoanSettings {
  const factory FrbLoanSettings({
    required int defaultLoanDurationDays,
    required bool perBookDurationEnabled,
    required int reminderDaysBeforeDue,
  }) = _FrbLoanSettings;
}

/// A card in the memory game (FFI-safe)
class FrbMemoryCard {
  final int bookId;
  final String title;
  final String coverUrl;

  const FrbMemoryCard({
    required this.bookId,
    required this.title,
    required this.coverUrl,
  });

  @override
  int get hashCode => bookId.hashCode ^ title.hashCode ^ coverUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbMemoryCard &&
          runtimeType == other.runtimeType &&
          bookId == other.bookId &&
          title == other.title &&
          coverUrl == other.coverUrl;
}

/// A leaderboard entry (FFI-safe)
class FrbMemoryLeaderboardEntry {
  final int peerId;
  final String libraryName;
  final double bestScore;
  final String difficulty;
  final String playedAt;

  /// True if this entry is the local user (not a peer)
  final bool isSelf;

  const FrbMemoryLeaderboardEntry({
    required this.peerId,
    required this.libraryName,
    required this.bestScore,
    required this.difficulty,
    required this.playedAt,
    required this.isSelf,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      libraryName.hashCode ^
      bestScore.hashCode ^
      difficulty.hashCode ^
      playedAt.hashCode ^
      isSelf.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbMemoryLeaderboardEntry &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          libraryName == other.libraryName &&
          bestScore == other.bestScore &&
          difficulty == other.difficulty &&
          playedAt == other.playedAt &&
          isSelf == other.isSelf;
}

/// A saved memory game score (FFI-safe)
class FrbMemoryScore {
  final int? id;
  final String difficulty;
  final int pairsCount;
  final double elapsedSeconds;
  final int errors;
  final double normalizedScore;
  final String playedAt;

  /// Achievements unlocked after this game (empty if none)
  final List<String> newAchievements;

  const FrbMemoryScore({
    this.id,
    required this.difficulty,
    required this.pairsCount,
    required this.elapsedSeconds,
    required this.errors,
    required this.normalizedScore,
    required this.playedAt,
    required this.newAchievements,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      difficulty.hashCode ^
      pairsCount.hashCode ^
      elapsedSeconds.hashCode ^
      errors.hashCode ^
      normalizedScore.hashCode ^
      playedAt.hashCode ^
      newAchievements.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbMemoryScore &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          difficulty == other.difficulty &&
          pairsCount == other.pairsCount &&
          elapsedSeconds == other.elapsedSeconds &&
          errors == other.errors &&
          normalizedScore == other.normalizedScore &&
          playedAt == other.playedAt &&
          newAchievements == other.newAchievements;
}

class FrbNotification {
  final int id;
  final String eventType;
  final String category;
  final String title;
  final String? body;
  final String? refType;
  final String? refId;
  final String? readAt;
  final String createdAt;

  const FrbNotification({
    required this.id,
    required this.eventType,
    required this.category,
    required this.title,
    this.body,
    this.refType,
    this.refId,
    this.readAt,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      eventType.hashCode ^
      category.hashCode ^
      title.hashCode ^
      body.hashCode ^
      refType.hashCode ^
      refId.hashCode ^
      readAt.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbNotification &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          eventType == other.eventType &&
          category == other.category &&
          title == other.title &&
          body == other.body &&
          refType == other.refType &&
          refId == other.refId &&
          readAt == other.readAt &&
          createdAt == other.createdAt;
}

/// FFI-safe view of a relay nudge event.
///
/// `source` is one of: "websocket" (instant nudge), "polling" (fallback timer),
/// "manual" (user-triggered or peer.rs request-response).
@freezed
sealed class FrbNudgeEvent with _$FrbNudgeEvent {
  const factory FrbNudgeEvent({
    required String mailboxId,
    required String source,
  }) = _FrbNudgeEvent;
}

@freezed
sealed class FrbOperationLogEntry with _$FrbOperationLogEntry {
  const factory FrbOperationLogEntry({
    required int id,
    required String entityType,
    required int entityId,
    required String operation,
    String? payload,
    required String status,
    String? errorMessage,
    required bool pinned,
    required String createdAt,
  }) = _FrbOperationLogEntry;
}

@freezed
sealed class FrbOperationLogStats with _$FrbOperationLogStats {
  const factory FrbOperationLogStats({
    required BigInt total,
    required BigInt today,
    required BigInt pending,
    required BigInt failed,
  }) = _FrbOperationLogStats;
}

/// FFI-safe view of a peer profile-change event.
///
/// Emitted when a peer sends a `profile_changed` relay message after they
/// edit their avatar (or, in the future, another profile field). Flutter
/// should call `try_peer_avatar_pull(peer_id)` on receipt to fetch the
/// fresh values over E2EE and update the local `peers` row.
@freezed
sealed class FrbProfileChangedEvent with _$FrbProfileChangedEvent {
  const factory FrbProfileChangedEvent({
    required int peerId,
    required List<String> changed,
  }) = _FrbProfileChangedEvent;
}

/// A generated puzzle board (FFI-safe)
class FrbPuzzleBoard {
  final int bookId;
  final String title;
  final String coverUrl;
  final int gridSize;
  final Uint8List tiles;
  final int emptyIndex;
  final int parMoves;

  const FrbPuzzleBoard({
    required this.bookId,
    required this.title,
    required this.coverUrl,
    required this.gridSize,
    required this.tiles,
    required this.emptyIndex,
    required this.parMoves,
  });

  @override
  int get hashCode =>
      bookId.hashCode ^
      title.hashCode ^
      coverUrl.hashCode ^
      gridSize.hashCode ^
      tiles.hashCode ^
      emptyIndex.hashCode ^
      parMoves.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbPuzzleBoard &&
          runtimeType == other.runtimeType &&
          bookId == other.bookId &&
          title == other.title &&
          coverUrl == other.coverUrl &&
          gridSize == other.gridSize &&
          tiles == other.tiles &&
          emptyIndex == other.emptyIndex &&
          parMoves == other.parMoves;
}

/// A leaderboard entry for the sliding puzzle (FFI-safe)
class FrbPuzzleLeaderboardEntry {
  final int peerId;
  final String libraryName;
  final double bestScore;
  final String difficulty;
  final String playedAt;
  final bool isSelf;

  const FrbPuzzleLeaderboardEntry({
    required this.peerId,
    required this.libraryName,
    required this.bestScore,
    required this.difficulty,
    required this.playedAt,
    required this.isSelf,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      libraryName.hashCode ^
      bestScore.hashCode ^
      difficulty.hashCode ^
      playedAt.hashCode ^
      isSelf.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbPuzzleLeaderboardEntry &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          libraryName == other.libraryName &&
          bestScore == other.bestScore &&
          difficulty == other.difficulty &&
          playedAt == other.playedAt &&
          isSelf == other.isSelf;
}

/// A saved sliding puzzle score (FFI-safe)
class FrbPuzzleScore {
  final int? id;
  final String difficulty;
  final int gridSize;
  final double elapsedSeconds;
  final int moveCount;
  final int parMoves;
  final double normalizedScore;
  final String playedAt;

  /// Achievements unlocked after this game (empty if none)
  final List<String> newAchievements;

  const FrbPuzzleScore({
    this.id,
    required this.difficulty,
    required this.gridSize,
    required this.elapsedSeconds,
    required this.moveCount,
    required this.parMoves,
    required this.normalizedScore,
    required this.playedAt,
    required this.newAchievements,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      difficulty.hashCode ^
      gridSize.hashCode ^
      elapsedSeconds.hashCode ^
      moveCount.hashCode ^
      parMoves.hashCode ^
      normalizedScore.hashCode ^
      playedAt.hashCode ^
      newAchievements.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbPuzzleScore &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          difficulty == other.difficulty &&
          gridSize == other.gridSize &&
          elapsedSeconds == other.elapsedSeconds &&
          moveCount == other.moveCount &&
          parMoves == other.parMoves &&
          normalizedScore == other.normalizedScore &&
          playedAt == other.playedAt &&
          newAchievements == other.newAchievements;
}

@freezed
sealed class FrbRegisterParams with _$FrbRegisterParams {
  const factory FrbRegisterParams({
    required String nodeId,
    required String displayName,
    required int bookCount,
    required bool isListed,
    required bool requiresApproval,
    required String acceptFrom,
    String? description,
    String? locationCountry,
    PlatformInt64? locationCityId,
    required bool allowBorrowing,
    String? x25519PublicKey,
    String? website,
    String? deviceModel,
    String? deviceFingerprint,
    String? appVersion,
    String? relayUrl,
    String? relayMailboxId,
    String? relayWriteToken,
    String? avatarConfig,
  }) = _FrbRegisterParams;
}

/// Relay config exposed via FFI. Excludes read_token (S2).
@freezed
sealed class FrbRelayConfig with _$FrbRelayConfig {
  const factory FrbRelayConfig({
    required String relayUrl,
    required String mailboxUuid,
    required String writeToken,
  }) = _FrbRelayConfig;
}

/// Outcome of a successful restore returned to the wizard.
@freezed
sealed class FrbRestoreSummary with _$FrbRestoreSummary {
  const factory FrbRestoreSummary({
    required String mode,
    required bool identityRestored,
    required bool sameDevice,
    String? restoredLibraryUuid,
    required String libraryUuidAction,
    required String prefsJson,
    String? rollbackPath,
    required PlatformInt64 booksAfter,
    required PlatformInt64 copiesAfter,
    required PlatformInt64 contactsAfter,
    required PlatformInt64 coversRestored,
  }) = _FrbRestoreSummary;
}

/// Available rollback file presented in the "Restore previous version" UI.
@freezed
sealed class FrbRollbackInfo with _$FrbRollbackInfo {
  const factory FrbRollbackInfo({
    required String path,
    required String createdAt,
    required PlatformInt64 ageSeconds,
    required PlatformInt64 sizeBytes,
  }) = _FrbRollbackInfo;
}

/// Search-related settings persisted in the installation profile.
///
/// Mirrors the `fallback_preferences` and `api_keys` fields the Flutter
/// settings screen expects under `_userStatus['config']`. The legacy
/// `gamification_get_status` payload (returned by `getUserStatus` in FFI
/// mode) does not carry these fields, hence this dedicated accessor.
class FrbSearchSettings {
  /// Per-provider toggles. Only entries the user explicitly toggled away
  /// from the implicit defaults are populated, so the client's `?? default`
  /// fallbacks (e.g. `bnfDefault = isFrench`) keep applying for untouched
  /// providers — preventing UI regressions on the BNF locale heuristic.
  ///
  /// Mapping (inverse of `api/profile.rs::update_profile`):
  /// - `enable_google_books` in modules → `google_books: true`
  /// - `disable_fallback:<provider>` in modules → `<provider>: false`
  final Map<String, bool> fallbackPreferences;

  /// API keys stored in `installation_profile.api_keys`
  /// (e.g. `{"google_books": "AIza..."}`).
  final Map<String, String> apiKeys;

  const FrbSearchSettings({
    required this.fallbackPreferences,
    required this.apiKeys,
  });

  @override
  int get hashCode => fallbackPreferences.hashCode ^ apiKeys.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbSearchSettings &&
          runtimeType == other.runtimeType &&
          fallbackPreferences == other.fallbackPreferences &&
          apiKeys == other.apiKeys;
}

/// Streak info (FFI-safe)
class FrbStreakInfo {
  final int current;
  final int longest;

  const FrbStreakInfo({required this.current, required this.longest});

  @override
  int get hashCode => current.hashCode ^ longest.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbStreakInfo &&
          runtimeType == other.runtimeType &&
          current == other.current &&
          longest == other.longest;
}

/// Simplified tag structure for FFI
@freezed
sealed class FrbTag with _$FrbTag {
  const factory FrbTag({
    required int id,
    required String name,
    int? parentId,
    required PlatformInt64 count,
    String? uuid,
  }) = _FrbTag;
}

/// Track progress (FFI-safe)
class FrbTrackProgress {
  final int level;
  final double progress;
  final PlatformInt64 current;
  final int nextThreshold;

  const FrbTrackProgress({
    required this.level,
    required this.progress,
    required this.current,
    required this.nextThreshold,
  });

  @override
  int get hashCode =>
      level.hashCode ^
      progress.hashCode ^
      current.hashCode ^
      nextThreshold.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbTrackProgress &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          progress == other.progress &&
          current == other.current &&
          nextThreshold == other.nextThreshold;
}
