#!/usr/bin/env dart
/// Patches .po files with missing translations.
/// Usage: dart tools/patch_po.dart

import 'dart:io';

void main() {
  patchFile('assets/i18n/en.po', enMissing);
  patchFile('assets/i18n/fr.po', frMissing);
  patchFile('assets/i18n/es.po', esMissing);
  patchFile('assets/i18n/de.po', deMissing);
  print('Done patching all .po files.');
}

/// Reads a .po file, fills in empty msgstr for keys in [translations], writes back.
void patchFile(String path, Map<String, String> translations) {
  final file = File(path);
  final lines = file.readAsStringSync().split('\n');
  final output = <String>[];
  int patched = 0;

  String? currentMsgId;

  for (int i = 0; i < lines.length; i++) {
    final line = lines[i];
    final trimmed = line.trim();

    if (trimmed.startsWith('msgid "') && trimmed.endsWith('"')) {
      currentMsgId = trimmed.substring(7, trimmed.length - 1);
      output.add(line);
    } else if (trimmed.startsWith('msgstr "') && trimmed.endsWith('"')) {
      final currentMsgStr = trimmed.substring(8, trimmed.length - 1);
      if (currentMsgStr.isEmpty &&
          currentMsgId != null &&
          translations.containsKey(currentMsgId)) {
        final escaped = escapePo(translations[currentMsgId]!);
        output.add('msgstr "$escaped"');
        patched++;
      } else {
        output.add(line);
      }
      currentMsgId = null;
    } else {
      output.add(line);
    }
  }

  file.writeAsStringSync(output.join('\n'));
  print('  $path: $patched entries patched');
}

String escapePo(String s) {
  return s
      .replaceAll('\\', '\\\\')
      .replaceAll('"', '\\"')
      .replaceAll('\n', '\\n')
      .replaceAll('\t', '\\t');
}

// ─── EN missing translations ───
const enMissing = <String, String>{
  'action_share': 'Share',
  'add_tag': 'Add',
  'badge_collection': 'Badge Collection',
  'create_new_tag': 'Create New Shelf',
  'currency_label': 'Currency',
  'done': 'Done',
  'error_creating_collection': 'Error creating collection',
  'existing_tags_section': 'Existing Shelves',
  'link_device_enter_code': 'Enter Code',
  'link_device_scan_or_type': 'Scan or type the pairing code',
  'link_device_verify': 'Verify',
  'no_available_copies': 'No available copies',
  'no_existing_tags': 'No shelves created yet. Start by creating one!',
  'onboarding_finish': "Let's go!",
  'onboarding_slogan_1': 'Your universal library, right in your pocket.',
  'onboarding_slogan_2': 'Add books by scanning barcodes or searching online.',
  'onboarding_slogan_3': 'Connect your knowledge. Share your worlds.',
  'onboarding_slogan_4': 'Visualize your passion. Measure your erudition.',
  'onboarding_tap_continue': 'Tap anywhere to continue',
  'record_sale_title': 'Record a Sale',
  'root_tag': 'Root (no parent)',
  'sale_date': 'Sale Date',
  'sale_notes': 'Notes (optional)',
  'sale_recorded': 'Sale recorded successfully',
  'saving_changes': 'Saving changes...',
  'select_book': 'Select a Book',
  'select_copy': 'Select a Copy',
  'select_currency': 'Select Currency',
  'select_parent_optional': 'Parent (optional)',
  'select_tags_title': 'Manage Shelves',
  'tab_members': 'Members',
  'tag_created_success': 'Shelf created: ',
  'tag_creation_error': 'Error creating shelf',
  'tag_name_hint': 'Shelf name',
  'tags_label': 'Shelves',
};

// ─── FR missing translations ───
const frMissing = <String, String>{
  'add_to_collection': 'Ajouter à la collection',
  'all_copies_lent': 'Tous les exemplaires sont actuellement prêtés.',
  'book_deleted': 'Livre supprimé',
  'collection_details': 'Détails de la collection',
  'content': 'Contenu',
  'copies_explanation':
      "Les exemplaires permettent de suivre plusieurs copies physiques du même livre. Utile pour les bibliothèques avec plusieurs copies pouvant être prêtées à différentes personnes.",
  'copies_title': 'Exemplaires de',
  'copy_number': 'Exemplaire n°',
  'delete_collection': 'Supprimer la collection',
  'delete_collection_confirm':
      'Êtes-vous sûr de vouloir supprimer cette collection ?',
  'edit_profile_title': 'Modifier le profil',
  'import_error': "Erreur lors de l'importation",
  'import_file': 'Importer un fichier',
  'library_name_label': 'Nom de la bibliothèque',
  'link_device_enter_code': 'Entrer le code',
  'link_device_scan_or_type': "Scanner ou saisir le code d'appairage",
  'link_device_verify': 'Vérifier',
  'no_copies': 'Aucun exemplaire trouvé',
  'owned_vs_total': 'Possédés / Total',
  'record_sale': 'Enregistrer une vente',
  'sales': 'Ventes',
  'saving_changes': 'Enregistrement en cours...',
  'status': 'Statut',
  'sync_collection': 'Synchroniser les prix',
  'sync_success': 'Prix synchronisés',
  'username_label': "Nom d'utilisateur",
  'wizard_books_view_desc':
      "Basculez entre la vue grille (étagère) et la vue liste.",
  'wizard_contacts_add_desc':
      'Ajoutez des amis ou des emprunteurs pour partager des livres.',
  'wizard_contacts_add_title': 'Ajouter un contact',
  'wizard_contacts_filter_desc':
      'Filtrez par Emprunteurs (local) ou Bibliothèques (P2P).',
  'wizard_contacts_filter_title': 'Filtrer les contacts',
};

// ─── ES missing translations ───
const esMissing = <String, String>{
  'achievement_collector_bronze': 'Coleccionista Bronce',
  'achievement_collector_silver': 'Coleccionista Plata',
  'achievement_first_book': 'Primer Libro',
  'achievement_first_loan': 'Generoso',
  'achievement_first_scan': 'Scanner Pro',
  'achievement_reader_bronze': 'Lector Ávido',
  'achievement_streak_3': 'Regular',
  'achievement_streak_7': 'Semana Perfecta',
  'action_scan_barcode': 'Escanear código de barras',
  'action_search_online': 'Buscar en línea',
  'action_share': 'Compartir',
  'add_book_button': 'Añadir libro',
  'add_book_manually': 'Añadir manualmente',
  'add_collection': 'Añadir colección',
  'add_contact': 'Añadir contacto',
  'add_contact_or_scan_help': 'Añada un contacto o escanee su código QR',
  'add_copy': 'Añadir ejemplar',
  'add_copy_hint': 'Añada un nuevo ejemplar de este libro',
  'add_first_book_in_shelf': 'Añade tu primer libro a esta estantería',
  'add_first_contact': 'Añadir primer contacto',
  'add_sub_shelf': 'Añadir sub-estantería',
  'add_tag': 'Añadir',
  'add_tags': 'Añadir etiquetas',
  'add_to_collection': 'Añadir a la colección',
  'add_to_collections_label': 'Añadir a colecciones',
  'add_to_library': 'Añadir a la biblioteca',
  'added_date_label': 'Fecha de adición',
  'advanced_filters': 'Filtros avanzados',
  'all_shelves': 'Todas las estanterías',
  'all_sources': 'Todas las fuentes',
  'allow_library_caching': 'Permitir caché de biblioteca',
  'allow_library_caching_desc':
      'Permite a tus amigos guardar una copia local de tu biblioteca',
  'anim_achievement_pop': 'Pop de logro',
  'anim_achievement_pop_desc': 'Animación al desbloquear un logro',
  'anim_badge_unlock': 'Desbloqueo de insignia',
  'anim_badge_unlock_desc': 'Animación al obtener una nueva insignia',
  'anim_book_complete': 'Libro completado',
  'anim_book_complete_desc': 'Animación al terminar un libro',
  'anim_gamification_title': 'Animaciones de gamificación',
  'anim_goal_reached': 'Objetivo alcanzado',
  'anim_goal_reached_desc': 'Animación al alcanzar un objetivo de lectura',
  'anim_level_up': 'Subida de nivel',
  'anim_level_up_desc': 'Animación al subir de nivel',
  'anim_play_sequence': 'Reproducir secuencia',
  'anim_plus_one': '+1',
  'anim_plus_one_desc': 'Animación +1 al añadir un libro',
  'anim_tap_to_test': 'Toca para probar',
  'api_key_saved': 'Clave API guardada',
  'ask_genie': 'Preguntar al Genio',
  'audio_module': 'Módulo de audio',
  'audio_module_desc': 'Escucha audiolibros de tu biblioteca',
  'availability_available': 'Disponible',
  'availability_borrowed': 'Prestado',
  'availability_label': 'Disponibilidad',
  'availability_loaned': 'Prestado',
  'availability_lost': 'Perdido',
  'availability_wanted': 'Deseado',
  'avatar_robot': 'Robot',
  'average_price': 'Precio medio',
  'avg_duration': 'Duración media',
  'back_to_all': 'Volver a todos',
  'backup_reminder_export': 'Exportar ahora',
  'backup_reminder_later': 'Más tarde',
  'backup_reminder_message':
      'Hace tiempo que no haces una copia de seguridad. Protege tus datos exportando una copia.',
  'backup_reminder_tip': 'Consejo: exporta regularmente para no perder datos',
  'backup_reminder_title': 'Copia de seguridad recomendada',
  'badge_collection': 'Colección de insignias',
  'badge_desc_bibliophile': 'Apasionado de los libros',
  'badge_desc_curieux': 'Explorador curioso',
  'badge_desc_erudit': 'Erudito del saber',
  'badge_desc_initie': 'Iniciado en la lectura',
  'badge_levels_title': 'Niveles de insignias',
  'badge_progress_info': 'Progreso de insignias',
  'batch_scan_desc': 'Escanea varios libros seguidos',
  'batch_scan_title': 'Escaneo por lotes',
  'best_streak': 'Mejor racha',
  'book_borrowed_from': 'Libro prestado de',
  'book_borrowed_success': 'Libro prestado con éxito',
  'book_found': 'Libro encontrado',
  'book_given_back': 'Libro devuelto',
  'book_not_found': 'Libro no encontrado',
  'book_price': 'Precio del libro',
  'book_returned': 'Libro devuelto',
  'books_added': 'Libros añadidos',
  'books_borrowed': 'Libros prestados',
  'books_imported': 'Libros importados',
  'books_in_collections': 'Libros en colecciones',
  'books_in_shelves': 'Libros en estanterías',
  'bookseller': 'Librero',
  'borrow_book_title': 'Tomar prestado un libro',
  'borrow_btn': 'Tomar prestado',
  'borrow_from_contact': 'Tomar prestado de un contacto',
  'borrow_from_contact_btn': 'Tomar prestado de',
  'borrowed': 'Prestado',
  'borrowed_books_list': 'Lista de libros prestados',
  'borrowed_from_label': 'Prestado de',
  'borrowed_statistics': 'Estadísticas de préstamos recibidos',
  'borrowed_status': 'Prestado',
  'borrowing_from': 'Prestado de',
  'browse_shelf': 'Explorar estantería',
  'btn_enter_manually': 'Introducir manualmente',
  'btn_scan_book': 'Escanear libro',
  'btn_search_book_online': 'Buscar libro en línea',
  'btn_search_online_cta': 'Buscar en catálogos en línea',
  'camera_error': 'Error de cámara',
  'camera_loading': 'Cargando cámara...',
  'change_password': 'Cambiar contraseña',
  'clear': 'Borrar',
  'close': 'Cerrar',
  'code_label': 'Código',
  'collection_details': 'Detalles de la colección',
  'collection_name_hint': 'Nombre de la colección',
  'collection_statistics': 'Estadísticas de colecciones',
  'collections': 'Colecciones',
  'collections_label': 'Colecciones',
  'commerce_module_label': 'Módulo comercio',
  'commerce_module_subtitle': 'Gestiona ventas y precios',
  'confirm_borrow': 'Confirmar préstamo',
  'confirm_delete': 'Confirmar eliminación',
  'confirm_password': 'Confirmar contraseña',
  'confirm_sale': 'Confirmar venta',
  'connection_pending_approval': 'Conexión pendiente de aprobación',
  'connection_request_awaiting': 'Solicitud de conexión en espera',
  'connection_validation': 'Validación de conexión',
  'connection_validation_desc':
      'Acepta o rechaza las solicitudes de conexión entrantes',
  'contact_first_name_hint': 'Nombre',
  'contact_first_name_label': 'Nombre',
  'contact_type_borrower': 'Prestatario',
  'contact_type_lender': 'Prestamista',
  'content': 'Contenido',
  'continue_reading': 'Continuar leyendo',
  'copy_added': 'Ejemplar añadido',
  'copy_label': 'Ejemplar',
  'copy_price': 'Precio del ejemplar',
  'cover_add': 'Añadir portada',
  'cover_change': 'Cambiar portada',
  'cover_choose_file': 'Elegir archivo',
  'cover_confirm_use': '¿Usar esta portada?',
  'cover_found': 'Portada encontrada',
  'cover_found_by_title': 'Portada encontrada por título',
  'cover_no_isbn': 'Sin ISBN para buscar portada',
  'cover_not_found': 'Portada no encontrada',
  'cover_pick_title': 'Elegir portada',
  'cover_remove': 'Eliminar portada',
  'cover_removed': 'Portada eliminada',
  'cover_search_online': 'Buscar portada en línea',
  'cover_searching': 'Buscando portada...',
  'cover_searching_by_title': 'Buscando portada por título...',
  'cover_updated': 'Portada actualizada',
  'cover_use_button': 'Usar esta portada',
  'create': 'Crear',
  'create_collection': 'Crear colección',
  'create_collection_hint': 'Nombre de la nueva colección',
  'create_first_shelf': 'Crear primera estantería',
  'create_new_collection': 'Crear nueva colección',
  'create_new_tag': 'Crear nueva estantería',
  'create_shelf': 'Crear estantería',
  'currency_label': 'Divisa',
  'current': 'Actual',
  'current_password': 'Contraseña actual',
  'current_streak': 'Racha actual',
  'date_select_option_none': 'Sin fecha',
  'date_select_option_pick': 'Elegir fecha',
  'date_select_option_today': 'Hoy',
  'date_select_title': 'Seleccionar fecha',
  'delete': 'Eliminar',
  'delete_collection': 'Eliminar colección',
  'delete_collection_confirm': '¿Está seguro de que desea eliminar esta colección?',
  'delete_shelf': 'Eliminar estantería',
  'delete_shelf_warning': 'Esta acción no se puede deshacer',
  'delete_with_children_warning':
      'Esta estantería contiene sub-estanterías que también serán eliminadas',
  'digital_formats_label': 'Formatos digitales',
  'disable': 'Desactivar',
  'discover': 'Descubrir',
  'discover_collections_subtitle': 'Explore listas curadas de libros',
  'discover_collections_title': 'Descubrir colecciones',
  'displayed_books_count': '{count} libro mostrado',
  'displayed_books_count_plural': '{count} libros mostrados',
  'displayed_collections_count': '{count} colección mostrada',
  'displayed_collections_count_plural': '{count} colecciones mostradas',
  'displayed_shelves_count': '{count} estantería mostrada',
  'displayed_shelves_count_plural': '{count} estanterías mostradas',
  'done': 'Hecho',
  'due_date_label': 'Fecha de devolución',
  'edit': 'Editar',
  'edit_shelf': 'Editar estantería',
  'editions': 'Ediciones',
  'email_label': 'Correo electrónico',
  'empty_collection': 'Colección vacía',
  'empty_library_subtitle': 'Añade tu primer libro para empezar',
  'empty_library_title': 'Tu biblioteca está vacía',
  'enable': 'Activar',
  'enable_network_discovery': 'Activar descubrimiento en red',
  'enter_isbn_manually': 'Introducir ISBN manualmente',
  'enter_library_name': 'Introduce el nombre de la biblioteca',
  'enter_manually': 'Introducir manualmente',
  'enter_password_to_reset': 'Introduce la contraseña para reiniciar',
  'enter_sale_price': 'Introduce el precio de venta',
  'enter_username': 'Introduce el nombre de usuario',
  'error_409_conflict': 'Conflicto: el recurso ya existe',
  'error_creating_collection': 'Error al crear la colección',
  'error_fetching_isbn': 'Error al buscar ISBN',
  'error_giving_back_book': 'Error al devolver el libro',
  'error_no_available_copies': 'No hay ejemplares disponibles',
  'error_peer_offline': 'El par está desconectado',
  'error_peer_timeout': 'Tiempo de espera del par agotado',
  'error_returning_book': 'Error al devolver el libro',
  'existing_tags_section': 'Estanterías existentes',
  'explore_collections': 'Explorar colecciones',
  'external_search_empty_hint': 'Busca libros en catálogos externos',
  'feature_borrow': 'Tomar prestado',
  'feature_connect': 'Conectar',
  'feature_discover': 'Descubrir',
  'feature_goals': 'Objetivos',
  'feature_history': 'Historial',
  'feature_manual': 'Manual',
  'feature_organize': 'Organizar',
  'feature_scan': 'Escanear',
  'feature_search': 'Buscar',
  'feature_share': 'Compartir',
  'feature_stats': 'Estadísticas',
  'feature_track': 'Seguimiento',
  'feedback_auto_collected': 'Información recopilada automáticamente',
  'feedback_beta_notice': 'Aviso beta',
  'feedback_copied': 'Copiado al portapapeles',
  'feedback_copy': 'Copiar',
  'feedback_description_hint': 'Describa el problema o la sugerencia...',
  'feedback_description_label': 'Descripción',
  'feedback_description_required': 'La descripción es obligatoria',
  'feedback_error_opening': 'Error al abrir',
  'feedback_error_sending': 'Error al enviar comentarios',
  'feedback_open_github': 'Abrir en GitHub',
  'feedback_opened_github': 'Abierto en GitHub',
  'feedback_share': 'Compartir comentarios',
  'feedback_solution_hint': '¿Tiene alguna sugerencia de solución?',
  'feedback_solution_label': 'Solución propuesta',
  'feedback_steps_hint': '1. Ir a...\\n2. Hacer clic en...',
  'feedback_steps_label': 'Pasos para reproducir',
  'feedback_submit': 'Enviar',
  'feedback_success': 'Comentarios enviados con éxito',
  'feedback_title': 'Comentarios',
  'feedback_title_hint': 'Resumen breve del problema',
  'feedback_title_label': 'Título',
  'feedback_title_required': 'El título es obligatorio',
  'feedback_type_bug': 'Error',
  'feedback_type_feature': 'Sugerencia',
  'fill_all_fields': 'Rellene todos los campos',
  'filter_all_books': 'Todos los libros',
  'filter_books': 'Filtrar libros',
  'filter_by_tag': 'Filtrar por etiqueta',
  'filter_contacts_only': 'Solo contactos',
  'filter_owned': 'Solo los míos',
  'finished_on': 'Terminado el',
  'finished_reading_label': 'Terminado de leer',
  'first_time_password': 'Primera contraseña',
  'format_audiobook': 'Audiolibro',
  'format_ebook': 'Libro electrónico',
  'format_paper': 'Papel',
  'from_book': 'Del libro',
  'give_back_book_btn': 'Devolver libro',
  'goal_books_this_month': 'Libros este mes',
  'goal_books_this_year': 'Libros este año',
  'google_api_key_helper': 'Clave API de Google Books (opcional)',
  'google_api_key_label': 'Clave API de Google',
  'greeting_afternoon': 'Buenas tardes',
  'greeting_evening': 'Buenas noches',
  'greeting_morning': 'Buenos días',
  'help': 'Ayuda',
  'help_cta_migrate': 'Migrar datos',
  'help_ctx_collections_content':
      'Las colecciones te permiten agrupar libros en listas temáticas.',
  'help_ctx_collections_tip_create': 'Crear colección',
  'help_ctx_collections_tip_create_desc': 'Crea tu primera colección temática',
  'help_ctx_collections_tip_order': 'Ordenar colección',
  'help_ctx_collections_tip_order_desc': 'Arrastra para reordenar los libros',
  'help_ctx_collections_title': 'Colecciones',
  'help_ctx_dashboard_content':
      'El panel te muestra un resumen de tu actividad de lectura.',
  'help_ctx_dashboard_tip_reading': 'Progreso de lectura',
  'help_ctx_dashboard_tip_reading_desc': 'Sigue tu progreso de lectura actual',
  'help_ctx_dashboard_tip_stats': 'Estadísticas',
  'help_ctx_dashboard_tip_stats_desc': 'Consulta tus estadísticas de lectura',
  'help_ctx_dashboard_title': 'Panel de control',
  'help_ctx_library_content':
      'Tu biblioteca contiene todos tus libros. Puedes organizarlos en estanterías.',
  'help_ctx_library_tip_add': 'Añadir libros',
  'help_ctx_library_tip_add_desc':
      'Escanea un código de barras o busca en línea',
  'help_ctx_library_tip_search': 'Buscar',
  'help_ctx_library_tip_search_desc': 'Busca en tu biblioteca por título o autor',
  'help_ctx_library_tip_shelves': 'Estanterías',
  'help_ctx_library_tip_shelves_desc': 'Organiza tus libros en estanterías',
  'help_ctx_library_title': 'Biblioteca',
  'help_ctx_network_content':
      'Conéctate con otros lectores para compartir y tomar prestados libros.',
  'help_ctx_network_tip_add': 'Añadir contacto',
  'help_ctx_network_tip_add_desc': 'Añade un amigo escaneando su código QR',
  'help_ctx_network_tip_browse': 'Explorar bibliotecas',
  'help_ctx_network_tip_browse_desc': 'Explora las bibliotecas de tus amigos',
  'help_ctx_network_tip_request': 'Solicitar préstamo',
  'help_ctx_network_tip_request_desc': 'Solicita un libro a un amigo',
  'help_ctx_network_title': 'Red',
  'help_ctx_profile_content':
      'Tu perfil muestra tus logros y tu progreso como lector.',
  'help_ctx_profile_tip_achievements': 'Logros',
  'help_ctx_profile_tip_achievements_desc': 'Consulta tus logros desbloqueados',
  'help_ctx_profile_tip_theme': 'Tema',
  'help_ctx_profile_tip_theme_desc': 'Personaliza el aspecto de la aplicación',
  'help_ctx_profile_title': 'Perfil',
  'help_ctx_settings_content':
      'Configura la aplicación según tus preferencias.',
  'help_ctx_settings_tip_backup': 'Copia de seguridad',
  'help_ctx_settings_tip_backup_desc': 'Exporta e importa tus datos',
  'help_ctx_settings_tip_modules': 'Módulos',
  'help_ctx_settings_tip_modules_desc': 'Activa o desactiva funcionalidades',
  'help_ctx_settings_tip_sources': 'Fuentes',
  'help_ctx_settings_tip_sources_desc':
      'Elige qué catálogos usar para buscar libros',
  'help_ctx_settings_title': 'Ajustes',
  'help_ctx_shelves_content':
      'Las estanterías te permiten organizar tus libros por categorías.',
  'help_ctx_shelves_tip_assign': 'Asignar libros',
  'help_ctx_shelves_tip_assign_desc':
      'Asigna libros a estanterías desde la ficha del libro',
  'help_ctx_shelves_tip_create': 'Crear estantería',
  'help_ctx_shelves_tip_create_desc': 'Crea estanterías temáticas',
  'help_ctx_shelves_title': 'Estanterías',
  'help_ctx_stats_genre_diversity': 'Diversidad de géneros',
  'help_ctx_stats_loan_stats': 'Estadísticas de préstamos',
  'help_ctx_stats_monthly_progress': 'Progreso mensual',
  'help_ctx_stats_publication_year': 'Año de publicación',
  'help_ctx_stats_reading_habits': 'Hábitos de lectura',
  'help_ctx_stats_sales': 'Ventas',
  'help_ctx_stats_top_authors': 'Autores principales',
  'help_ctx_stats_unique_stats': 'Estadísticas únicas',
  'help_desc_import': 'Importa libros desde un archivo CSV o una copia de seguridad.',
  'help_import_app': 'Importar en la aplicación',
  'help_tips_title': 'Consejos',
  'help_topic_import': '¿Cómo importar libros?',
  'hierarchical_tag_hint': 'Seleccione un padre para crear una jerarquía',
  'how_to_add_contact_help_desc':
      'Escanea el código QR de un amigo o añade un contacto manualmente.',
  'how_to_add_contact_help_title': '¿Cómo añadir un contacto?',
  'how_to_add_contact_qr': 'Escanear código QR de un contacto',
  'how_to_show_code_help_desc':
      'Muestra tu código QR para que otros puedan escanearlo.',
  'how_to_show_code_help_title': '¿Cómo mostrar mi código?',
  'how_to_show_code_label': 'Mostrar mi código',
  'import_action_button': 'Importar',
  'import_backup': 'Importar copia de seguridad',
  'import_backup_fail': 'Error al importar la copia de seguridad',
  'import_btn': 'Importar',
  'import_collection_success': 'Colección importada con éxito',
  'import_file': 'Importar archivo',
  'import_method_file_desc': 'Importar desde un archivo CSV o Excel',
  'import_method_file_title': 'Desde un archivo',
  'import_method_paste_desc': 'Pegar una lista de ISBN o títulos',
  'import_method_paste_title': 'Desde el portapapeles',
  'import_options': 'Opciones de importación',
  'import_preview_subtitle': 'Vista previa de los libros a importar',
  'import_preview_title': 'Vista previa de importación',
  'import_screen_title': 'Importar libros',
  'import_status_label': 'Estado de importación',
  'importing_backup': 'Importando copia de seguridad...',
  'individual_reader': 'Lector individual',
  'invalid_code': 'Código no válido',
  'invalid_code_length': 'Longitud de código no válida',
  'invalid_credentials': 'Credenciales no válidas',
  'invalid_isbn_scanned': 'ISBN escaneado no válido',
  'invalid_sale_price': 'Precio de venta no válido',
  'isbn_already_exists': 'Este ISBN ya existe en tu biblioteca',
  'kid': 'Niño',
  'leaderboard_cataloguer': 'Catalogador',
  'leaderboard_cataloguer_desc': 'Más libros catalogados',
  'leaderboard_collector': 'Coleccionista',
  'leaderboard_collector_desc': 'Más libros en la colección',
  'leaderboard_empty': 'Aún no hay clasificación',
  'leaderboard_lender': 'Prestamista',
  'leaderboard_lender_desc': 'Más libros prestados',
  'leaderboard_rank': 'Posición',
  'leaderboard_reader': 'Lector',
  'leaderboard_reader_desc': 'Más libros leídos',
  'leaderboard_title': 'Clasificación',
  'leaderboard_you': 'Tú',
  'lend_book_btn': 'Prestar libro',
  'lend_to_contact': 'Prestar a un contacto',
  'lent_status': 'Prestado',
  'let_someone_scan_your_library': 'Deja que alguien escanee tu biblioteca',
  'level': 'Nivel',
  'level_apprenti': 'Aprendiz',
  'level_bibliophile': 'Bibliófilo',
  'level_bronze': 'Bronce',
  'level_curieux': 'Curioso',
  'level_curious': 'Curioso',
  'level_erudit': 'Erudito',
  'level_gold': 'Oro',
  'level_initiate': 'Iniciado',
  'level_initie': 'Iniciado',
  'level_novice': 'Novato',
  'level_platine': 'Platino',
  'level_scholar': 'Erudito',
  'level_silver': 'Plata',
  'libraries_found': 'Bibliotecas encontradas',
  'link_device_code_instructions': 'Introduce este código en el otro dispositivo',
  'link_device_code_valid': 'Código válido',
  'link_device_generate_code': 'Generar código',
  'link_device_host_ip': 'IP del host',
  'link_device_host_ip_hint': 'Dirección IP del servidor',
  'link_device_join_desc': 'Únete a una biblioteca existente',
  'link_device_join_title': 'Unirse',
  'link_device_pairing_code_hint': 'Código de emparejamiento',
  'link_device_share_desc': 'Comparte tu biblioteca con otro dispositivo',
  'link_device_share_title': 'Compartir',
  'link_device_sync_complete': 'Sincronización completada',
  'link_device_verify_link': 'Verificar enlace',
  'link_device_your_ip': 'Tu IP',
  'loan_statistics': 'Estadísticas de préstamos',
  'loans_and_borrowings': 'Préstamos y préstamos recibidos',
  'loans_label': 'Préstamos',
  'local_discovery_help':
      'Descubre bibliotecas en tu red local',
  'local_network_title': 'Red local',
  'login_failed_prefix': 'Error de inicio de sesión:',
  'login_subtitle': 'Inicia sesión para continuar',
  'looking_up_isbn': 'Buscando ISBN...',
  'manage_collections': 'Gestionar colecciones',
  'manage_login_credentials': 'Gestionar credenciales de inicio de sesión',
  'manage_shelves': 'Gestionar estanterías',
  'manage_shelves_desc': 'Renombrar, eliminar o reorganizar estanterías',
  'manage_tags': 'Gestionar estanterías',
  'mark_as_finished': 'Marcar como terminado',
  'mark_as_owned': 'Marcar como poseído',
  'mark_as_read': 'Marcar como leído',
  'mfa_code_required': 'Código MFA obligatorio',
  'mfa_disabled': 'MFA desactivado',
  'mfa_enabled': 'MFA activado',
  'mfa_enter_code': 'Introduce el código MFA',
  'mfa_manual_key': 'Clave manual',
  'mfa_requires_server': 'MFA requiere modo servidor',
  'mfa_scan_qr': 'Escanear código QR',
  'mfa_setup_error': 'Error al configurar MFA',
  'mfa_setup_success': 'MFA configurado con éxito',
  'mfa_setup_title': 'Configurar MFA',
  'mfa_verify': 'Verificar',
  'min_one_source_error': 'Se requiere al menos una fuente',
  'module_collections': 'Colecciones',
  'module_collections_desc': 'Agrupa libros en listas temáticas',
  'module_digital_formats': 'Formatos digitales',
  'module_digital_formats_desc': 'Gestiona ebooks y audiolibros',
  'module_gamification': 'Gamificación',
  'module_gamification_desc': 'Logros, niveles y racha de lectura',
  'module_network': 'Red',
  'module_network_desc': 'Conéctate con otros lectores',
  'module_quotes': 'Citas',
  'module_quotes_desc': 'Guarda citas de tus libros favoritos',
  'modules': 'Módulos',
  'more_actions': 'Más acciones',
  'most_lent_books': 'Libros más prestados',
  'move': 'Mover',
  'move_shelf': 'Mover estantería',
  'move_shelf_hint': 'Cambiar categoría padre',
  'moving': 'Moviendo...',
  'multiple_editions_found': 'Varias ediciones encontradas',
  'my_books': 'Mis libros',
  'nav_report_bug': 'Reportar un error',
  'network_discovery_desc': 'Descubre bibliotecas cercanas en tu red',
  'network_gamification': 'Gamificación en red',
  'network_gamification_desc': 'Compara tu progreso con otros lectores',
  'network_module': 'Módulo de red',
  'network_module_desc': 'Comparte y toma prestados libros',
  'never_synced': 'Nunca sincronizado',
  'new_password': 'Nueva contraseña',
  'no_available_copies': 'No hay ejemplares disponibles',
  'no_borrowed_books': 'No hay libros prestados',
  'no_collection_selected': 'Ninguna colección seleccionada',
  'no_collections': 'Sin colecciones',
  'no_contacts_hint': 'Añade contactos para compartir libros',
  'no_contacts_title': 'Sin contactos',
  'no_copies_found': 'No se encontraron ejemplares',
  'no_cover_available': 'Sin portada disponible',
  'no_existing_tags': '¡No se han creado estanterías. Empieza por crear una!',
  'no_local_libraries_found': 'No se encontraron bibliotecas locales',
  'no_network_members': 'Sin miembros en la red',
  'no_password_set': 'Sin contraseña configurada',
  'no_reading_status': 'Sin estado de lectura',
  'no_shelves': 'Sin estanterías',
  'no_sub_shelves': 'Sin sub-estanterías',
  'no_tags': 'Sin etiquetas',
  'none': 'Ninguno',
  'onboarding_network_desc': 'Conéctate con otros lectores para compartir libros',
  'onboarding_network_title': 'Red de lectores',
  'onboarding_slogan_1': 'Tu biblioteca universal, en tu bolsillo.',
  'onboarding_slogan_2': 'Añade libros escaneando códigos de barras o buscando en línea.',
  'onboarding_slogan_3': 'Conecta tu conocimiento. Comparte tus mundos.',
  'onboarding_slogan_4': 'Visualiza tu pasión. Mide tu erudición.',
  'onboarding_swipe_hint': 'Desliza para continuar',
  'or_manual_entry': 'O introducir manualmente',
  'organize': 'Organizar',
  'own_this_book': 'Tengo este libro',
  'own_this_book_hint': 'Marcar como poseído en tu biblioteca',
  'owned_vs_total': 'Poseídos / Total',
  'parent_shelf': 'Estantería padre',
  'password': 'Contraseña',
  'password_changed_success': 'Contraseña cambiada con éxito',
  'password_incorrect': 'Contraseña incorrecta',
  'password_required': 'Contraseña obligatoria',
  'password_too_short': 'Contraseña demasiado corta',
  'passwords_dont_match': 'Las contraseñas no coinciden',
  'peer_offline': 'Par desconectado',
  'peer_offline_caching': 'Caché de par desconectado',
  'peer_offline_caching_desc':
      'Los datos se guardan en caché cuando el par está desconectado',
  'peer_offline_cannot_sync': 'No se puede sincronizar: par desconectado',
  'peer_offline_library_unavailable':
      'La biblioteca no está disponible: par desconectado',
  'peer_online': 'Par conectado',
  'preparing_backup': 'Preparando copia de seguridad...',
  'preset_applied': 'Perfil aplicado',
  'preset_bookseller': 'Librero',
  'preset_librarian': 'Bibliotecario',
  'preset_reader': 'Lector',
  'price': 'Precio',
  'price_label': 'Precio',
  'profile_advantage_borrow': 'Tomar prestados libros',
  'profile_advantage_contacts': 'Gestión de contactos',
  'profile_advantage_inventory': 'Inventario completo',
  'profile_advantage_lend': 'Prestar libros',
  'profile_advantage_lending': 'Sistema de préstamos',
  'profile_advantage_pricing': 'Gestión de precios',
  'profile_advantage_sales': 'Gestión de ventas',
  'profile_advantage_simple_ui': 'Interfaz simplificada',
  'profile_advantage_statistics': 'Estadísticas avanzadas',
  'profile_advantage_wishlist': 'Lista de deseos',
  'profile_bookseller': 'Librero',
  'profile_bookseller_desc': 'Gestiona tu inventario y ventas',
  'profile_restriction_no_borrow': 'Sin préstamos recibidos',
  'profile_restriction_no_gamification': 'Sin gamificación',
  'profile_restriction_no_lend': 'Sin préstamos',
  'profile_restriction_no_loans': 'Sin sistema de préstamos',
  'profile_summary': 'Resumen del perfil',
  'profile_updated': 'Perfil actualizado',
  'progress_hint_bibliophile': 'Sigue leyendo para convertirte en bibliófilo',
  'progress_hint_curieux': 'Explora más para satisfacer tu curiosidad',
  'progress_hint_erudit': 'Casi eres un erudito',
  'progress_hint_initie': 'Estás en camino de la iniciación',
  'qr_wifi_suggestion': 'Conéctate al mismo WiFi para mejor conexión',
  'quick_actions_title': 'Acciones rápidas',
  'quick_borrow_book': 'Tomar prestado un libro',
  'quick_create_shelf': 'Crear estantería',
  'quick_presets': 'Perfiles predefinidos',
  'quick_presets_desc': 'Elige un perfil para configurar rápidamente la app',
  'quick_scan_barcode': 'Escanear código de barras',
  'quick_search_online': 'Buscar en línea',
  'quote_of_the_day': 'Cita del día',
  'reading_status_abandoned': 'Abandonado',
  'reading_status_borrowed': 'Prestado',
  'reading_status_lent': 'Prestado',
  'reading_status_read': 'Leído',
  'reading_status_reading': 'Leyendo',
  'reading_status_to_read': 'Por leer',
  'reading_status_wanting': 'Deseado',
  'recent_achievements': 'Logros recientes',
  'recent_sales': 'Ventas recientes',
  'record_sale': 'Registrar venta',
  'record_sale_title': 'Registrar una venta',
  'refresh_apply': 'Aplicar cambios',
  'refresh_current': 'Valor actual',
  'refresh_empty': 'Vacío',
  'refresh_field_author': 'Autor',
  'refresh_field_cover': 'Portada',
  'refresh_field_publisher': 'Editorial',
  'refresh_field_summary': 'Resumen',
  'refresh_field_title': 'Título',
  'refresh_field_year': 'Año',
  'refresh_found': 'Encontrado en línea',
  'refresh_identical': 'Idéntico',
  'refresh_metadata_applied': 'Metadatos actualizados',
  'refresh_metadata_error': 'Error al actualizar metadatos',
  'refresh_metadata_no_changes': 'Sin cambios',
  'refresh_metadata_not_found': 'Metadatos no encontrados',
  'refresh_metadata_title': 'Actualizar metadatos',
  'reorder_manual': 'Ordenar manualmente',
  'reordering_shelf': 'Reordenando estantería...',
  'return_book_btn': 'Devolver libro',
  'return_rate': 'Tasa de devolución',
  'root_level': 'Nivel raíz',
  'root_tag': 'Raíz (sin padre)',
  'sale_date': 'Fecha de venta',
  'sale_notes': 'Notas (opcional)',
  'sale_price': 'Precio de venta',
  'sale_recorded': 'Venta registrada con éxito',
  'sales': 'Ventas',
  'sales_count': 'Número de ventas',
  'sales_statistics': 'Estadísticas de ventas',
  'scan_first_book': 'Escanea tu primer libro',
  'scan_friend_qr_code': 'Escanear código QR de un amigo',
  'scan_into_collection': 'Escanear en colección',
  'scan_into_shelf': 'Escanear en estantería',
  'scan_isbn_barcode': 'Escanear código de barras ISBN',
  'search_btn': 'Buscar',
  'search_empty_desc': 'No se encontraron resultados',
  'search_hint_example': 'ej: Harry Potter, 978-2-07...',
  'search_in_library': 'Buscar en la biblioteca',
  'search_library_placeholder': 'Buscar en tu biblioteca...',
  'search_placeholder': 'Buscar...',
  'search_sources': 'Fuentes de búsqueda',
  'search_tab_editions': 'Ediciones',
  'search_tab_list': 'Lista',
  'search_title_label': 'Título',
  'security': 'Seguridad',
  'security_settings': 'Ajustes de seguridad',
  'see_all_books': 'Ver todos los libros',
  'see_all_to_read': 'Ver todos por leer',
  'select_book': 'Seleccionar un libro',
  'select_buyer': 'Seleccionar comprador',
  'select_copy': 'Seleccionar un ejemplar',
  'select_currency': 'Seleccionar divisa',
  'select_date': 'Seleccionar fecha',
  'select_edition': 'Seleccionar edición',
  'select_from_tree': 'Seleccionar del árbol',
  'select_lender': 'Seleccionar prestamista',
  'select_new_parent': 'Seleccionar nuevo padre',
  'select_parent_optional': 'Padre (opcional)',
  'select_profile_type': 'Seleccionar tipo de perfil',
  'select_tags': 'Seleccionar etiquetas',
  'select_tags_title': 'Gestionar estanterías',
  'select_this_edition': 'Seleccionar esta edición',
  'selected_books_count': '{count} libros seleccionados',
  'sell_book_btn': 'Vender libro',
  'server_changed': 'Servidor cambiado',
  'server_settings_title': 'Ajustes del servidor',
  'server_url_label': 'URL del servidor',
  'set_password': 'Establecer contraseña',
  'share_gamification_stats': 'Compartir estadísticas',
  'share_gamification_stats_desc': 'Comparte tus logros con amigos',
  'shelf_books_count': '{count} libros',
  'shelf_created': 'Estantería creada',
  'shelf_deleted': 'Estantería eliminada',
  'shelf_empty_desc': 'Esta estantería está vacía',
  'shelf_management_hint': 'Gestiona tus estanterías',
  'shelf_name': 'Nombre de estantería',
  'shelf_name_hint': 'ej: Ciencia Ficción',
  'shelf_statistics': 'Estadísticas de estanterías',
  'shelf_updated': 'Estantería actualizada',
  'show_my_code': 'Mostrar mi código',
  'showing_cached': 'Mostrando datos en caché',
  'simplified_mode': 'Modo simplificado',
  'simplified_mode_desc': 'Interfaz simplificada para niños',
  'sort_by_author_az': 'Ordenar por autor A→Z',
  'sort_by_author_za': 'Ordenar por autor Z→A',
  'sorted_by_author_az': 'Ordenado por autor A→Z',
  'sorted_by_author_za': 'Ordenado por autor Z→A',
  'source_bnf_desc': 'Biblioteca Nacional de Francia',
  'source_google_desc': 'Google Books',
  'source_inventaire_desc': 'Inventaire (basado en Wikidata)',
  'source_openlibrary_desc': 'Open Library',
  'start_reading': 'Empezar a leer',
  'started_reading_label': 'Empezado a leer',
  'stat_avg_collection_completion': 'Compleción media de colecciones',
  'stat_total_collections': 'Total de colecciones',
  'status': 'Estado',
  'status_active': 'Activo',
  'status_approved': 'Aprobado',
  'status_connected': 'Conectado',
  'status_inactive': 'Inactivo',
  'status_loaned': 'Prestado',
  'status_offline': 'Desconectado',
  'status_owned': 'Poseído',
  'status_uncategorized': 'Sin categorizar',
  'status_updated': 'Estado actualizado',
  'status_wanted': 'Deseado',
  'sub_categories': 'Sub-categorías',
  'sync_collection': 'Sincronizar precios',
  'sync_success': 'Precios sincronizados',
  'synced_days_ago': 'Sincronizado hace {count} días',
  'synced_hours_ago': 'Sincronizado hace {count} horas',
  'synced_just_now': 'Sincronizado ahora',
  'synced_minutes_ago': 'Sincronizado hace {count} minutos',
  'tab_list': 'Lista',
  'tab_members': 'Miembros',
  'tag_created_success': 'Estantería creada: ',
  'tag_creation_error': 'Error al crear la estantería',
  'tag_experimental': 'Experimental',
  'tag_name_hint': 'Nombre de la estantería',
  'tags_label': 'Estanterías',
  'tap_to_view': 'Toca para ver',
  'text_size': 'Tamaño del texto',
  'text_size_default': 'Normal',
  'text_size_large': 'Grande',
  'text_size_small': 'Pequeño',
  'top_borrowers': 'Principales prestatarios',
  'top_collections': 'Principales colecciones',
  'top_shelves': 'Principales estanterías',
  'total_collections': 'Total de colecciones',
  'total_loans': 'Total de préstamos',
  'total_revenue': 'Ingresos totales',
  'total_shelves': 'Total de estanterías',
  'track_cataloguer': 'Catalogador',
  'track_collector': 'Coleccionista',
  'track_lender': 'Prestamista',
  'track_reader': 'Lector',
  'two_factor_auth': 'Autenticación de dos factores',
  'type_contact_details': 'Introduce los datos del contacto',
  'understood': 'Entendido',
  'username': 'Nombre de usuario',
  'verification_failed': 'Verificación fallida',
  'verify': 'Verificar',
  'view_carousel': 'Vista carrusel',
  'view_existing': 'Ver existentes',
  'view_list': 'Vista lista',
  'view_online': 'Ver en línea',
  'wizard_books_view_desc': 'Alterna entre vista cuadrícula (estantería) y vista lista.',
  'wizard_contacts_add_desc': 'Añade amigos o prestatarios para compartir libros.',
  'wizard_contacts_add_title': 'Añadir contacto',
  'wizard_contacts_filter_desc': 'Filtra por Prestatarios (local) o Bibliotecas (P2P).',
  'wizard_contacts_filter_title': 'Filtrar contactos',
  'works': 'Obras',
  'young_reader_mode': 'Modo joven lector',
  'young_reader_mode_desc': 'Interfaz simplificada para niños',
  'your_current_level': 'Tu nivel actual',
  'your_progress': 'Tu progreso',
  'link_device_enter_code': 'Introducir código',
  'link_device_scan_or_type': 'Escanear o escribir el código de emparejamiento',
  'link_device_verify': 'Verificar',
  'saving_changes': 'Guardando cambios...',
};

// ─── DE missing translations ───
const deMissing = <String, String>{
  'achievement_collector_bronze': 'Sammler Bronze',
  'achievement_collector_silver': 'Sammler Silber',
  'achievement_first_book': 'Erstes Buch',
  'achievement_first_loan': 'Großzügig',
  'achievement_first_scan': 'Scanner Pro',
  'achievement_reader_bronze': 'Eifriger Leser',
  'achievement_streak_3': 'Regelmäßig',
  'achievement_streak_7': 'Perfekte Woche',
  'action_scan_barcode': 'Barcode scannen',
  'action_search_online': 'Online suchen',
  'action_share': 'Teilen',
  'add_book_button': 'Buch hinzufügen',
  'add_book_manually': 'Manuell hinzufügen',
  'add_collection': 'Sammlung hinzufügen',
  'add_contact': 'Kontakt hinzufügen',
  'add_contact_or_scan_help': 'Kontakt hinzufügen oder QR-Code scannen',
  'add_contact_title': 'Kontakt hinzufügen',
  'add_copy': 'Exemplar hinzufügen',
  'add_copy_hint': 'Neues Exemplar dieses Buches hinzufügen',
  'add_first_book_in_shelf': 'Füge dein erstes Buch zu diesem Regal hinzu',
  'add_first_contact': 'Ersten Kontakt hinzufügen',
  'add_sub_shelf': 'Unterregal hinzufügen',
  'add_tag': 'Hinzufügen',
  'add_tags': 'Tags hinzufügen',
  'add_to_collection': 'Zur Sammlung hinzufügen',
  'add_to_collections_label': 'Zu Sammlungen hinzufügen',
  'add_to_library': 'Zur Bibliothek hinzufügen',
  'added_date_label': 'Hinzugefügt am',
  'advanced_filters': 'Erweiterte Filter',
  'all_shelves': 'Alle Regale',
  'all_sources': 'Alle Quellen',
  'allow_library_caching': 'Bibliothek-Cache erlauben',
  'allow_library_caching_desc':
      'Ermöglicht deinen Freunden, eine lokale Kopie deiner Bibliothek zu speichern',
  'anim_achievement_pop': 'Erfolg-Pop',
  'anim_achievement_pop_desc': 'Animation beim Freischalten eines Erfolgs',
  'anim_badge_unlock': 'Abzeichen-Freischaltung',
  'anim_badge_unlock_desc': 'Animation beim Erhalten eines neuen Abzeichens',
  'anim_book_complete': 'Buch abgeschlossen',
  'anim_book_complete_desc': 'Animation beim Abschließen eines Buches',
  'anim_gamification_title': 'Gamification-Animationen',
  'anim_goal_reached': 'Ziel erreicht',
  'anim_goal_reached_desc': 'Animation beim Erreichen eines Leseziels',
  'anim_level_up': 'Level-Up',
  'anim_level_up_desc': 'Animation beim Aufstieg',
  'anim_play_sequence': 'Sequenz abspielen',
  'anim_plus_one': '+1',
  'anim_plus_one_desc': '+1 Animation beim Hinzufügen eines Buches',
  'anim_tap_to_test': 'Tippen zum Testen',
  'api_key_saved': 'API-Schlüssel gespeichert',
  'ask_genie': 'Genie fragen',
  'audio_module': 'Audio-Modul',
  'audio_module_desc': 'Hörbücher aus deiner Bibliothek anhören',
  'availability_available': 'Verfügbar',
  'availability_borrowed': 'Ausgeliehen',
  'availability_label': 'Verfügbarkeit',
  'availability_loaned': 'Verliehen',
  'availability_lost': 'Verloren',
  'availability_wanted': 'Gewünscht',
  'avatar_robot': 'Roboter',
  'average_price': 'Durchschnittspreis',
  'avg_duration': 'Durchschnittsdauer',
  'back_to_all': 'Zurück zu allen',
  'backup_reminder_export': 'Jetzt exportieren',
  'backup_reminder_later': 'Später',
  'backup_reminder_message':
      'Es ist lange her seit deiner letzten Sicherung. Schütze deine Daten durch einen Export.',
  'backup_reminder_tip': 'Tipp: Exportiere regelmäßig, um Datenverlust zu vermeiden',
  'backup_reminder_title': 'Sicherung empfohlen',
  'badge_collection': 'Abzeichen-Sammlung',
  'badge_desc_bibliophile': 'Leidenschaftlicher Bücherfreund',
  'badge_desc_curieux': 'Neugieriger Entdecker',
  'badge_desc_erudit': 'Gelehrter des Wissens',
  'badge_desc_initie': 'Eingeweihter im Lesen',
  'badge_levels_title': 'Abzeichen-Stufen',
  'badge_progress_info': 'Abzeichen-Fortschritt',
  'batch_scan_desc': 'Mehrere Bücher nacheinander scannen',
  'batch_scan_title': 'Stapel-Scan',
  'best_streak': 'Beste Serie',
  'book_borrowed_from': 'Buch ausgeliehen von',
  'book_borrowed_success': 'Buch erfolgreich ausgeliehen',
  'book_found': 'Buch gefunden',
  'book_given_back': 'Buch zurückgegeben',
  'book_not_found': 'Buch nicht gefunden',
  'book_price': 'Buchpreis',
  'book_returned': 'Buch zurückgegeben',
  'books_added': 'Bücher hinzugefügt',
  'books_borrowed': 'Ausgeliehene Bücher',
  'books_imported': 'Bücher importiert',
  'books_in_collections': 'Bücher in Sammlungen',
  'books_in_shelves': 'Bücher in Regalen',
  'bookseller': 'Buchhändler',
  'borrow_book_title': 'Buch ausleihen',
  'borrow_btn': 'Ausleihen',
  'borrow_from_contact': 'Von Kontakt ausleihen',
  'borrow_from_contact_btn': 'Ausleihen von',
  'borrowed': 'Ausgeliehen',
  'borrowed_books_list': 'Liste der ausgeliehenen Bücher',
  'borrowed_from_label': 'Ausgeliehen von',
  'borrowed_statistics': 'Ausleih-Statistiken',
  'borrowed_status': 'Ausgeliehen',
  'borrowing_from': 'Ausgeliehen von',
  'browse_shelf': 'Regal durchsuchen',
  'btn_enter_manually': 'Manuell eingeben',
  'btn_scan_book': 'Buch scannen',
  'btn_search_book_online': 'Buch online suchen',
  'btn_search_online_cta': 'In Online-Katalogen suchen',
  'camera_error': 'Kamerafehler',
  'camera_loading': 'Kamera wird geladen...',
  'change_password': 'Passwort ändern',
  'city_label': 'Stadt',
  'clear': 'Löschen',
  'close': 'Schließen',
  'code_label': 'Code',
  'collection_details': 'Sammlungsdetails',
  'collection_name_hint': 'Name der Sammlung',
  'collection_statistics': 'Sammlungsstatistiken',
  'collections': 'Sammlungen',
  'collections_label': 'Sammlungen',
  'commerce_module_label': 'Handelsmodul',
  'commerce_module_subtitle': 'Verkäufe und Preise verwalten',
  'confirm_borrow': 'Ausleihe bestätigen',
  'confirm_delete': 'Löschen bestätigen',
  'confirm_password': 'Passwort bestätigen',
  'confirm_sale': 'Verkauf bestätigen',
  'connection_pending_approval': 'Verbindung wartet auf Genehmigung',
  'connection_request_awaiting': 'Verbindungsanfrage ausstehend',
  'connection_validation': 'Verbindungsvalidierung',
  'connection_validation_desc':
      'Eingehende Verbindungsanfragen akzeptieren oder ablehnen',
  'contact_address_label': 'Adresse',
  'contact_created': 'Kontakt erstellt',
  'contact_email_invalid': 'Ungültige E-Mail-Adresse',
  'contact_email_label': 'E-Mail',
  'contact_first_name_hint': 'Vorname',
  'contact_first_name_label': 'Vorname',
  'contact_name_label': 'Name',
  'contact_name_required': 'Name ist erforderlich',
  'contact_notes_label': 'Notizen',
  'contact_phone_label': 'Telefon',
  'contact_type_borrower': 'Entleiher',
  'contact_type_label': 'Kontakttyp',
  'contact_type_lender': 'Verleiher',
  'content': 'Inhalt',
  'continue_reading': 'Weiterlesen',
  'copy_added': 'Exemplar hinzugefügt',
  'copy_label': 'Exemplar',
  'copy_price': 'Exemplarpreis',
  'country_label': 'Land',
  'cover_add': 'Cover hinzufügen',
  'cover_change': 'Cover ändern',
  'cover_choose_file': 'Datei auswählen',
  'cover_confirm_use': 'Dieses Cover verwenden?',
  'cover_found': 'Cover gefunden',
  'cover_found_by_title': 'Cover nach Titel gefunden',
  'cover_no_isbn': 'Keine ISBN für Cover-Suche',
  'cover_not_found': 'Cover nicht gefunden',
  'cover_pick_title': 'Cover auswählen',
  'cover_remove': 'Cover entfernen',
  'cover_removed': 'Cover entfernt',
  'cover_search_online': 'Cover online suchen',
  'cover_searching': 'Suche Cover...',
  'cover_searching_by_title': 'Suche Cover nach Titel...',
  'cover_updated': 'Cover aktualisiert',
  'cover_use_button': 'Dieses Cover verwenden',
  'create': 'Erstellen',
  'create_collection': 'Sammlung erstellen',
  'create_collection_hint': 'Name der neuen Sammlung',
  'create_first_shelf': 'Erstes Regal erstellen',
  'create_new_collection': 'Neue Sammlung erstellen',
  'create_new_tag': 'Neues Regal erstellen',
  'create_shelf': 'Regal erstellen',
  'currency_label': 'Währung',
  'current': 'Aktuell',
  'current_password': 'Aktuelles Passwort',
  'current_streak': 'Aktuelle Serie',
  'date_select_option_none': 'Kein Datum',
  'date_select_option_pick': 'Datum wählen',
  'date_select_option_today': 'Heute',
  'date_select_title': 'Datum auswählen',
  'delete': 'Löschen',
  'delete_collection': 'Sammlung löschen',
  'delete_collection_confirm': 'Sind Sie sicher, dass Sie diese Sammlung löschen möchten?',
  'delete_shelf': 'Regal löschen',
  'delete_shelf_warning': 'Diese Aktion kann nicht rückgängig gemacht werden',
  'delete_with_children_warning':
      'Dieses Regal enthält Unterregale, die ebenfalls gelöscht werden',
  'digital_formats_label': 'Digitale Formate',
  'disable': 'Deaktivieren',
  'discover': 'Entdecken',
  'discover_collections_subtitle': 'Kuratierte Buchlisten entdecken',
  'discover_collections_title': 'Sammlungen entdecken',
  'displayed_books_count': '{count} Buch angezeigt',
  'displayed_books_count_plural': '{count} Bücher angezeigt',
  'displayed_collections_count': '{count} Sammlung angezeigt',
  'displayed_collections_count_plural': '{count} Sammlungen angezeigt',
  'displayed_shelves_count': '{count} Regal angezeigt',
  'displayed_shelves_count_plural': '{count} Regale angezeigt',
  'done': 'Fertig',
  'due_date_label': 'Fälligkeitsdatum',
  'edit': 'Bearbeiten',
  'edit_library_name': 'Bibliotheksname bearbeiten',
  'edit_shelf': 'Regal bearbeiten',
  'editions': 'Ausgaben',
  'email_label': 'E-Mail',
  'empty_collection': 'Leere Sammlung',
  'empty_library_subtitle': 'Füge dein erstes Buch hinzu, um zu beginnen',
  'empty_library_title': 'Deine Bibliothek ist leer',
  'enable': 'Aktivieren',
  'enable_network_discovery': 'Netzwerkerkennung aktivieren',
  'enter_isbn_manually': 'ISBN manuell eingeben',
  'enter_library_name': 'Bibliotheksname eingeben',
  'enter_manually': 'Manuell eingeben',
  'enter_password_to_reset': 'Passwort eingeben zum Zurücksetzen',
  'enter_sale_price': 'Verkaufspreis eingeben',
  'enter_title_error': 'Bitte einen Titel eingeben',
  'enter_username': 'Benutzername eingeben',
  'error_409_conflict': 'Konflikt: Ressource existiert bereits',
  'error_creating_collection': 'Fehler beim Erstellen der Sammlung',
  'error_creating_contact': 'Fehler beim Erstellen des Kontakts',
  'error_fetching_isbn': 'Fehler beim ISBN-Abruf',
  'error_giving_back_book': 'Fehler beim Zurückgeben des Buches',
  'error_no_available_copies': 'Keine Exemplare verfügbar',
  'error_peer_offline': 'Peer ist offline',
  'error_peer_timeout': 'Peer-Zeitüberschreitung',
  'error_returning_book': 'Fehler beim Zurückgeben des Buches',
  'error_updating_library': 'Fehler beim Aktualisieren der Bibliothek',
  'existing_tags_section': 'Vorhandene Regale',
  'explore_collections': 'Sammlungen erkunden',
  'external_search_empty_hint': 'Bücher in externen Katalogen suchen',
  'feature_borrow': 'Ausleihen',
  'feature_connect': 'Verbinden',
  'feature_discover': 'Entdecken',
  'feature_goals': 'Ziele',
  'feature_history': 'Verlauf',
  'feature_manual': 'Handbuch',
  'feature_organize': 'Organisieren',
  'feature_scan': 'Scannen',
  'feature_search': 'Suchen',
  'feature_share': 'Teilen',
  'feature_stats': 'Statistiken',
  'feature_track': 'Verfolgen',
  'feedback_auto_collected': 'Automatisch gesammelte Informationen',
  'feedback_beta_notice': 'Beta-Hinweis',
  'feedback_copied': 'In Zwischenablage kopiert',
  'feedback_copy': 'Kopieren',
  'feedback_description_hint': 'Beschreiben Sie das Problem oder den Vorschlag...',
  'feedback_description_label': 'Beschreibung',
  'feedback_description_required': 'Beschreibung ist erforderlich',
  'feedback_error_opening': 'Fehler beim Öffnen',
  'feedback_error_sending': 'Fehler beim Senden des Feedbacks',
  'feedback_open_github': 'Auf GitHub öffnen',
  'feedback_opened_github': 'Auf GitHub geöffnet',
  'feedback_share': 'Feedback teilen',
  'feedback_solution_hint': 'Haben Sie einen Lösungsvorschlag?',
  'feedback_solution_label': 'Vorgeschlagene Lösung',
  'feedback_steps_hint': '1. Gehe zu...\\n2. Klicke auf...',
  'feedback_steps_label': 'Schritte zum Reproduzieren',
  'feedback_submit': 'Absenden',
  'feedback_success': 'Feedback erfolgreich gesendet',
  'feedback_title': 'Feedback',
  'feedback_title_hint': 'Kurze Zusammenfassung des Problems',
  'feedback_title_label': 'Titel',
  'feedback_title_required': 'Titel ist erforderlich',
  'feedback_type_bug': 'Fehler',
  'feedback_type_feature': 'Vorschlag',
  'fill_all_fields': 'Alle Felder ausfüllen',
  'filter_all_books': 'Alle Bücher',
  'filter_books': 'Bücher filtern',
  'filter_by_tag': 'Nach Tag filtern',
  'filter_contacts_only': 'Nur Kontakte',
  'filter_owned': 'Nur eigene',
  'finished_on': 'Beendet am',
  'finished_reading_label': 'Fertig gelesen',
  'first_time_password': 'Erstes Passwort',
  'format_audiobook': 'Hörbuch',
  'format_ebook': 'E-Book',
  'format_paper': 'Papier',
  'friends_libraries_title': 'Bibliotheken von Freunden',
  'from_book': 'Vom Buch',
  'give_back_book_btn': 'Buch zurückgeben',
  'goal_books_this_month': 'Bücher diesen Monat',
  'goal_books_this_year': 'Bücher dieses Jahr',
  'google_api_key_helper': 'Google Books API-Schlüssel (optional)',
  'google_api_key_label': 'Google API-Schlüssel',
  'greeting_afternoon': 'Guten Nachmittag',
  'greeting_evening': 'Guten Abend',
  'greeting_morning': 'Guten Morgen',
  'help': 'Hilfe',
  'help_cta_migrate': 'Daten migrieren',
  'help_ctx_collections_content':
      'Sammlungen ermöglichen es dir, Bücher in thematischen Listen zu gruppieren.',
  'help_ctx_collections_tip_create': 'Sammlung erstellen',
  'help_ctx_collections_tip_create_desc': 'Erstelle deine erste thematische Sammlung',
  'help_ctx_collections_tip_order': 'Sammlung ordnen',
  'help_ctx_collections_tip_order_desc': 'Ziehe um die Bücher neu zu ordnen',
  'help_ctx_collections_title': 'Sammlungen',
  'help_ctx_dashboard_content':
      'Das Dashboard zeigt dir eine Übersicht deiner Leseaktivität.',
  'help_ctx_dashboard_tip_reading': 'Lesefortschritt',
  'help_ctx_dashboard_tip_reading_desc': 'Verfolge deinen aktuellen Lesefortschritt',
  'help_ctx_dashboard_tip_stats': 'Statistiken',
  'help_ctx_dashboard_tip_stats_desc': 'Sieh dir deine Lesestatistiken an',
  'help_ctx_dashboard_title': 'Dashboard',
  'help_ctx_library_content':
      'Deine Bibliothek enthält alle deine Bücher. Du kannst sie in Regalen organisieren.',
  'help_ctx_library_tip_add': 'Bücher hinzufügen',
  'help_ctx_library_tip_add_desc': 'Scanne einen Barcode oder suche online',
  'help_ctx_library_tip_search': 'Suchen',
  'help_ctx_library_tip_search_desc': 'Suche in deiner Bibliothek nach Titel oder Autor',
  'help_ctx_library_tip_shelves': 'Regale',
  'help_ctx_library_tip_shelves_desc': 'Organisiere deine Bücher in Regalen',
  'help_ctx_library_title': 'Bibliothek',
  'help_ctx_network_content':
      'Verbinde dich mit anderen Lesern, um Bücher zu teilen und auszuleihen.',
  'help_ctx_network_tip_add': 'Kontakt hinzufügen',
  'help_ctx_network_tip_add_desc': 'Füge einen Freund hinzu, indem du seinen QR-Code scannst',
  'help_ctx_network_tip_browse': 'Bibliotheken durchsuchen',
  'help_ctx_network_tip_browse_desc': 'Durchsuche die Bibliotheken deiner Freunde',
  'help_ctx_network_tip_request': 'Ausleihe anfragen',
  'help_ctx_network_tip_request_desc': 'Frage ein Buch bei einem Freund an',
  'help_ctx_network_title': 'Netzwerk',
  'help_ctx_profile_content':
      'Dein Profil zeigt deine Erfolge und deinen Fortschritt als Leser.',
  'help_ctx_profile_tip_achievements': 'Erfolge',
  'help_ctx_profile_tip_achievements_desc': 'Sieh dir deine freigeschalteten Erfolge an',
  'help_ctx_profile_tip_theme': 'Design',
  'help_ctx_profile_tip_theme_desc': 'Passe das Aussehen der App an',
  'help_ctx_profile_title': 'Profil',
  'help_ctx_settings_content': 'Konfiguriere die App nach deinen Wünschen.',
  'help_ctx_settings_tip_backup': 'Sicherung',
  'help_ctx_settings_tip_backup_desc': 'Exportiere und importiere deine Daten',
  'help_ctx_settings_tip_modules': 'Module',
  'help_ctx_settings_tip_modules_desc': 'Aktiviere oder deaktiviere Funktionen',
  'help_ctx_settings_tip_sources': 'Quellen',
  'help_ctx_settings_tip_sources_desc': 'Wähle, welche Kataloge für die Buchsuche verwendet werden',
  'help_ctx_settings_title': 'Einstellungen',
  'help_ctx_shelves_content':
      'Regale ermöglichen es dir, deine Bücher nach Kategorien zu organisieren.',
  'help_ctx_shelves_tip_assign': 'Bücher zuweisen',
  'help_ctx_shelves_tip_assign_desc': 'Weise Bücher über die Buchdetails Regalen zu',
  'help_ctx_shelves_tip_create': 'Regal erstellen',
  'help_ctx_shelves_tip_create_desc': 'Erstelle thematische Regale',
  'help_ctx_shelves_title': 'Regale',
  'help_ctx_stats_genre_diversity': 'Genre-Vielfalt',
  'help_ctx_stats_loan_stats': 'Ausleih-Statistiken',
  'help_ctx_stats_monthly_progress': 'Monatlicher Fortschritt',
  'help_ctx_stats_publication_year': 'Erscheinungsjahr',
  'help_ctx_stats_reading_habits': 'Lesegewohnheiten',
  'help_ctx_stats_sales': 'Verkäufe',
  'help_ctx_stats_top_authors': 'Top-Autoren',
  'help_ctx_stats_unique_stats': 'Einzigartige Statistiken',
  'help_desc_import': 'Importiere Bücher aus einer CSV-Datei oder einer Sicherung.',
  'help_import_app': 'In die App importieren',
  'help_tips_title': 'Tipps',
  'help_topic_import': 'Wie importiere ich Bücher?',
  'hierarchical_tag_hint': 'Wähle einen Elternteil, um eine Hierarchie zu erstellen',
  'how_to_add_contact_help_desc':
      'Scanne den QR-Code eines Freundes oder füge manuell einen Kontakt hinzu.',
  'how_to_add_contact_help_title': 'Wie füge ich einen Kontakt hinzu?',
  'how_to_add_contact_qr': 'QR-Code eines Kontakts scannen',
  'how_to_show_code_help_desc': 'Zeige deinen QR-Code, damit andere ihn scannen können.',
  'how_to_show_code_help_title': 'Wie zeige ich meinen Code?',
  'how_to_show_code_label': 'Meinen Code anzeigen',
  'import_action_button': 'Importieren',
  'import_backup': 'Sicherung importieren',
  'import_backup_fail': 'Fehler beim Importieren der Sicherung',
  'import_btn': 'Importieren',
  'import_collection_success': 'Sammlung erfolgreich importiert',
  'import_file': 'Datei importieren',
  'import_method_file_desc': 'Aus einer CSV- oder Excel-Datei importieren',
  'import_method_file_title': 'Aus einer Datei',
  'import_method_paste_desc': 'Eine Liste von ISBNs oder Titeln einfügen',
  'import_method_paste_title': 'Aus der Zwischenablage',
  'import_options': 'Importoptionen',
  'import_preview_subtitle': 'Vorschau der zu importierenden Bücher',
  'import_preview_title': 'Importvorschau',
  'import_screen_title': 'Bücher importieren',
  'import_status_label': 'Importstatus',
  'importing_backup': 'Sicherung wird importiert...',
  'incoming_connections': 'Eingehende Verbindungen',
  'individual_reader': 'Einzelleser',
  'invalid_code': 'Ungültiger Code',
  'invalid_code_length': 'Ungültige Codelänge',
  'invalid_credentials': 'Ungültige Anmeldedaten',
  'invalid_isbn_scanned': 'Ungültige gescannte ISBN',
  'invalid_sale_price': 'Ungültiger Verkaufspreis',
  'isbn_already_exists': 'Diese ISBN existiert bereits in deiner Bibliothek',
  'kid': 'Kind',
  'leaderboard_cataloguer': 'Katalogisierer',
  'leaderboard_cataloguer_desc': 'Meiste katalogisierte Bücher',
  'leaderboard_collector': 'Sammler',
  'leaderboard_collector_desc': 'Meiste Bücher in der Sammlung',
  'leaderboard_empty': 'Noch keine Rangliste',
  'leaderboard_lender': 'Verleiher',
  'leaderboard_lender_desc': 'Meiste verliehene Bücher',
  'leaderboard_rank': 'Rang',
  'leaderboard_reader': 'Leser',
  'leaderboard_reader_desc': 'Meiste gelesene Bücher',
  'leaderboard_title': 'Rangliste',
  'leaderboard_you': 'Du',
  'lend_book_btn': 'Buch verleihen',
  'lend_to_contact': 'An Kontakt verleihen',
  'lent_status': 'Verliehen',
  'let_someone_scan_your_library': 'Jemanden deine Bibliothek scannen lassen',
  'level': 'Level',
  'level_apprenti': 'Lehrling',
  'level_bibliophile': 'Bibliophiler',
  'level_bronze': 'Bronze',
  'level_curieux': 'Neugieriger',
  'level_curious': 'Neugieriger',
  'level_erudit': 'Gelehrter',
  'level_gold': 'Gold',
  'level_initiate': 'Eingeweihter',
  'level_initie': 'Eingeweihter',
  'level_novice': 'Anfänger',
  'level_platine': 'Platin',
  'level_scholar': 'Gelehrter',
  'level_silver': 'Silber',
  'libraries_found': 'Bibliotheken gefunden',
  'library_name': 'Bibliotheksname',
  'library_name_required': 'Bibliotheksname ist erforderlich',
  'library_updated': 'Bibliothek aktualisiert',
  'link_device_code_instructions': 'Gib diesen Code auf dem anderen Gerät ein',
  'link_device_code_valid': 'Code gültig',
  'link_device_generate_code': 'Code generieren',
  'link_device_host_ip': 'Host-IP',
  'link_device_host_ip_hint': 'IP-Adresse des Servers',
  'link_device_join_desc': 'Einer bestehenden Bibliothek beitreten',
  'link_device_join_title': 'Beitreten',
  'link_device_pairing_code_hint': 'Kopplungscode',
  'link_device_share_desc': 'Deine Bibliothek mit einem anderen Gerät teilen',
  'link_device_share_title': 'Teilen',
  'link_device_sync_complete': 'Synchronisierung abgeschlossen',
  'link_device_verify_link': 'Verbindung überprüfen',
  'link_device_your_ip': 'Deine IP',
  'loan_statistics': 'Ausleih-Statistiken',
  'loans_and_borrowings': 'Ausleihen & Entleihungen',
  'loans_label': 'Ausleihen',
  'local_discovery_help': 'Bibliotheken in deinem lokalen Netzwerk entdecken',
  'local_network_title': 'Lokales Netzwerk',
  'login_failed_prefix': 'Anmeldefehler:',
  'login_subtitle': 'Melde dich an, um fortzufahren',
  'logout': 'Abmelden',
  'looking_up_isbn': 'ISBN wird gesucht...',
  'manage_collections': 'Sammlungen verwalten',
  'manage_login_credentials': 'Anmeldedaten verwalten',
  'manage_shelves': 'Regale verwalten',
  'manage_shelves_desc': 'Regale umbenennen, löschen oder neu organisieren',
  'manage_tags': 'Regale verwalten',
  'mark_as_finished': 'Als beendet markieren',
  'mark_as_owned': 'Als besessen markieren',
  'mark_as_read': 'Als gelesen markieren',
  'mfa_code_required': 'MFA-Code erforderlich',
  'mfa_disabled': 'MFA deaktiviert',
  'mfa_enabled': 'MFA aktiviert',
  'mfa_enter_code': 'MFA-Code eingeben',
  'mfa_manual_key': 'Manueller Schlüssel',
  'mfa_requires_server': 'MFA erfordert Servermodus',
  'mfa_scan_qr': 'QR-Code scannen',
  'mfa_setup_error': 'Fehler bei der MFA-Einrichtung',
  'mfa_setup_success': 'MFA erfolgreich eingerichtet',
  'mfa_setup_title': 'MFA einrichten',
  'mfa_verify': 'Überprüfen',
  'min_one_source_error': 'Mindestens eine Quelle erforderlich',
  'module_collections': 'Sammlungen',
  'module_collections_desc': 'Bücher in thematischen Listen gruppieren',
  'module_digital_formats': 'Digitale Formate',
  'module_digital_formats_desc': 'E-Books und Hörbücher verwalten',
  'module_gamification': 'Gamification',
  'module_gamification_desc': 'Erfolge, Level und Leseserien',
  'module_network': 'Netzwerk',
  'module_network_desc': 'Mit anderen Lesern verbinden',
  'module_quotes': 'Zitate',
  'module_quotes_desc': 'Zitate aus deinen Lieblingsbüchern speichern',
  'modules': 'Module',
  'more_actions': 'Weitere Aktionen',
  'most_lent_books': 'Meistverliehene Bücher',
  'move': 'Verschieben',
  'move_shelf': 'Regal verschieben',
  'move_shelf_hint': 'Übergeordnete Kategorie ändern',
  'moving': 'Verschieben...',
  'multiple_editions_found': 'Mehrere Ausgaben gefunden',
  'my_books': 'Meine Bücher',
  'network_discovery_desc': 'Nahegelegene Bibliotheken in deinem Netzwerk entdecken',
  'network_gamification': 'Netzwerk-Gamification',
  'network_gamification_desc': 'Vergleiche deinen Fortschritt mit anderen Lesern',
  'network_module': 'Netzwerk-Modul',
  'network_module_desc': 'Bücher teilen und ausleihen',
  'never_synced': 'Nie synchronisiert',
  'new_password': 'Neues Passwort',
  'no_available_copies': 'Keine Exemplare verfügbar',
  'no_borrowed_books': 'Keine ausgeliehenen Bücher',
  'no_collection_selected': 'Keine Sammlung ausgewählt',
  'no_collections': 'Keine Sammlungen',
  'no_contacts_hint': 'Füge Kontakte hinzu, um Bücher zu teilen',
  'no_contacts_title': 'Keine Kontakte',
  'no_copies_found': 'Keine Exemplare gefunden',
  'no_cover_available': 'Kein Cover verfügbar',
  'no_existing_tags': 'Noch keine Regale erstellt. Erstelle eines!',
  'no_local_libraries_found': 'Keine lokalen Bibliotheken gefunden',
  'no_network_members': 'Keine Netzwerkmitglieder',
  'no_password_set': 'Kein Passwort gesetzt',
  'no_reading_status': 'Kein Lesestatus',
  'no_shelves': 'Keine Regale',
  'no_sub_shelves': 'Keine Unterregale',
  'no_tags': 'Keine Tags',
  'none': 'Keine',
  'onboarding_slogan_1': 'Deine universelle Bibliothek, direkt in deiner Tasche.',
  'onboarding_slogan_2': 'Füge Bücher hinzu, indem du Barcodes scannst oder online suchst.',
  'onboarding_slogan_3': 'Verbinde dein Wissen. Teile deine Welten.',
  'onboarding_slogan_4': 'Visualisiere deine Leidenschaft. Miss deine Gelehrtheit.',
  'onboarding_swipe_hint': 'Wischen um fortzufahren',
  'or_manual_entry': 'Oder manuell eingeben',
  'organize': 'Organisieren',
  'outgoing_connections': 'Ausgehende Verbindungen',
  'own_this_book': 'Ich besitze dieses Buch',
  'own_this_book_hint': 'Als besessen in deiner Bibliothek markieren',
  'owned_vs_total': 'Besessen / Gesamt',
  'parent_shelf': 'Übergeordnetes Regal',
  'password': 'Passwort',
  'password_changed_success': 'Passwort erfolgreich geändert',
  'password_incorrect': 'Passwort falsch',
  'password_required': 'Passwort erforderlich',
  'password_too_short': 'Passwort zu kurz',
  'passwords_dont_match': 'Passwörter stimmen nicht überein',
  'peer_offline': 'Peer offline',
  'peer_offline_caching': 'Peer-Offline-Cache',
  'peer_offline_caching_desc':
      'Daten werden zwischengespeichert, wenn der Peer offline ist',
  'peer_offline_cannot_sync': 'Synchronisierung nicht möglich: Peer offline',
  'peer_offline_library_unavailable': 'Bibliothek nicht verfügbar: Peer offline',
  'peer_online': 'Peer online',
  'postal_code_label': 'Postleitzahl',
  'preparing_backup': 'Sicherung wird vorbereitet...',
  'preset_applied': 'Profil angewendet',
  'preset_bookseller': 'Buchhändler',
  'preset_librarian': 'Bibliothekar',
  'preset_reader': 'Leser',
  'price': 'Preis',
  'price_label': 'Preis',
  'profile_advantage_borrow': 'Bücher ausleihen',
  'profile_advantage_contacts': 'Kontaktverwaltung',
  'profile_advantage_inventory': 'Vollständiges Inventar',
  'profile_advantage_lend': 'Bücher verleihen',
  'profile_advantage_lending': 'Ausleihsystem',
  'profile_advantage_pricing': 'Preisverwaltung',
  'profile_advantage_sales': 'Verkaufsverwaltung',
  'profile_advantage_simple_ui': 'Vereinfachte Oberfläche',
  'profile_advantage_statistics': 'Erweiterte Statistiken',
  'profile_advantage_wishlist': 'Wunschliste',
  'profile_bookseller': 'Buchhändler',
  'profile_bookseller_desc': 'Verwalte dein Inventar und deine Verkäufe',
  'profile_restriction_no_borrow': 'Kein Ausleihen',
  'profile_restriction_no_gamification': 'Keine Gamification',
  'profile_restriction_no_lend': 'Kein Verleihen',
  'profile_restriction_no_loans': 'Kein Ausleihsystem',
  'profile_summary': 'Profilzusammenfassung',
  'profile_updated': 'Profil aktualisiert',
  'progress_hint_bibliophile': 'Lies weiter, um ein Bibliophiler zu werden',
  'progress_hint_curieux': 'Entdecke mehr, um deine Neugier zu stillen',
  'progress_hint_erudit': 'Fast ein Gelehrter',
  'progress_hint_initie': 'Du bist auf dem Weg der Einweihung',
  'qr_wifi_suggestion': 'Verbinde dich mit demselben WLAN für bessere Verbindung',
  'quick_actions_title': 'Schnellaktionen',
  'quick_borrow_book': 'Buch ausleihen',
  'quick_create_shelf': 'Regal erstellen',
  'quick_presets': 'Schnellprofile',
  'quick_presets_desc': 'Wähle ein Profil für schnelle App-Konfiguration',
  'quick_scan_barcode': 'Barcode scannen',
  'quick_search_online': 'Online suchen',
  'quote_of_the_day': 'Zitat des Tages',
  'reading_status_abandoned': 'Abgebrochen',
  'reading_status_borrowed': 'Ausgeliehen',
  'reading_status_lent': 'Verliehen',
  'reading_status_owned': 'Besessen',
  'reading_status_read': 'Gelesen',
  'reading_status_reading': 'Lese gerade',
  'reading_status_to_read': 'Zu lesen',
  'reading_status_wanting': 'Gewünscht',
  'recent_achievements': 'Letzte Erfolge',
  'recent_sales': 'Letzte Verkäufe',
  'record_sale': 'Verkauf erfassen',
  'record_sale_title': 'Verkauf erfassen',
  'refresh_apply': 'Änderungen anwenden',
  'refresh_current': 'Aktueller Wert',
  'refresh_empty': 'Leer',
  'refresh_field_author': 'Autor',
  'refresh_field_cover': 'Cover',
  'refresh_field_publisher': 'Verlag',
  'refresh_field_summary': 'Zusammenfassung',
  'refresh_field_title': 'Titel',
  'refresh_field_year': 'Jahr',
  'refresh_found': 'Online gefunden',
  'refresh_identical': 'Identisch',
  'refresh_metadata_applied': 'Metadaten aktualisiert',
  'refresh_metadata_error': 'Fehler beim Aktualisieren der Metadaten',
  'refresh_metadata_no_changes': 'Keine Änderungen',
  'refresh_metadata_not_found': 'Metadaten nicht gefunden',
  'refresh_metadata_title': 'Metadaten aktualisieren',
  'reorder_manual': 'Manuell ordnen',
  'reordering_shelf': 'Regal wird neu geordnet...',
  'reset_app': 'App zurücksetzen',
  'reset_app_confirmation': 'Wirklich zurücksetzen?',
  'reset_app_title': 'App zurücksetzen',
  'reset_confirm': 'Zurücksetzen bestätigen',
  'reset_full_desc': 'Alle Daten einschließlich Bücher und Einstellungen löschen',
  'reset_full_warning': 'Alle Daten werden unwiderruflich gelöscht!',
  'reset_standard_desc': 'Einstellungen zurücksetzen, Bücher behalten',
  'reset_type_full': 'Vollständig',
  'reset_type_label': 'Art des Zurücksetzens',
  'reset_type_standard': 'Standard',
  'return_book_btn': 'Buch zurückgeben',
  'return_rate': 'Rückgabequote',
  'role_borrower': 'Entleiher',
  'role_library': 'Bibliothek',
  'root_level': 'Stammebene',
  'root_tag': 'Wurzel (kein Elternteil)',
  'sale_date': 'Verkaufsdatum',
  'sale_notes': 'Notizen (optional)',
  'sale_price': 'Verkaufspreis',
  'sale_recorded': 'Verkauf erfolgreich erfasst',
  'sales': 'Verkäufe',
  'sales_count': 'Anzahl Verkäufe',
  'sales_statistics': 'Verkaufsstatistiken',
  'save_contact': 'Kontakt speichern',
  'scan_first_book': 'Scanne dein erstes Buch',
  'scan_friend_qr_code': 'QR-Code eines Freundes scannen',
  'scan_into_collection': 'In Sammlung scannen',
  'scan_into_shelf': 'In Regal scannen',
  'scan_isbn_barcode': 'ISBN-Barcode scannen',
  'search_btn': 'Suchen',
  'search_empty_desc': 'Keine Ergebnisse gefunden',
  'search_hint_example': 'z.B.: Harry Potter, 978-3-...',
  'search_in_library': 'In der Bibliothek suchen',
  'search_library_placeholder': 'In deiner Bibliothek suchen...',
  'search_placeholder': 'Suchen...',
  'search_sources': 'Suchquellen',
  'search_tab_editions': 'Ausgaben',
  'search_tab_list': 'Liste',
  'search_title_label': 'Titel',
  'security': 'Sicherheit',
  'security_settings': 'Sicherheitseinstellungen',
  'see_all_books': 'Alle Bücher anzeigen',
  'see_all_to_read': 'Alle zu lesen anzeigen',
  'select_book': 'Buch auswählen',
  'select_buyer': 'Käufer auswählen',
  'select_copy': 'Exemplar auswählen',
  'select_currency': 'Währung auswählen',
  'select_date': 'Datum auswählen',
  'select_edition': 'Ausgabe auswählen',
  'select_from_tree': 'Aus Baum auswählen',
  'select_lender': 'Verleiher auswählen',
  'select_new_parent': 'Neues Elternelement auswählen',
  'select_parent_optional': 'Elternteil (optional)',
  'select_profile_type': 'Profiltyp auswählen',
  'select_tags': 'Tags auswählen',
  'select_tags_title': 'Regale verwalten',
  'select_this_edition': 'Diese Ausgabe auswählen',
  'selected_books_count': '{count} Bücher ausgewählt',
  'sell_book_btn': 'Buch verkaufen',
  'server_changed': 'Server geändert',
  'server_settings_title': 'Servereinstellungen',
  'server_url_label': 'Server-URL',
  'set_password': 'Passwort setzen',
  'share_gamification_stats': 'Statistiken teilen',
  'share_gamification_stats_desc': 'Teile deine Erfolge mit Freunden',
  'shelf_books_count': '{count} Bücher',
  'shelf_created': 'Regal erstellt',
  'shelf_deleted': 'Regal gelöscht',
  'shelf_empty_desc': 'Dieses Regal ist leer',
  'shelf_management_hint': 'Verwalte deine Regale',
  'shelf_name': 'Regalname',
  'shelf_name_hint': 'z.B.: Science-Fiction',
  'shelf_statistics': 'Regalstatistiken',
  'shelf_updated': 'Regal aktualisiert',
  'show_my_code': 'Meinen Code anzeigen',
  'showing_cached': 'Zwischengespeicherte Daten werden angezeigt',
  'simplified_mode': 'Vereinfachter Modus',
  'simplified_mode_desc': 'Vereinfachte Oberfläche für Kinder',
  'sort_by_author_az': 'Nach Autor A→Z sortieren',
  'sort_by_author_za': 'Nach Autor Z→A sortieren',
  'sorted_by_author_az': 'Nach Autor A→Z sortiert',
  'sorted_by_author_za': 'Nach Autor Z→A sortiert',
  'source_bnf_desc': 'Französische Nationalbibliothek',
  'source_google_desc': 'Google Books',
  'source_inventaire_desc': 'Inventaire (Wikidata-basiert)',
  'source_openlibrary_desc': 'Open Library',
  'start_reading': 'Anfangen zu lesen',
  'started_reading_label': 'Angefangen zu lesen',
  'stat_avg_collection_completion': 'Durchschnittliche Sammlungsvollständigkeit',
  'stat_total_collections': 'Sammlungen gesamt',
  'status': 'Status',
  'status_active': 'Aktiv',
  'status_approved': 'Genehmigt',
  'status_connected': 'Verbunden',
  'status_inactive': 'Inaktiv',
  'status_loaned': 'Verliehen',
  'status_offline': 'Offline',
  'status_owned': 'Besessen',
  'status_uncategorized': 'Nicht kategorisiert',
  'status_updated': 'Status aktualisiert',
  'status_wanted': 'Gewünscht',
  'street_address_label': 'Straßenadresse',
  'sub_categories': 'Unterkategorien',
  'sync_collection': 'Preise synchronisieren',
  'sync_success': 'Preise synchronisiert',
  'synced_days_ago': 'Vor {count} Tagen synchronisiert',
  'synced_hours_ago': 'Vor {count} Stunden synchronisiert',
  'synced_just_now': 'Gerade synchronisiert',
  'synced_minutes_ago': 'Vor {count} Minuten synchronisiert',
  'tab_list': 'Liste',
  'tab_members': 'Mitglieder',
  'tag_created_success': 'Regal erstellt: ',
  'tag_creation_error': 'Fehler beim Erstellen des Regals',
  'tag_experimental': 'Experimentell',
  'tag_name_hint': 'Regalname',
  'tags_label': 'Regale',
  'tap_to_view': 'Tippen zum Anzeigen',
  'text_size': 'Textgröße',
  'text_size_default': 'Normal',
  'text_size_large': 'Groß',
  'text_size_small': 'Klein',
  'top_borrowers': 'Top-Entleiher',
  'top_collections': 'Top-Sammlungen',
  'top_shelves': 'Top-Regale',
  'total_collections': 'Sammlungen gesamt',
  'total_loans': 'Ausleihen gesamt',
  'total_revenue': 'Gesamtumsatz',
  'total_shelves': 'Regale gesamt',
  'track_cataloguer': 'Katalogisierer',
  'track_collector': 'Sammler',
  'track_lender': 'Verleiher',
  'track_reader': 'Leser',
  'two_factor_auth': 'Zwei-Faktor-Authentifizierung',
  'type_contact_details': 'Kontaktdaten eingeben',
  'understood': 'Verstanden',
  'username': 'Benutzername',
  'verification_failed': 'Überprüfung fehlgeschlagen',
  'verify': 'Überprüfen',
  'view_carousel': 'Karussellansicht',
  'view_existing': 'Vorhandene anzeigen',
  'view_list': 'Listenansicht',
  'view_online': 'Online anzeigen',
  'wizard_add_desc': 'Bücher per Scan oder manuell hinzufügen',
  'wizard_add_title': 'Bücher hinzufügen',
  'wizard_books_view_desc': 'Wechsle zwischen Raster- (Regal) und Listenansicht.',
  'wizard_contacts_add_desc': 'Füge Freunde oder Entleiher hinzu, um Bücher zu teilen.',
  'wizard_contacts_add_title': 'Kontakt hinzufügen',
  'wizard_contacts_filter_desc': 'Filtere nach Entleihern (lokal) oder Bibliotheken (P2P).',
  'wizard_contacts_filter_title': 'Kontakte filtern',
  'wizard_menu_desc': 'Navigiere durch die App-Funktionen',
  'wizard_menu_title': 'Menü',
  'wizard_search_desc': 'Suche Bücher in externen Katalogen',
  'wizard_search_title': 'Online suchen',
  'wizard_skip': 'Überspringen',
  'wizard_stats_desc': 'Verfolge deine Lesestatistiken',
  'wizard_stats_title': 'Statistiken',
  'works': 'Werke',
  'young_reader_mode': 'Junger-Leser-Modus',
  'young_reader_mode_desc': 'Vereinfachte Oberfläche für Kinder',
  'your_current_level': 'Dein aktuelles Level',
  'your_progress': 'Dein Fortschritt',
  'link_device_enter_code': 'Code eingeben',
  'link_device_scan_or_type': 'Kopplungscode scannen oder eingeben',
  'link_device_verify': 'Überprüfen',
  'saving_changes': 'Änderungen werden gespeichert...',
  'nav_report_bug': 'Fehler melden',
};
